#import "@preview/noteworthy:0.4.0": *
#import "@preview/theorion:0.6.0": *
#import "@local/moremath:0.1.0": *
#show: show-theorion

#set math.equation(numbering: "(1.1)")
#set page(numbering: "1")
#set heading(numbering: "1.1")
#set enum(numbering: "(i)")
#set text(font: "New Computer Modern")

#show link: set text(fill: rgb("#4a6e2e"))

// Prevents inline math line breaking
#show math.equation.where(block: false): box

#v(1fr)
#show title: set text(size: 30pt)
#title("Mathematical Data Analysis")

#v(1fr)

#outline()

#v(1fr)
#pagebreak()
= Setup
Assume that $(X', cal(A))$ is a measurable space and that $(Y,d)$ is a metric space.
- Given a dataset $cal(D) = {(x_n,y_n) | n = 1, dots, N } subset X' times Y$.
- Data model: That is $f^*: X' -> Y $ (unknown) which generates the data, i.e. $f^*(x_n) = y_n$.
- Goal: Learn $f^*$ from the data $cal(D)$, or a good approximation.

We cannot treat the dataset in full generality, we have to make some assumptions.
These are
== Data generation process
*Assumption*: There is an (unknown) probability measure $P$ on $X' times Y$, $P: cal(A) times.o cal(L)(Y) -> [0,1]$.
$cal(L)(Y)$ is the Borel $sigma$-algebra on $Y$.
$(x,y)$ is drawn independently according to $P$ s.t.
1. $x$ is drawn according to the marginal probability measure $P_(X'): cal(A) -> [0,1]$
2. $y$ is generated according to the conditional probability measure $P(dot.c | x): cal(L)(Y) -> [0,1]$.

#note[Note that there is uncertainty in both the input $x$ and the output $y$.]
== Learning Process
The quality of an approximation $f: X' -> Y$ to $f^*$ will be measured point-wise by a so-called loss function:
$
  L: X' times Y times Y -> [0,oo),
$
which has the property that $L$ gets smaller if $f(x)$ is close to $y$.
Consider the average loss
$
  R_(L, P) (f) = integral_(X' times Y) L(x, y, f(x)) dif P(x,y) = integral_(X') integral_Y L(x, y, f(x)) dif P(y | x) dif P_(X') (x).
$
(Can be consideredas non-linear functional on some measureable function space).
$R_(L,P)$ is called the *risk functional*.

The best possible function $f: X' -> Y$ is given by $inf {R_(L,P) (f) | f in X'^Y} =: R_(L,P)^*$.
This task is infeasible since $P$ is not known.
// #question[

*Questions:*
1. Can we determine from $cal(D)$ a function $f_(cal(D)): X' -> Y$ s.t. $|R_(L,P) (f_cal(D)) - R_(L,P)^*|$ is small?
2. Can we make $|R_(L,P) (f_cal(D)) - R_(L,P)^*|$ smaller when $|cal(D)|$ gets larger?

Since only $cal(D)$ is known, we replace $R_(L,P)$ by
$
  R_(L,cal(D)) = 1/N sum_(n=1)^N L(x_n, y_n, f(x_n)),
$
which we call the *Empirical risk functional*.
Consider
$
  inf {R_(L,cal(D)) (f) | f in X'^Y}.
$
Usually this doesn't produce a good approximation:
$
  f^* (x) = sum_(n=1)^N y_n delta_(x_n) (x),
$
where $delta_x (y) = cases(1 quad &x=y, 0 &"otherwise")$.
Clearly $R_(L,D) (f^*) = inf {R_(L,D) (f) | f in X'^Y}$
#figure(
  image("images/overfitting.jpeg", width: 70%),
  caption: "Overfitting because the function space is too big and the perfect minimizer is 'ugly'."
)<img:overfitting>

To avoid overfitting we have to restrict the class of functions, i.e. going from $X'^Y$ to some $cal(F) subset X'^Y$.

= Mathematical Foundation
$(X',cal(A))$ is a measurable space, $(Y,d)$ is a metric space $P: cal(A) times.o cal(L)(Y) -> [0,1]$.

#lemma[
Let $(X',cal(A))$ be a measurable space, $(Y,d)$ a metric space, $P: cal(A) times.o cal(L)(Y) -> [0,1]$.
Then there is a mapping $P(dot.c | dot.c): cal(L)(Y) times X' -> [0,1]$ s.t.
1. $P(dot.c | x)$ is a probability measure on $cal(L)(Y)$,
2. the mapping $X'->[0,1]$, $x |-> P(B | x)$, $B in cal(L)(Y)$ is measurable for all $B in cal(L)(Y)$,
3. $forall (A,B) in cal(A) times.o cal(L)(Y): P(A times B) = integral_A P(B|x)dif P_X' (x)$.]

- $P(dot.c|dot.c)$ is called regular conditional probability measure.
- $P_X'$ is the marginal probability measure defined by
$
  P_X' (A) = P(pi^(-1) (A)),
$
where $pi: X' times Y -> X'$ is a projection.

#proof[
Assume $S = {(x_n,y_n) : n = 1, dots, n} subset.eq X' times Y$ independently generated according to $P$.
Suppose that $Y subset.eq RR$.]

#definition[
Let $(X', cal(A))$ be a measurable space, $Y subset.eq RR$ be closed.
The function $L: X' times Y times RR -> [0, oo)$ is called a *loss function* if it is measurable.
$L(x, y, f(x))$ is the point-wise error.]

#definition[
Let $L: X' times Y times RR -> [0,oo)$ be a loss function and let $P$ be a probability measure on $X' times Y$.
For any measurable function $f: X' -> RR$ the *$L$-risk* is
$
  R_(L,P) (f) &= integral_(X' times Y) L(x, y, f(x)) dif P(x, y) \
  &= integral_X' integral_Y L(x, y, f(x)) dif P(y|x) dif P_X' (x).
$
The *empirical measure* is
$
  D = 1/N sum_(n=1)^N delta_((x_n, y_n)),
$
and the related *empirical risk* is
$
  R_(L,D) (f) = 1/N sum_(n=1)^N L(x_n, y_n, f(x_n)).
$
]

#remark[Due to assumptions that $D$ respectively $S$ are i.i.d. samples generated by $P$, and by assuming $R_(L,P)(f) < oo$ by the law of large numbers
$
  |R_(L,P) (f) - R_(L,D) (f)|
$
is small with high probability if $|S|$ is large.
]

#definition[
Let $L: X' times Y times RR -> [0, oo)$ be a loss function, $P$ a probability measure on $X times Y$.
The minimum $L$-risk $R_(L,P)^* = inf{R_(L,P)(f) | f: X'->Y "measurable"}$ is called *Bayes risk*.
The minimizer $f^*: X' -> Y$ (i.e. $R_(L,P)(f^*) = R_(L,P)^*)$ is called the *Bayes decision function*.]

#definition[
1. $L: Y times RR -> [0, oo)$ is called *supervised loss function* if it is measurable
2. $L: X' times RR -> [0, oo)$ is called *unsupervised loss function* if it is measurable]

#example[
1. $L_2: Y times RR -> [0,oo), L_2 (y,t) = (y-t)^2$\
We have the $L_2$-risk
$
  R_(L_2,P) (f) = integral_X integral_Y (y - f(x))^2 dif P(y|x) dif P_X' (x)
$
$L_2$ is called the least squares loss.\
Let
$
  f_P (x) &:= integral_Y y dif P(y|x)\
  sigma_P^2 (x) &:= integral_Y (y-f_P (x))^2 dif P(y|x)
$
and $sigma_P^2 = integral_X' sigma_P^2 (x) dif P_X' (x)$.
Then
$
  R_(L,P) (f) &= integral_(X' times Y) (y - f_P (x) + f_P (x) - f(x))^2 dif P(x,y)\
  &= integral_X' (f(x) - f_P (x))^2 dif P_X' (x) + sigma_P^2 + 2 integral_X' integral_Y (f(x) - f_P (x))(f_P (x) - y) dif P(y|x) dif P_X' (x)
$
Note that
$
  integral_Y (f_P (x) - y) dif P(y|x) = 0.
$
Hence
$
  R_(L,P) (f) = integral_X' (f(x) - f_P (x))^2 dif P_X' (x) + sigma_P^2.
$
Then it is easy to see that $f_P = "argmin"_(f: X'->Y) R_(L,P) (f)$.
A potential modification of this loss is for $p in (0, oo)$ the loss $ L_p (y,t) = |y-t|^p$.

#figure(
  image("images/Lp_loss.jpeg", width: 70%),
  caption: "L_p losses for different p."
)<img:lp_loss>

2. *Density Level Detection*
Let $mu$ be a probability measure on $X'$ and $g: X' -> [0,oo)$ desnity w.r.t. $mu$.
$
  nu = g mu
$
*Goal*: Learn the regions where $g$ is highly concetrated, i.e. for $rho > 0$ look at sets $zeta_rho = {x in X' | g(x) >= rho }$.
Consider the loss function $ L(x, t) = II_((-oo,0]) ((g(x) - rho) rho g h (t)), quad x in X', t in RR. $
$L(x, f(x))$ penalizes functions $f: X' -> RR$ if
$
  f(x) >= 0 &and g(x) < rho \
  f(x) < 0 &and g(x) > rho.
$
$L$ is an unsupervised loss function.
]

= Loss Functions
== Properties of loss functions
$(X', cal(A))$ is a measurable space, $Y subset.eq RR$, $cal(L)(Y)$.
$ cal(L)_0 (X', Y) = {f: X'->Y | f "is" cal(A) dot cal(L)(Y) "measurable"} $
Let $cal(F) subset cal(L)_0 (X', Y)$, and $d: cal(F) times cal(F) -> [0,oo)$ metric on $cal(F)$.
Assume that $(cal(F), d)$ is complete and separable.
Let $cal(L)(cal(F))$ be the Borel $sigma$-algebra.
The metric dominates point-wise convergence if
$
  lim_(n->oo) d(f_n, f) = 0 ==> lim_(n->oo) |f_n (x) - f(x)| = 0
$
holds for all $x in X'$ and $(f_n) subset cal(F)$.

#example[
  Let $X'$ be a compact metric space, $cal(F) = C(X')$. Then $d(f,g) = ||f-g||_oo$, $(cal(F), d)$ is complete and separable due to Stone-Weierstrass.
]

#example[
  Another example is the class of reproducing kernel Hilbert spaces (RKHS).
]

#proposition[
  Let $cal(F) subset cal(L)_0 (X', Y)$ be a space which dominates pointwise convergence.
  Then 
  1. The mapping $cal(F) times X' -> RR, (f,x) |-> f(x)$ is measurable.
  2. The mapping $X' times Y times cal(F) -> [0,oo), (x,y,f) |-> L(x,y,f(x))$ is measurable.
  3. If $cal(P)$ is a probability measure on $X' times Y$, then the mapping $R_(L,P): cal(F) -> [0,oo), R_(L,P) (f) = integral_(X'times Y) L(x,y,f(x)) dif P(x,y$ is measurable.
]
#proof[
  1. $(cal(F), d)$ is a function space s.t. $d$ dominates pointwise convergence.
    Hence: $cal(F) -> RR, f |-> f(x)$ is continuous on $(cal(F), d)$.
    We use the collowing result without proof:
    - Let $(X', cal(A))$ be a measurable space and $Z$ be a Polish space with Borel $sigma$-algebra $cal(L)(Z)$.
      Suppoose $phi: X' times Z -> RR$ with
      1. $phi(x,dot): X-> RR$ is continuous for all $x in X'$.
      2. $phi(dot,z): Z -> RR$ is measurable for all $z in Z$.
      Then $phi$ is measurable.
    Apply the above statement to get 1.
  2. Follows from 1.
  3. Is a consequence of _Tonelli's theorem_.
]

#definition[
  A loss function $L: X' times Y times RR -> [0,oo)$ is called
  1. continuous if $L(x,y,dot)$ is continuous for all $(x,y) in X' times Y$,
  2. (strictly) convex if $L(x,y,dot)$ is (strictly) convex for all $(x,y) in X' times Y$,
]

#proposition[
  Let $L: X' times Y times RR -> [0,oo)$ be a loss function which is (strictly) convex and $P$ a probability measure on $X' times Y$.
  Then $R_(L,P): cal(L)_0 (X',Y) -> [0,oo)$ is (strictly) convex.
]
#proof[
  Proof is an easy exercise for the reader.
]

In general, the following
$ R_(L,P)(f) = integral_(X' times Y) L(x,y,f(x)) dif P(x,y) $
is a nonlinear functional.
We therefore have to clarify a couple of things:

// #definition[
//   #box(fill: red)[TODO:]
//   By $cal(L)^P (X', P_X')$ we mean functions that are pointwise 
// ]

#note[
  Question: If $(f_n)_(n in NN) subset cal(L)_0 (X', y)$ with $f_n (x) -> f(x)$ and assume $L$ to be continuous.
  Do we then have $R_(L,P) (f_n) -> R_(L,P) (f)$?
  
  Note: $L(x,y,f_n (x)) -> L(x,y,f(x)) not(==>) R_(L,P) (f_n) -> R_(L,P) (f)$.
]

#proposition[
  Let $L$ be a continuous loss function, $P$ a probability measure on $X' times Y$, and $(f_n)_(n in NN) subset cal(L)_0 (X',Y)$ with $lim_(n->oo) P_X' {|f_n (x) - f(x) | >= epsilon } = 0 forall epsilon > 0$ (convergence in probability).
  Then $R_(L,P) (f) <= liminf_(n->oo) R_(L,P) (f_n)$ (i.e. $R_(L,P)$ is lower semi-continuous).
]
#proof[
  $(f_n)_(n in NN)$ converges to $f$ in probability.
  We choose a subseqence $(f_(n_k)_(k in NN) subset (f_n)_(n in NN)$ s.t.
  1. $lim R_(L,P) (f_(n_k)) = liminf_(n->oo) R_(L,P)(f_n)$,
  2. $f_(n_k) -> f(x)$ for $P_X'$-almost all $x in X'$.
  By continuity of $L$ we have $L(x,y,f_(n_k)(x)) -> L(x,y,f(x))$ for $P$-almost all $(x,y) in X' times Y$.
  By Fatou's lemma we get:
  $
    R_(L,P) (f) &= integral_(X' times Y) lim_(k->oo) L(x,y,f_(n_k)(x)) dif P(x,y)\
                &<=^("Fatou") liminf_(k->oo) integral_(X' times Y) L(x,y,f_(n_k)(x)) dif P(x,y)\
                &= liminf_(n->oo) R_(L,P) (f_n).
  $.
]

#remark[
  If there is an integrable majorant of $L(dot, dot, f_n (dot))$ then by the dominated convergence theorem, we would have $R_(L,P) (f) = lim_(n->oo) R_(L,P) (f_n)$.
]

#definition[
  A loss function $L$ is called *Nemitski* loss function if ther is a measurable $b: X' times Y -> [0,oo)$ and an increasing $h: [0,oo) -> [0,oo)$ such that
  $
    L(x,y,t) <= b(x,y) + h(t) quad forall (x,y,t) in X' times Y times RR.
  $<eq:nemytski>
  L is called Nemitski floss function of order $p in (0,oo)$ if
  $
    L(x,y,t) <= b(x,y) + c |t|^p quad forall (x,y,t) in X' times Y times RR.
  $
]

If $b in L^1 (X' times Y, P)$ and $L$ satisfiess @eq:nemytski with $b$, then $L$ is $P$-integrable Nemitski Loss Function (NLF).

Assume $L$ is $P$-integrable NLF, $f in L^oo (X', P_X')$ then $R_(L,P) < oo$.
In particular, $R_(L,P) (0) < oo$, hence $R_(L,P)^* = inf {R_(L,P) (f): f in cal(L)_0 (X',Y)} < oo$.

#proposition[
  Let $P$ be a probability measure on $X' times Y$, $L$ continuous, $P$-integrable LF.
  Then
  1. $(f_n)_(n in NN)$ sequence of measurable functions with $||f_n||_oo < B$ for all $n in NN$.
    If $f: X' -> RR$ is a function with
    $
      lim_(n->oo) P_X' {sup_(m >= n) |f_n (x) - f(x)| > epsilon} = 0 quad forall epsilon > 0 quad "(conv. almost surely)",
    $
    Then $lim_(n->oo) R_(L,P) (f_n) = R_(L,P) (f)$. 
  2. The mapping $R_(L,P): L^oo (X',P_X') -> [0,oo)$ is well-defined and continuous.
  3. If $L$ is of order $p in [1,oo)$, then $R_(L,P): L^p (X', P_X') -> [0,oo)$ is well-defined and continuous.
]

#proof[
  (later)
]

#definition[
  A loss function $L: X' times Y times RR -> [0,oo)$ is locally Lipschitz continuous if for all $r >= 0$ there is $C_r >= 0$ such that
  $
    sup_((x,y) in X' times Y) |L(x,y,t) - L(x,y,t')| <= C_r |t-t'| quad forall t,t' in [-r,r].
  $<eq:lipschitz_lf>
  Lipschitz constant: $ |L|_(r,1) = inf {C_r | C_r "satisfiess" #[@eq:lipschitz_lf]}$.
  If $sup_(r>=0) |L|_(r,1) =: |L|_1 < oo$.
]

#proposition[
  If $L$ is locally Lipschitz continuous, then $forall B,f,g in L^oo (X', P_X')$, s.t. $||f||_oo, ||g||_oo <= B$,
  we get
  $
    |R_(L,P) (f) - R_(L,P) (g)| <= |L|_(B,1) integral_(X') |f(x) - g(x)| dif P_X' (x).
  $
]

#note[
  Motivation: We want to minimize the non-linear object $R_(L,P) (f)$.
  Therefore we need to differentiate w.r.t. $f$.
  But $R_(L,P): cal(F) -> [0,oo)$ ($cal(F)$ is infinite-dimensional).
]

#definition[
  A loss function $L: X' times Y times RR -> [0,oo)$ is called differentiable if $L(x,y,dot)$ is differentiable for all $x in X'$, $y in Y$.
]

#definition[
  Let $V, W$ be Banach spaces. $F: V->W$ is Fréchet differentiable if there is a linear map $A: V->W$ s.t. $ lim_(h -> bold(o)) (||F(v+h) - F(v) - A v||_W)/(||h||_V) = 0. $
]

#proposition[
  Let $L: X' times Y times RR -> [0, oo)$ be a differentiable loss function and $L,|L'|$ are $P$-interable Nemitski loss functions.
  Then $ R_(L,P): L^oo (X',P_X) -> [0,oo) $ is Fréchet differentiable with Fréchet derivative at $f in L^oo (X', P_X)$ being $ R'_(L,P)(f) in B(L^oo,RR), $
  where $ R'_(L,P)(f) g = integral_(X' times Y) g(x) L'(x,y,f(x)) dif P(x,y). $
]<prop:frechet>

#proof[
  $L': X' times Y times RR -> [0,oo)$ is measurable because $ L'(x,y,t) = lim_(n->oo) (L(x,y,t+1/n) - L(x,y,t))/(1/n) $ for $(x,y,t) in X' times Y times RR$.
  Let $f in L^oo (X', P_X')$, $(f_n)_(n in NN) subset L^oo (X', P_X')$, $f_n != 0 (n in NN)$, $lim_(n->oo) ||f_n||_oo = 0$, $||f_n||_oo <= 1 (n in NN)$.
  Define
  $ G(x,y) = |1/(f_n (x)) {L(x,y;f(x) + f_n (x)) - L(x,y;f(x))} - L'(x,y,f(x))| $
  if $f_n (x) != 0$ and $G(x,y) = 0$ otherwise.
  Then
  $
    &1/(||f_n||_oo) |R_(L,P)(f+f_n) - R_(L,P)(f) - R'_(L,P)(f)f_n| \
    &<= integral_(X' times Y) 1/(||f_n||_oo) |L(x,y,f(x) + f_n (x)) - L(x,y,f(x)) - f_n (x)L'(x,y,f(x))| dif P(x,y)\
    &<= integral_(X' times Y) G(x,y) dif P(x,y).
  $
  For $(x,y) in X' times Y$ we have $lim_(n->oo)G_n (x,y) = 0$.
  For $f_n (x) != 0$, the mean value theory gives the existence of $g_n (x,y)$ s.t. $|g_n (x,y)| in [0,|f_n (x)|]$ with
  $ 1/(f_n (x)) {L(x,y,f(x) + f_n (x)) - L(x,y,f(x))} = L'(x,y,f(x)+g_n (x,y)). $
  By assumpption $L'$ is $P$-integrable Nemitski loss function.
  Hence  there is a $b in L^1 (X' times Y, P)$ and increasing $h$ s.t.
  $ |L'(x,y,t)| <= b(x,y) + h(t) wide forall x,y,t in X' times Y times RR. $
  In combination with $||f_n||_oo <= 1$ and assuming $f_n (x) != 0$ for all $x in X'$.
  Then:
  $
    &1/(f_n (x)) {L(x,y,f(x) + f_n (x)) - L(x,y,f(x))} \
    &<= b(x,y) + h(|f(x) + g_n (x,y)|)\
    &<= b(x,y) + h(||f||_oo + 1).
  $
  Hence $G_n (x,y) <= 2 b(x,y) + 2 h(||f||_oo + 1)$ for every $(x,y) in X' times Y$.
  The rest follows by dominated convergence.
]

== Special Classes of Loss Functions
=== Distance-based loss functions
#definition[This is supposed to be definition 3.17][
  $L: Y times RR -> [0,oo)$ is called a distance-based loss function if there is $psi: RR -> [0,oo)$, $psi(0) = 0$, and $L(y,t) = psi(y-t)$.
  $L$ is called symmetric if $psi(r) = psi(-r)$.
]

#proposition[This is supposed to be example 3.18][
  Let $L(y,t) = psi(y-t)$.
  Then
  1. $L$ is (strictly) convex iff $psi$ is (strictly) convex,
  2. $L$ is continuous iff  $psi$ is continuous,
  3. $L$ is Lipschitz continuous iff $psi$ is Lipschitz continuous.
]

#proof[By inspection.]

#remark[
  Local Lipschitz continuity of $psi$ does not imply the local Lipschitz continuity of $L$.
  Consider as a counter example $psi(r) = r^2$.
  Then
  $
    sup_(y in Y) |L(y,t)-L(y,t')|
    = sup_(y in Y) |(y-t)^2 - (y-t')^2|
    = ( sup_(y in Y) |(t-t') - 2y| ) |t-t'|
    = oo.
  $
]

=== Margin-based loss functions
Let $Y = {-1, 1}$.

#definition[This is supposed to be definition 3.14][
  A supervised LF $L: Y times RR -> [0,oo)$ is called margin-based if there is $phi: RR->[0,oo)$ s.t. $L(y,t) = phi(y dot t)$.
]

#proposition[This is supposed to be proposition 3.15][
  Let $L$ be a margin-based LF $L(y,t) = phi(y dot t)$.
  Then
  1. $L$ is (strictly) convex iff $phi$ is (strictly) convex,
  2. $L$ is continuous iff $phi$ is continuous,
  3. $L$ is (locally) Lipschitz iff $phi$ is locally Lipschitz,
  4. if $L$ is convex, then it is locally Lipschitz,
  5. $L$ is $P$-integrable Nemitski LF for all probability measures $P$ on $X' times Y$.
]
#proof[Exercise. The reader is left to the proof.]

#example[This is supposed to be example 3.16][
  1. *Binary classification loss function*
    $ L(y,t) = II_((-oo,o]) (y "sgn"(t)) $
    is not margin-based.
  2. *Least squares loss function*
    $ L_2 (y,t) = (y-t)^2 = (1-y t)^2 $
    is margin-based, strictly convex, and for $a>0$ it is locally Lipschitz continuous
    $ |L_2|_(a,1) = 2a + 2. $
  3. *Hinge loss function*
    $ L_H (y,t) = max{0, 1-y t}. $
    Find out about properties (Exercise).
  4. *Logistic loss function*
    $ L_log (y,t) = log(1 + e^(-y t)). $
    Find out about properties (Exercise).
]

=== Growth of distance-based LF
Let $p in (0,oo)$, $L(y,t) = psi (y-t)$.
$L$ is called
- *$p$-upper bounded* if there is a $G>0$ s.t.
  $ psi(r) <= G ( |r|^p + 1 ) quad forall r in RR, $
- *$p$-lower bounded* if there is a $c>0$ s.t.
  $ psi(r) >= c ( |r|^p - 1 ) quad forall r in RR, $
- *growth type $p$* if it is $p$-lower and upper bounded:
  $ c(|r|^p - 1) <= psi(r) <= G(|r|^p + 1) quad forall r in RR.$

#proposition[
  Let $L(y,t) = psi(y-t), p in (0,oo)$.
  Then
  1. if $psi$ is convex with $lim_(|r|->oo) psi(r) = oo$, then $L$ is $1$-lower bounded,
  2. if $psi$ is Lipschitz continuous, then $L$ is $1$-upper bounded,
  3. if $psi$ is convex, then for every $r>0$
    $ |psi | [-r,r] |_1 <= 2/r ||psi | [-2r,2r] ||_oo <= 4 |psi | [-2r,2r]|_1. $<eq:convexity_implication>
]

#proof[
  Use the following result:
  #box(stroke: black, outset: 4pt, radius: 4pt, width: 100%)[
  Let $f: RR->RR$ be convex.
  Then $f$ is locally Lipschitz continuous and $|f | [-t,t]|_1 <= 2/t ||f | [-2t,2t]||_oo$.
  If in addition $f(0) = 0$, then the mapping $r|->f(r)/r$ is increasing on $(0,oo)$ and
  $ ||f | [-t,t] ||_oo <= t |f | [-t,t]|_1 $
  ]
  1.-3. follow with this (exercise).
]

=== $P$-integrable distance-based loss functions
Let $Q$ be a probability measure on $RR$, $p in (0,oo)$.
The $p$-the moment of $Q$ is $ |Q|_p := (integral_RR |y|^p dif Q(y))^(1/p). $
For $p=oo$ define $ |Q|_oo := |"supp"(Q)|. $

#remark[
  $|Q|_p$ is not necessarily finite.
  $|Q|_p < oo$ iff $Q$ has compact support.
  If $0 < q <= p < oo$, then $|Q|_q <= |Q|_p$.
]

Define $ I_(L,Q)(t) = integral_RR L(y,t) dif Q(y). $

#proposition[
  1. If $L$ is of growth type $p in (0,oo)$, then there is $C_(L,p) > 0$independent of $Q$ s.t.
    $ I_(L,Q)(t) <= C_(L,p)(|Q|_p^p + |t|^p + 1). $
  2. If $L$ is $p$-lower bounded, then there is $C_(L,p) > 0$ independent of $Q$ s.t. $|Q|_p^p<= C_(L,p)(I_(L,Q)(t) + |t|^p + 1)$ and $|t|^p <= C_(L,p)(I_(L,Q)(t) + |Q|_p^p + 1) $
  3. If $L$ is of growth type $p$, then $ I_(L,Q)^* = inf_(t in RR) I_(L,Q) (t) < oo. $
]
#proof[
  1. $L$ is of growth type $p$, then
    $ L(y,t) = psi(y-t) <= c(c_p(|y|^p + |t|^p)+1). $
    This gives $ I_(L,Q)(t) = integral_RR L(y,t) dif Q(y) <= c' (|Q|_p^p + |t|^p) + c. $
  2. Without loss of generality assume $I_(L,Q)(t)<oo.$
    Then
    $
      |Q|_p^p &= integral_RR |y|^p dif Q(y) <= c_p integral_RR (|y-t|^p + |t|^p) dif Q(y) \
      &= c_(L,P) (I_(L,Q)(t) + |t|^p + 1).
    $
    Second statement follows analogously.
  3. Consequence of 1. and 2.
]

Let $P$ be a probability measure on $X' times Y, p in (0,oo)$.
Define $ |P|_p := (integral_(X' times RR) |y|^p dif P(x,y))^(1/p). $
Then $ |P|_p = (integral_X' |P(dot|x)|_p^p dif P_X' (x))^(1/p). $
Also define $ |P|_0 = 1, quad |P|_oo = "ess-sup"|P(dot|x)|_oo. $

#proposition[
  Let $L(y,t) = psi(y-t)$, $P$ a probability measure on $X' times Y$, $p in (0,oo)$.
  Then the following statements hold.
  1. If $L$ is $p$-upper bounded, then there is $c_(L,p) > 0$ independent of $P$ s.t.
    $ R_(L,P)(f) <= c_(L,p)(|P|_p^p + ||f||_(L^p (X',P_X'))^p + 1) "for" f in cal(L)^0 (X'). $
    If $|P|_p < oo$, then $L$ is a $P$-integrable Nemitski loss function of order $p$.
    Moreover, $ R_(L,P): L^p (X',P_X')->RR$ is well-defined.
  2. If $L$ is convex and $p$-upper bounded for $p>=1$, then for $q in (p-1,oo)$ there is $c_(L,p,q)>0$ independent of $P$ s.t.
    $ |R_(L,P)(f) - R_(L,P)(g)| <= c_(L,p,q) {|p|^(p-1)_q + ||f||_q^(p-1) + ||g||_p^(p-1) + 1} ||f-g||_S, $
    with $ S = p / (q-p+1). $
  3. If $L$ is $p$-lower bounded, then there is $c_(L,p)>0$ independent of $P$ s.t.
    - $|P|_p^p <= c_(L,p) {R_(L,P)(f) + ||f||_p^p + 1}$
    - $||f||_p^p <= c_(L,p) {R_(L,P)(f) + |P|_p^p + 1}$
    for every $f in cal(L)^0 (X').$
]
#proof[Skipped for now.]

#example[
  1. *$L^p$-loss function*: $L_p (y,t) = |y-t|^p$.
    Then we have:
    1. $L$ is of growth type $p$,
    2. $L$ is convex iff $p>=1$ and strictly convex if $p>1$,
    3. $L_p$ is Lipschitz continuous iff $p=1$.

    #figure(
      image("images/not_banach_space.jpeg", width: 75%),
      caption: [For $p < 1$ the space $L^p$ is not a Banach space.]
    )
  2. *Logistic loss function*: $L_log (y,t) = psi(y-t)$ with $psi(r) = -log((4e^r)/(1+e^r)^2), r in RR$
    We have
    1. $L_log$ is Lipschitz continuous and of growth type $p=1$.
  3. *Huber loss function*: For $alpha>0$ define
    $ psi(r) = cases(1/2 r^2 quad &|r|<= alpha, alpha |r| - 1/2 alpha^2 &"elsewhere".) $
    $ L_H_alpha (y,t) = psi(y-t)$ has the following properties:
    1. it is convex, but not strictly convex,
    2. it is Lipschitz continuous and of growth type $p=1$.
  4. *$epsilon$-insensitive loss function*: For $epsilon>0$ let $psi(r) = max{0,|r|-epsilon}.$
    $ L_epsilon (y,t) = psi(y-t)$ has the following properties:
    1. it is Lipschitz continuous,
    2. it is convex, but not striclty convex, and it is of growth type $p=1$.
]

= Reproducing Kernel Hilbert Spaces
Let $X' != emptyset$ be a set. $CC^X' = {f:X'->CC}.$
A Hilbert space $cal(H) subset CC^X'$ is called Hilbert space of functions (HSF).
#definition[
  A HSF is called reproducing kernel Hilbert space (RKHS) if the functionals
  $ delta_x: cal(H) -> CC, quad delta_x (f) = f(x), quad x in X',$
  are *continuous*.
  That means there is a constant $c_x >= 0$ s.t.
  $ |delta_x (f)| <= c_x ||f||_cal(H) quad forall f in cal(H). $
]

By Riesz representation theorem, for every $x in X'$ there is $K_x in cal(H)$ s.t.
$ f(x) = delta_x (f) = chevron.l f, K_x chevron.r_cal(H) wide "(reproducing property)". $
The map $K_x: X' -> CC, quad K_x (x') =: K(x,x')$ is called *reproducing kernel*.

#proposition[
  Let $hh$ be a RKHS with kernel $K$.
  Then
  1. $K(x,x') = chevron.l K_x, K_x' chevron.r _hh quad forall x,x' in X'$,
  2. $K(x,x') = overline(K(x',x)) quad forall x, x' in X'$,
  3. $K(x,x) >= 0 quad forall x in X'$,
  4. If $K(x,x) = 0$ for $x in X'$, then $delta_x = 0$,
  5. $|K(x,x')|^2 <= K(x,x) K(x',x') quad forall x,x' in X'$,
  6. $K: X' times X' -> CC$ is positive definite, i.e.
    1. $ sum_(i=1)^N sum_(j=1)^N c_i overline(c_j) K(x_j, x_i) >= 0$ for all $N in NN, c_1, ..., c_N in CC, x_1, ..., x_N in X'$.
      Moreover, $delta_x_i, i=1,...,N$ are linearly independent if
    2. $ sum_(i=1)^N sum_(j=1)^N c_i overline(c_j) K(x_j, x_i) > 0$ for all $N in NN, c_1,...,c_N in CC, x_1,...X_N in X'$.
  7. the reproducing kernel $K$ for $hh$ is unique.
]

#proof[
  1.~-~5. are straightforward.

  6. Let $N in NN, c_1, ..., c_N in CC, x_1, ..., x_N in X'$
    $ sum_(i=1)^N sum_(j=1)^N c_i overline(c_j) K(x_j, x_i) = sum_(i=1)^N sum_(j=1)^N c_i overline(c_j) chevron.l K_x_i, K_x_j chevron.r = ||sum_(i=1)^N c_i K_x_i||_hh >= 0. $
    Now assume that $c_1, ..., c_N in CC \ {0}, x_1, ..., x_N in X'$ with $sum_(i=1)^N sum_(j=1)^N c_i overline(c_j) K(x_j, x_i) = 0.$
    Then $sum_(i=1)^N c_i K_x_i = 0$ and $sum_(i=1)^n overline(c_i) delta_x_i (f) = sum_(i=1)^N overline(c_i) chevron.l f, K_x_i chevron.r _hh = 0.$
    Hence $delta_x_i, i=1,...,N$ is linearly dependent.
]

#note[
  $ |f(x)| = |chevron.l f, K_x chevron.r| <= ||K_x||_hh dot ||f||_hh $
  and
  $ ||k_x||_hh^2 = K(x,x)$, i.e. $|f(x)| <= (K(x,x))^(1/2) ||f||_hh$.
]

#remark[
  The function $K(x,x), x in X',$ is not necessarily bounded, hence $K(x,x)$ is not necessarily a function in $hh$.
]

#proposition[
  Let $hh$ be a RKHS with kernel $K$, $(f_n)_(n in NN) subset hh$ with $||f_n - f||_hh -> 0$ as $n ->oo$.
  Then
  1. $|f_n (x) - f(x)| -->_(n->oo) 0 quad forall x in X'$,
  2. $sup_(x in M) |f_n (x) - f(x)| -->_(n->oo) 0$ for every $M subset X'$ for which $sup_(x in M) K(x,x) < oo$.
]

#proof[
  Both 1. and 2. should be fairly clear.
]

== Subspaces
Assume $hh$ is RKHS, $tilde(hh) subset hh$ is a #underline[closed] subspace.
Then $delta_x: tilde(hh) -> CC$ is continuous on $tilde(hh)$.
Hence $tilde(hh)$ has a representing kernel $tilde(K)$.

#proposition[
  $hh$ RKHS, $tilde(hh) subset hh$ closed subspace with kernel $tilde(K)$.
  Then $ tilde(f) (x) := chevron.l f, tilde(K)_x chevron.r_hh, quad f in hh $
  is the projection of $f in hh$ onto $tilde(hh)$.
]

#proof[
  Since $tilde(hh) subset hh$ is closed, there is $tilde(hh)^perp subset hh, hh = tilde(hh) plus.o tilde(hh)^perp$.
  Then for $f in hh$, there are $tilde(f) in tilde(hh)$, $tilde(f)^perp in tilde(hh)^perp$ s.t. $f = tilde(f) + tilde(f)^perp$.
  Hence $ chevron.l  f, tilde(K)_x chevron.r_hh = chevron.l tilde(f), tilde(K)_x chevron.r_hh + underbrace(chevron.l tilde(f)^perp"," tilde(K)_x chevron.r_hh, 0) = tilde(f)(x). $
  Note: $tilde(hh)^perp$ is always closed.
]

Let $hh_0,hh_1$ be RKHSes with kernels $K_0,k_1$, respectively.
Consider $hh = hh_0 plus.o hh_1$.
Then $hh$ is a RKHS with kernel $K(x,x') = K_0 (x,x') + K_1 (x,x')$ (Exercise).

#note[
  Deciding whether a given function is positive definite is in general difficult.
  We need to decide, whether the matrix $ (K(x_i, x_j))_(i,j=1)^N $ is positive semi-definite for all $N in NN, x_1, ..., x_N in X'$.
  Kernel $K$ is positive semidefinite if and only if all of these matrices are positive semi-definite.
  The matrices are therefore #underline[robust] to perturbations.
  #figure(
    image("images/robust_matrix.jpeg", width: 70%),
    caption: [The matrices of the kernel are robust.]
  )
]

#note[
  Question: How to complete $H_k$ to a $hh$ s.t. $hh$ is a RKHS with kernel $K$?
]

== Completion
Let $H$ be a pre-Hilbert space with reproducing kernel $K$.
#note[
  If $(f_n)_(n in NN) subset H$ is a Cauchy sequence (CS), then $||f_n - f_m||_H -->_(n,m->oo) 0$, then $(f_n (x))_(n in NN) subset CC$ is a CS due to $|f_n (x) - f_m (x)| <= c_x ||f_n - f_m||_H$
  Then define $f(x) := lim_(n -> oo) f_n (x)$.
]
We define $ hh = {f in CC^X | exists (f_n)_(n in NN) subset H "CS" : f(x) = lim_(n->oo) f_n (x) }. $<eq:rkhs_completion>
$ (f_n)_(n in NN) subset H "is a CS with" lim_(n->oo) f_n (x) = 0 forall x in X', "then" lim_(n->oo) ||f_n||_hh = 0. $<eq:completion_requirement>

#theorem[
  Let $H$ be a pre-Hilbert space with reproducing kernel $K$.
  Then
  1. there is a RKHS completion of $H$ iff @eq:completion_requirement holds,
  2. the RKHS completion of $H$ is unique and given by $hh$ from @eq:rkhs_completion.
]

#proof[
  1. $==>$: Let $tilde(hh)$ be RKHS completion of $H$, $(f_n)_(n in NN) subset H$ CS with $f_n (x) -->_(n->oo) 0$.
    Then $(f_n)_(n in NN) subset tilde(hh)$ is a CS in $tilde(hh).$
    Hence there is $f in tilde(hh)$ s.t. $||f - f_n||_(tilde(hh)) -> 0$.
    Since $tilde(hh)$ is a RKHS, for every $x in X'$ we have $ |f(x)| = lim_(n->oo) |f(x) - f_n (x)| <=^("property of RKHS") x_x lim_(n->oo) ||f-f_n||_tilde(hh), $
    i.e. $f(x) = 0 quad forall x in X'$ and hence $||f||_tilde(hh) = 0.$

    $<==$: Assume @eq:completion_requirement. We show that $hh$ is a RKHS-completion.
    For $f in hh$ define $||f||_hh := lim_(n->oo) ||f_n||_hh$.
    #set enum(numbering: "(a)")
    + We need to show that $||f||_hh$ is well-defined. Suppose $(tilde(f)_n)_(n in NN) subset H$ different from $(f_n)_(n in NN)$ with $lim_(n->oo)f_n (x) = f(x) = lim_(n->oo) tilde(f)_n (x)$.
      Then $f_n (x) - tilde(f)_n (x) -->_(n->oo) 0 quad x in X'$.
      Applying @eq:completion_requirement: $| ||f_n||_H - ||tilde(f)||_H | <= ||f_n - tilde(f)_n||_H -->_(n->oo) 0$.
    + $||dot||_hh$ is a norm on $hh$. Clear.
    + $hh$ has an inner product.
      Polarization: $ chevron.l f,g chevron.r_hh = 1/2 ||f+g||_hh - 1/2 ||f-g||_hh + i/2 ||f+i g||_hh - i/2 ||f-i g||_hh. $
      Verification that this is indeed an inner product is straightforward.
    + $H$ is dense in $hh$.
      Let $f in hh, (f_n)_(n in NN) subset H$ with $f(x) = lim_(n->oo) f_n (x)$.
      Then $ lim_(n->oo) ||f-f_n||_hh = lim_(n->oo) lim_(m->oo) ||f_m - f_n||_H = 0. $
    + $hh$ is complete.
      Let $(f_n)_(n in NN) subset hh$ be a CS.
      By the previous point there is $(g_(n,k))_(k in NN) subset H$ with $f_n (x) - g_(n,k)(x) -->_(k->oo) 0, x in X'$ and $||f_n - g_(n,k)||_hh -->_(k->oo) 0$.
      Consider $( g_(n,n)(x) )_(n in NN) subset H$.
      This is a CS for every $x in X'$.
      Hence there is $lim_(n->oo) g_(n,n)(x) =: f(x)$ and $f in hh$.
      Same argument as in the previous point gives that $||f-g_(n,n)||_H -->_(n->oo) 0.$
      Then $||f_n - f||_hh <= ||f_n - g_(n,n)||_hh + ||g_(n,n) - f||_hh --> 0$
    + $hh$ is a RKHS.
      Take $f in hh$ and $(f_n)_(n in NN) subset H$ s.t. $f_n (x) -->_(n->oo) f(x), x in X'.$
      That means $||f_n||_H --> ||f||_hh$.
      Then $ |delta_x (f)| = |f(x)| = lim_(n->oo) |f_n (x)| <= c_x lim_(n->oo) ||f_n||_H = c_x ||f||_hh. $
      Hence $hh$ is a RKHS and, by uniqueness, the kernel is $K$.
  2. The RKHS-completion is unique. Exercise. (Assume that there exists a second one and show that it equals the original.)
]

== Construction of RKHS
The main actor for construction is the positive definite kernel.
#note[Question][
  Assume $K in CC^(X' times X')$ is positive definite.
  Is there a RKHS $hh_K$ related to $K$?
]
Let $K: X' times X' -> CC$ be positive definite.
Define $ H_K = "span"{sum_(n=1)^N a_n K(x_n, dot) | N in NN, a_1, ..., a_N in CC, x_1, ..., x_N in X'}. $
Thus, if $f,g in H_K$, then there are $a_1,...,a_N,b_1,...,b_M in CC, x_1,...,x_N,y_1,...,y_M in X'$ such that
$ f = sum_(n=1)^N a_n K(x_n, dot), quad g = sum_(n=1)^M b_m K(y_m, dot). $
Without loss of generality we can assume that $N = M$.
Define $ chevron.l f,g chevron.r_K := sum_(n=1)^N sum_(m=1)^M a_n overline(b_m) K(x_n, y_m). $
We need to show that this definition does not depend on the representation of the functions $f$ and $g$.
Since $ chevron.l f,g chevron.r_K = sum_(m=1)^N overline(b_m) f(y_m) = sum_(n=1)^N a_n g(x_n), $
we have $chevron.l dot, dot chevron.r$ is independent of the representations of $f$ and $g$.

#proposition[
  $chevron.l dot,dot chevron.r_K: H_K times H_K -> CC$ is a positive definite sesquilinear form.
]

#proof[
  - $chevron.l dot,dot chevron.r_K$ is linear in the first component. (#math.checkmark)
  - $chevron.l dot,dot chevron.r_K$ is anti-linear in the second argument. (#math.checkmark)
  - $chevron.l f,f chevron.r_K = sum_(n=1)^N sum_(m=1)^N a_n overline(a_m) K(x_n, x_m) >= 0.$ (#math.checkmark)
  - $chevron.l f,K_x chevron.r_K = sum_(n=1)^N a_n K(x_n, x) = f(x).$ (#math.checkmark)
  - $chevron.l f,f chevron.r_K = 0$ (Exercise).
]

That means that $(H_K, chevron.l dot, dot chevron.r_K)$ is a RK pre-HS.
In order to get to the RKHS-completion we check @eq:completion_requirement:
Let $(f_n)_(n in NN) subset H_K$ be a CS with $f_k (x) -->_(k->oo) 0$.
Then $ f_k (x) = sum_(k=1)^N_k a_(n,k) K(x_(n,k),x). $
and thus $ ||f_k||_K^2 = ... = sum_(n=1)^N_k a_(n,k) f_k (x_(n,k)) -->_(k->oo) 0. $
Hence the completion is $ hh_K = {f in CC^X' | exists (f_n)_(n in NN) subset H : lim_(n->oo) f_n (x) = f(x) quad forall x in X' }. $

#remark[
  Note that there is a 1 to 1 correspondence of RKHS and positive definite kernels.
]

#example[
  #set enum(numbering: "(a)")
  + $X' = RR, K: X' times X' -> RR, K(x,x') = x x' ==> sum_(i=1)^N sum_(j=1)^N c_i c_j x_i x_j = (sum_(i=1)^N c_i x_i)^2 >= 0. $\
    *Generalization*: Assume $X' != emptyset$ is a set, $H$ is a Hilbert spaec and $Phi: X' -> H$.
    Let $K: X' times X'->CC, K(x,x') = chevron.l Phi(x), Phi(x') chevron.r_H$.
    This is a positive definite kernel.
    This kernel generates a RKHS of functions defined on $X'$.
    The cool thing is that $X'$ can be anything, no structure is assumed (for example a graph).
    $Phi$ is sometimes called the feature map.
    #figure(
      image("images/rkhs_classification.png", width: 70%)
    )
  + Let $(X', d)$ be a compact metric space and $mu$ a probability measure on $X'$.
    Assume we are given an orthonormal system of functions ${phi_k | k in NN}$, that is $ integral_X' f_j (x) overline(f_k) (x) dif mu(x) = delta_(j,k). $
    We can define a positive definite kernel by $ K(x,y) = sum_(n=1)^oo w_k overline(phi_k) (x) phi_k (y), $
    where $(w_k)_(n in NN) subset RR$ with
    + $forall k in NN: w_k >= 0,$
    + $forall x,y in X': |sum_(k=1)^oo w_k overline(phi_k)(x) phi_k (y)| < oo.$
    In particular we might consider $X' = [-1,1], d(x,y) = |x-y|$.
    On this space we can for example have the system of orthonormal polynomials, Jacobi polynomials, or Chebyshev polynomials.
]

#text(size: 20pt, fill: red, weight: "bold")[A week of material was skipped here.]

#proposition[
  Let $(X', aa)$ be a measurable space, $K$ reproducing kernel for RKHS $hh_K$.
  Then every $f in hh_K$ is measurable iff $K(dot, y): X' -> RR$ is measurable for all $y in X'$.
]
#proof[\
  $==>$: #sym.checkmark\
  $<==$: Assume $K(dot, y): X' -> RR$ is measurable.
  Then every $f in H_K$ is measurable.
  For $f in hh_K$ ther is $(f_n)_(n>=1) s.t. ||f-f_n||_K -->_(n->oo) 0$.
  In particular, $f_n (x) -> f(x)$ for all $x in X'$.
  Pointwise limits of measurable functions are measurable.
]

#theorem[
  Let $(X', aa)$ be a mesaruable space, $mu$ a $sigma$-finite measure on $X'$, $hh_K$ a RKHS with kernel $K: X' times X' -> RR$.
  Let $ |K|_p := (integral_(X') |K(x,x)|^(p/2) dif mu(x))^(1/p), quad 1 <= p < oo. $
  Then
  + every $f in hh_k$ is $p$-integrable,
  + the embedding
    $ L: (hh_K, ||dot||_K) -> (L^p (X', mu), ||dot||_p), quad L(f) = f $<eq:embedding>
    is continuous with $||L|| <= |K|_p,$
  + if $1/p + 1/p' = 1$, then
    $ L^*: (L^p' (X', mu), ||dot||_(p')) -> (hh_K, ||dot||), quad (L^*g)(x) = integral_(X') g(y) K(x,y) dif mu(y) $<eq:adjoint>
    is the adjoint of $L$,
  + $hh_K$ is dense in $L^p (X', mu)$ iff $L^*$ is injective,
  + $rr(L^*)$ is dense in $hh_K$ iff $L$ is injective.
]

#proof[
  + For $f in hh_K$ we have $|f(x)| &= |chevron.l f, K_X' chevron.r_K| <= ||f||_K dot ||K_X'||_K.$
    $ integral_X' |f(x)|^p dif mu(x) &= integral_X' |chevron.l f, K_X' chevron.r_K|^p dif mu(x) <= underbrace(||f||_K^p integral_X' ||K_x||_K^p dif mu(x), integral_X' |K(x,x)|^p dif mu(x)) $
  + The above also shows this point.
  + Let $p,p' in [1,oo)$ and $1/p + 1/p' = 1$.
    Then
    $ integral_(X') |g(y)| dot |K(x,y)| dif mu(y) &<= sqrt(K(x,x)) integral_X' sqrt(K(y,y)) |g(y)| dif mu(y)\
                                                  &<= sqrt(K(x,x)) dot |K|_p dot ||g||_p' $
    Hence $X' in.rev y |-> g(y) K(dot, y)$ is integrable for every $x in X'$ and $L^* g$ is well defined.
    This shows that $g(y)K(dot,y)$ is #link("https://en.wikipedia.org/wiki/Bochner_integral")[Bochner integrable] and 
    $ tilde(g) = integral_(X') g(y) K(dot, y) dif mu(y) in hh_K. $
    Consider $delta_x in hh'_K.$
    Then for every $x in X':$
    $ tilde(g)(x) &= delta_x (tilde(g))
                   = delta_x (integral_X' g(y) K(dot, y) dif mu(y))
                   = integral_X' g_9y) delta_x (K(dot, y)) dif mu(y) \
                  &= integral_X' g(y) K(x, y) dif mu(y)
                   = (L^* g)(x). $
    It remains to show that $L^*$ is the adjoint of $L$.
    #v(0.5em)
    #box(stroke: black, radius: 5pt, width: 25%, outset: 10pt)[$ A&: V -> W "linear"\ A^*&: W^* -> V^*\ &(A^* phi) (v) := phi(A v)$]
    #v(0.5em)
    To show $(L^* phi.alt)(f) = phi(L f)$ for $phi.alt in (L^p (X', mu))' tilde.eq L^p' (X', mu)$ for $p,p' in [1,oo)$ s.t. $1/p + 1/p' =1.$
    There is $g in L^p' (X', mu)$ s.t. $ phi.alt(f) = integral_X' f(x) g(x) dif mu(x).$
    $ phi.alt (L f) &= integral_X' g(y) (L f) (y) dif mu(y) = integral_X' g(y) f(y) dif mu(y)\
                    &= integral_X' overline(g)(y) chevron.l f, K_y chevron.r_K dif mu(y) = chevron.l f, integral_X' g(y) K(dot, y) dif mu(y) chevron.r_K, $
    where we were able to interchange $integral_X'$ and $chevron.l dot, dot chevron.r$ by continuity.
  + Follows from:\
    If $A in B(E,F)$, $E,F$ Banach spaces.
    Then $ "Ker"(A^*) = rr(A)^perp, quad "Ker"(A) = rr(A^*)^perp. $
  + Same as the previous point.
]

#theorem[
  Let $(X', aa)$ be a measurable space, $mu$ a $sigma$-finite measure on $X'$, and $hh_K$ separable RKHS with measurable kernel $K$, $|K|_2 < oo$.
  Then $ S_K: L^2 (X', mu) -> hh_K, quad S_K g(x) = integral_X' g(y) K(x, y) dif mu(y) $
  is a #link("https://en.wikipedia.org/wiki/Hilbert%E2%80%93Schmidt_operator")[Hilbert-Schmidt operator] #footnote[HS operators are similar to matrices in some sense.].
  Furthermore, $ T_K: L^2 (X', mu) -> L^2 (X', mu), quad T_K = S_K^* S_K $ is compact, positive, self-adjoint, and nuclear with
  $ ||T_K||_N = ||S_K||_("HS") = |K|_2. $
]

#proof[
  $S^*_K: hh_K -> L^2 (X', mu).$ Let ${v_n | n in NN}$ be an orthonormal basis for $hh_K$.
  Then $ sum_(n in NN) ||S_K^* v_n||_2^2 &= sum_(n in NN) integral_X' |S_K^* v_n (x)|^2 dif mu(x) = integral_X' sum_(n in NN) |S_K^* v_n (x)|^2 dif mu(x)\
                                         &= integral_X' sum_(n in NN)|v_n (x)|^2 dif mu(x). #footnote[Note: $S_K^*$ is the embedding.] $
  Write $ K(x, y) = sum_(n in NN) chevron.l K_x, v_n chevron.r v_n (y) = sum_(n in NN) overline(v_n (x)) v_n (y).$
  In particular, $ K(x, x) = sum_(n in NN) |v_n (x)|^2. $
  Then
  $ sum_(n in NN) ||S_K v_n||^2_2 = integral_(X') K(x,x) dif mu(x) < oo $
  due to the assumption that $|K|_2 < oo$.
  Hence $S_K^*$ is a Hilbert-Schmidt operator, and ,in particular, is compact.
  According to Theorem of Schauder: $S_K = (S_K^*)^*$ is compact.
  Since the class of compact operators forms an ideal in the space of operators, we know that $T_K = S_K^* S_K$ is also compact.
  Further, we have $T_K^* = S_K^* S_K = T_K$, i.e. $T_K$ is self-adjoint.
  $ chevron.l T_K g, g chevron.r = chevron.l S_K^* S_K g, g chevron.r = chevron.l S_K g, S_K g chevron.r = ||S_K g||_2^2 >= 0, $
  hence $T_K$ is positive.
  $ integral_X' integral_X' |K(x,y)|^2 dif mu(x) dif mu(y) <= (integral_X' K(x,x) dif mu(x))^(1/2) (integral_X' K(y,y) dif mu(y))^(1/2). $
  Therefore $K(dot, dot) in L^2 (X' times X', mu times mu)$ and we have the norm
  $ ||S_K||_("HS") = (integral_(X' times X') |K(x,y)|^2 dif (mu times mu) (x,y) )^(1/2) = ||K||_(L^2 (X' times X' , mu times mu)) $
  Let ${e_j : j in NN}$ be an orthonormal basis of $L^2 (X', mu)$.
  Then $ ||S_K||_("HS") = sum_(j in NN) ||S_K e_j||_K^2 = sum_(j in NN) chevron.l S_K e_j, S_K e_j chevron.r_K = sum_(j in NN) chevron.l T_K e_j, e_j chevron.r = tr(T_K) = ||T_K||_N $
]
It holds that $hh_K arrow.hook L^p (X', mu)$ for $1 <= p < oo$.

Let $X'$ be a topological space with topology $tau$.
#note[Question][
  Under what condition on $K$ do we have that $hh_K subset C(X')$?
]

We consider kernels with a special property:
#definition[Separately continuous kernel][
  Let $K: X' times X' -> CC$ be a positive definite kernel.
  $K$ is called separately continuous if $K_x = K(dot, x) in C(X')$ for every $x in X'$.
]
#note[Separate continuity does not imply continuity of $K: X' times X' -> CC$.]


#proposition[
  Let $(X', tau)$ be a topological space, $hh_K$ a RKHS with kernel K.
  Then
  + $K$ is bounded and separately continuous $<==>$ every $f in hh_K$ is bounded and continuous,
  + the embedding $ L: (hh_K, ||dot||_K) -> (C_b (X'), ||dot||_n) $ is continuous and $||iota|| = |K|_oo $
]

#proof[
  + Assume that $K_x in C(X')$ for all $x in X'.$#footnote[It may or may not also be necessary to assume $K in C(X' times X')$.]
    For $f in hh_K$ there is $(f_n)_(n in NN) subset H_K$ with $||f - f_n||_K -->_(n->oo) 0.$
    Then $|f(x) - f_n (x)| <= ||K_x|| ||f-f_n||_K$ for every $x in X'.$
    Hence $f in C_b (X').$
    Now let $hh_K subset C_b (X').$
    Then $K_x in C_b (X')$ for every $x in X'.$
    Now the boundedness of $K$ follows from Prop 4.9 (i) (in the missing part of the notes).
  + Follows from Prop 4.9 (ii).

]

=== The Feature Map
Let $X' != emptyset$ be a set, $H$ a Hilbert space, $Phi: X' -> H$ (Example 4.9).
$ K(x,y) = chevron.l Phi(x), Phi(y) chevron.r_H $<eq:Phi_kernel> is a positive definite kernel on $X'.$
$Phi$ is called a _feature map_ and $H$ is called _feature space_.

#note[
  Every positive definite kernel can be written in the form of @eq:Phi_kernel.
  To see this, take $H = hh_K$ and $Phi_K: X' -> hh_K$.
]

The feature map establishes a pseudo-metric on $X'$:
$ d_Phi (x,y) = ||Phi(x) - Phi(y)||_H. $
$d_Phi$ is note necessarily a metric, since it could be that $d_Phi (x,y) = 0$ for some $x != y$.
If we additionally assume that $Phi$ is injective, however, then $d_Phi$ is a metric and $(X', d_Phi)$ is a metric space.
The feature map $Phi$ is a Lispchitz continuous function.

*Motivation*: $X' = [0,1] times [0,1]$
#figure(
  image("images/kernel_trick_motivation.jpeg", width: 60%),
  caption: [Kernel trick motivation.]
)

#proposition[
  Let $(X', tau)$ be a topological space, $Phi: X' -> H$ an injective feature map, and $K(x, y) = chevron.l Phi(x), Phi(y) chevron.r_H.$
  The following are eqivalent:
  + $K: X' times X' -> CC$ is continuous w.r.t. $tau.$
  + $K$ is separately continuous and $X' in.rev x |-> K(x, x) in CC$ is continuous w.r.t. $tau.$
  + $Phi$ is continuous w.r.t. $tau.$
  + $iota: (X', tau) -> (X', d_Phi)$, $iota(x) = x$ is continuous.
]<prop>
#proof[
  1.$=>$2. is obvious.
  
  3.$=>$4. $d_Phi (dot, y): (X', tau) -> (X', d_Phi)$ is continuous w.r.t. $tau$, since $Phi$ is continuous.
    The set ${x in X' | d_Phi (x, y) < epsilon}$ is open w.r.t. $tau.$
    This implies that $iota$ is continuous.

  4.$=>$3. Let $x, y in X'$. Then $||Phi(x) - Phi(y)||_H = d_Phi (x, y) = d_Phi (iota(x), iota(y)).$
    Therefore, because $iota$ is continuous, so is $Phi$.
  3.$=>$1. Let $x, y, x', y' in X'$.
    Then
    $ |K(x,y) - K(x',y')| &<= |chevron.l Phi(x), Phi(y) - Phi(y') chevron.r - chevron.l Phi(x) - Phi(x'), Phi(y) chevron.r|\
    &<= ||Phi(x)||_H ||Phi(y) - Phi(y')||_H + ||Phi(y)||_H ||Phi(x) - Phi(x')||_H. $
    This shows the statement.
]

#remark[
  So as to not overfit, we introduce regularization terms. One potential regularization is:
  $ rr_(L,P) (f) = integral L(x, y, f(x)) dif P(x, y) + underbrace(lambda ||f||_K + lambda ||f'||_K, "regularization term"). $
]

#proposition[
  Let $X' != emptyset$, $hh_K$ be a RKHS with kernel $K$, and canonical feature map $Phi_K: X' -> hh_K.$
  If $Phi_K (X') subset hh_K$ is compact, then $iota: hh_K -> L^oo (X')$ is compact.
]
#proof[
  $Phi_K (X') subset hh_K$ is a compact subset of a metric space.
  In particular, $Phi_K (X')$ is bounded.
  Then $ K(x,x) = |chevron.l Phi_K (x), Phi_K (x) chevron.r| <= ||Phi (x)||_K $
  Hence, $K(x,x), x in X'$ is bounded.
  Further, $(X', d_(Phi_K))$ is a compact metric space (since $Phi_K (X')$ is compact, and $Phi_K: (X', d_Phi) -> (hh_K, ||dot||_K)$ is continuous).
  Consider $C(X', RR) := C((X', d_(Phi_K)), RR).$
  Clearly, $C(X', RR) subset L^oo (X')$ because $(X', d_Phi_K)$ is compact and continuous functions on a compact set are bounded.
  For $x, y in X', f in hh_K$ we have $ |f(x) - f(y)| = |chevron.l f, Phi(x) - Phi(y) chevron.r| <= ||f||_K ||Phi(x) - Phi(y)||_K = ||f||_K d_Phi_K (x,y) $
  Hence, $f$ is Lipschitz continuous on $(X', d_Phi_K).$
  Consider $B_1 = {f in hh_K | ||f||_K <= 1}.$
  $B_1$ is uniformly equi-continuous and is bounded w.r.t. $||dot||_oo.$
  Now apply theorem of Arzela-Ascoli to find that $overline(B)_1 subset C(X', RR)$ is compact.
  This shows that $iota$ is compact.
]

#proposition[
  Let $(X', tau)$ be a separable topological space and $K in C(X' times X').$
  Then $hh_K$ is separable.
]
#proof[
  By Proposition 4.14 $K in C(X' times X')$ implies $Phi_K: X' -> hh_K, Phi_K (x) = K(dot, x).$
  Hence $Phi_K (X')$ is separable in $H_K.$
  This implies that $hh_K$ is separable.
]

#remark[
  If $(X', tau)$ is separable, and $K in C(X' times X')$, then there is a ONB ${e_n, n in NN}$ for $hh_K.$
  In particular $ Phi(x) = K(dot, x) = sum_(n=1)^oo chevron.l K(dot, x), e_n chevron.r e_n = sum_(n=1)^oo overline(e_n (x)) e_n. $
  The convergence of this series is uniform on every compact subset $cal(U) subset X'.$
]

#definition[
  Let $(X', d)$ be a compact metric space.
  A positive definite kernel $K in C(X' times X')$ is called universal if $hh_K$ is dense in $(C(X'), ||dot||_oo).$
  A kernel separates  disjoint subsets $A, B in X'$ if there is $a in RR$ and $f in hh_K$ with $f(x) > a med forall x in A$ and $f(x) < a med forall x in B$
  A kernel separates finite resp. compact subsets if it holds for $A,B$ finite or compactact.
]

#proposition[
  Let $(X', d)$ be a metric space, $K$ a universal kernel.
  Then $K$ separates compact subsets.
]
#proof[
  $A,B in X'$ be compact and $A inter B = emptyset.$
  For $x in X'$ define $ g(x) = (dist(x, B) - dist(x, A)) / (dist(x, B) + dist(x, A)), $
  where $dist(x, M) = inf_(y in M) d(x,y).$
  The $X' in.rev x |-> dist(x, M) subset RR_+$ is continuous, hence $g$ is continuous.
  Moreover $g(x) = 1 med forall x in A$, and $g(x) = -1 med forall x in B.$
  Since $K$ is universal, there is $f in hh_K$ s.t. $||f-g||_oo < -1/2.$
  Thus $f(x) > 1/2 med forall x in A$, and $f(x) < 1/2 med forall x in B.$
]

#remark[
  + The complexity of $hh_K subset C(X')$ affects the approximation properties.
    ...
    If $hh_K$ is dense in $C(X')$, then $hh_K$ contains functions of high complexity.
    Then an overfitting of data by $inf_(f in hh_K) cal(R)_(L,P)(f)$ is very likely)
    On the other hand, if $hh_K$ is too small, then $inf_(f in hh_K) cal(R)_(L,P)(f)$ will give functions which are too smooth.
  + Now assume that $K$ is universal and defined by a feature map $Phi: X' -> H.$
    Let ${x_1, ..., x_N} subset X'$ and $y_1, ..., y_N in {-1, 1}.$
    By universality, there is an $f in hh_K$ s.t. $y_i f(x_i) > 0 med forall i=1,...,N.$
    For every $f in hh_K$ there exists a $w in H$ s.t. $f(x) = chevron.l Phi(x), w chevron.r_H.$
    #proof[
      For every $f in hh_K$ there are $a_1, ..., a_M in CC$ and $y_1, ..., y_M in X'$ s.t.
      $ f &= sum_(m=1)^M overline(a)_m K(dot, y_m), med x in X' = sum_(m=1)^M overline(a)_m chevron.l Phi(x), Phi(y_m) chevron.r_H = chevron.l Phi(x), underbrace(sum_(m=1)^M a_m Phi(y_m), w) chevron.r. $
      Since the inner product is continuous this also holds for $hh_K.$
    ]
    This shows that every set ${(Phi(x_1), y_1), ..., (Phi(x_N),y_N)}$ can be separated by hyperplane defined by $w$
    into subsets $ {(Phi(x_l), 1) | x_l in X'} quad "and" quad {(Phi(x_l), -1) | x_l in X'}. $
]

=== Properties of universal kernels
#proposition[
  Let $(X', d)$ be a compact metric space and $K$ universal positive definite kernel on $X'$.
  Then
  + every feature map $Phi: X' -> H$ for which $K(x, y) = chevron.l Phi(x), Phi(y) chevron.r_H$ is injective,
  + $K(x, x) > 0$ for every $x in X',$
  + if $X'' subset X'$, then $K | X'' times X'$ is universal on $X'',$
  + the kernel $ K^*: X' times X' -> CC, med K^* (x,y) = (K(x,y))/((K(x,x)K(y,y))^(1/2)) $ is universal.
]
#proof[
  + Let $Phi: X' -> H$ be a feature map with $K(x,y) = chevron.l Phi(x), Phi(y) chevron.r_H$.
    Take $x_0, x_1 in X', x_0 != x_1$ and assume $Phi(x_0) = Phi(x_1).$
    Since $K$ is universal, there is an $f in hh_K$ s.t. $f(x_0)<0, med f(x_1)>0$. 
    Since $f(x) = chevron.l Phi(x), w chevron.r_H$ with $w in H.$
    $ f(x_0) = chevron.l Phi(x_0), w chevron.r_H = chevron.l Phi(x_1), w chevron.r = f(x_1).$
    Thus $x_0 = x_1$, and therefore $Phi$ is injective.
  + $K(x,x) = ||Phi(x)||_H^2 >= 0$.
    If $K(x,x) = 0$, then $Phi(x) = 0.$
    There is $f in hh_K$ with $f(x) = chevron.l Phi(x), w chevron.r_H, med w in H$, with $f(x) > 0.$ 
    Hence $K(x,x) = 0$ is impossible.
  + #math.checkmark
  + According to 2.: $K(x,x) > 0 med forall x in X'.$
    Hence $K^*$ is well-defined.
    Define $alpha(x) := (K(x,x))^(-1/2).$
    If $Phi_K$ is the canonical feature map for $K$, then $alpha Phi$ is then a feature map for $K^*$ since
    $ K^* (x,y) = chevron.l (alpha Phi)(x), (alpha Phi)(y) chevron.r_H = alpha(x) alpha(y) chevron.l Phi(x), Phi(y) chevron.r_H. $
    Now let $g in C(X'), med epsilon > 0$.
    $c = ||alpha||_oo < oo.$
    Since $K$ is universal, we find $f in hh_K$ with $||f - alpha^(-1) g||_oo < epsilon / c.$
    Then $||chevron.l f, alpha(dot) Phi(dot) chevron.r - g||_oo <= ||alpha||_oo ||f-alpha^(-1) g||_oo < epsilon.$
]


#proposition[
  Let $(X', d)$ be a compact metric space, $K$ a positive definite kernel with $K(x,x) > 0 med forall x in X'.$
  Suppose that $Phi: X' -> cal(l)^2 (NN), med Phi(x) = (Phi_n (x))_(n in NN)$ is an injective feature map with $K(x,y) = chevron.l Phi(x), Phi(y) chevron.r_(cal(l)^2 (NN)).$
  If $cal(A) = "span"(Phi_n, n in NN)$ is an algebra, then $K$ is univiersal.
]
#proof[
  Since $0 < K(x,x) = ||Phi(x)||_(cal(l)^2),$ ${0} subset.neq aa,$ $Phi$ is continuous by Proposition ?4.14 (probably like 4.12)?.
  Hence $Phi_n subset C(X')$ and therefore $cal(A) subset C(X').$
  $cal(A)$ is an algebra w.r.t. pointwise multiplication.
  Now let $x, y in X', x != y$, then $Phi(x) != Phi(y).$
  Thus $aa$ separate points in $X'$.
  By the Theorem of Stone-Weierstrass we have $ "cl"_(||dot||_oo) aa = C(X'). $
  Take $g in C(X')$ then there is $f in aa$ s.t. $f = sum_(j=1)^J alpha_n_j Phi_n_j$ s.t. $||f - g||_oo < epsilon.$
  Define $w_n = alpha_n_j$ if $n = n_j$ and $w_n$ = 0 otherwise.
  Then for $w = (w_n)_(n in NN) in cal(l)^2 (NN)$ and $ f(x) = chevron.l Phi(x), w chevron.r_(cal(l)^2)$ approximates $g$ arbitrarily well.
  Hence $K$ is universal.
]

#example[
  #set enum(numbering: "(a)")
  + $DD = {z in CC | |z| < 1}.$
    Let $r > 0$ and $F: r DD -> CC$ be a holomorphic function with $F(z) = sum_(n=0)^oo a_n z^n$ (Taylor series).
    Define $K(z,xi) = F(z dot xi) = sum_(n=0)^oo a_n (z dot xi)^n$ with $z, xi in sqrt(r) DD.$
    Then $K$ is a positive definite kernel on $sqrt(r) DD^d$.
    $ K(z, xi) = sum_(n=1)^N a_n (sum_(j=1)^d z_j xi_j)^n = dots = sum_(xi_1, ..., xi_d) a_(xi_1 + ... + xi_d) c_(xi_1 + ... + xi_d) (product_(i=1)^d z_i^(j_i)) (product_(i=1)^d overline(xi)_i^(j_i)). $
    Then from this $Phi: sqrt(r) DD^d -> cal(l)^2 (NN_0^d)$
    $ Phi(z) = ( (a_(j_1+...+j_d) c_(j_1,...,j_d))^(1/2) product_(i=1)^d overline(xi)_i^(j_i))_(j_1, ..., j_d >= 0,\ j_1 + ... + j_d = n) $
    If $a_n > 0$ for all $n in NN_0$, then $K(x,x) > 0 med forall x in X'.$
    $ Phi: X' -> cal(l)^2 (NN_0^d)$ is injective since $Phi_(j_1, ..., j_d)$ is polynomial.
    Applying Proposition 4.18 shows $K$ is universal.
  + Use (a) to see that
    + Exponential kernel $ K(x,y) = exp(x dot y), quad x, y in X', $
    + Gaussian kernel $ K_sigma (x,y) = exp( - (|x-y|^2)/sigma^2 ), quad x,y in X', sigma in RR, $
    + Binomial kernel $ K_alpha (x,y) = (1 - x dot y)^(-alpha), quad x,y in X', alpha > 0 $
    are all universal.
  + Let $TT^d = {z in CC^d | |z|_2 = 1} tilde.equiv RR^d / (2 pi ZZ)^d.$
    $ e_k (x) = e^(i k x) = z^k, med z^k = z_1^k_1 dot ... dot z_d^k_d dot ... dot z_d^k_d quad quad(z = e^(i x)). $
    Then ${e_k | k in ZZ^d}$ is an orthonormal basis of $L^2 (pi^d).$
    For $w = (w_k)_(k in ZZ^d)$ with $w_k >= 0$ define $ F(z) = sum_(k in ZZ^d) w_k z^k.$
    We see $ sum_(n=0)^N sum_(m=0)^N c_n overline(c)_m F(z_n dot z_m^(-1)) >= 0 $
    for $N in NN, c_1,...,c_N in CC, z_1,...,z_N in pi^d.$
    Now $Phi(z) = (Phi_k (z))_(k in ZZ^d), med Phi_k (z) = w_k^(1/2) z^k.$ 
    This defines a feature map $Phi: pi^d ->  cal(l)^2 (NN_0^d)$ s.t. $K(z,xi) <= chevron.l Phi(z), Phi(xi) chevron.r_(cal(l)^2 (NN_0^d)).$
    In harmonic analysis it is shown that $aa = "span"{Phi_k | k in ZZ^d}$ (space of trigonometric polynomials) is dense in $C(pi^d).$
    Hence $K$ is universal.
]

== Mercer Kernels
Let $(X', d)$ be a compact metric space and $mu$ a finite Borel measure with support $X'$.
Let $K: X' times X' -> CC$ be a positive definite kernel with $|K|_2 < oo$ and let $hh_K$ be the corresponding RKHS. 
By Theorem 4.12:
$ T_K: L^2 (mu) -> L^2 (mu), quad T_k = S_K^*S_K $
where $ S_K: L^2 (mu) -> hh_K, quad S_K g(x) = integral_X' g(y) K(x,y) dif mu(y). $
Then $T_K$ is compact, self-adjoint, and positive definite and $"spec"(T_K) = {0,lambda_1,lambda_2,...}$ with $lambda_1 >= lambda_2 >= dots >= lambda_j -->_(j->oo) 0.$
// #figure(
//   image("images/spectrum.jpeg", width: 70%),
//   caption: [The spectrum of $T_K$.]
// )
Then there is an ONB ${phi_j, j in NN}$ with $ T_K phi_j = lambda_j phi_j " for " j in NN, $
and $ T_K = sum_(j=1)^oo lambda_j chevron.l dot, phi_j chevron.r phi_j quad "(spectral decomposition)". $
Every $g in L^2 (mu)$ can be decomposed as $ g = g_0 + sum_(j=1)^oo chevron.l g, phi_j chevron.r phi_j, $
where $g_0 in "ker"(T_K).$
Define $psi_j := 1/lambda_j S_K phi_j$ for $j = 1,2, dots.$
Then $psi_j in hh_K$, and since $S_K^*$ is the embedding, we have $ phi_j = 1/lambda_j T_K phi_j = 1/lambda_j S_K^* S_K phi_j = 1/lambda_j S_K phi_j = psi_j. $
Hence $phi_j = psi_j$ $mu$-almost everywhere, and in particular, $phi_j in hh_K$ and
$ lambda_j lambda_k chevron.l phi_j, phi_k chevron.r_hh_K = chevron.l S_K phi_j, S_K phi_j chevron.r_hh_K = chevron.l phi_j, T_K phi_k chevron.r_(L^2 (mu)) = lambda_k chevron.l phi_j, phi_k chevron.r = lambda_k delta_(j,k). $
Therefore, ${lambda_j^(1/2) phi_j, j in NN$ is an orthonormal system for $hh_K$.

#theorem[Mercer][
  Let $(X', d)$ be a compact metric space, $mu$ a finite Borel measure with $"supp"(mu) = X'$.
  Let $A in C(X' times X')$ with $A(x,y) = overline(A(y,x)).$
  Then
  + $aa: L^2 (mu) -> L^2 (mu), med aa f(x) = integral_X' f(y) A(x,y) dif mu (y)$ is compact and self-adjoint,
  + we have $A(x,y) = sum_(j=1)^oo lambda_j phi_j (x) overline(phi)_j (y)$<eq:definitioni_of_aa>
    The convergence in @eq:definitioni_of_aa is absolute and uniform, provided that $"spec"(aa) minus {0} subset RR_(>0).$ 
]<thm:mercer>
#proof[
  + Let $A in C(X' times X')$, and $X'$ is compact.
    Hence $A in L^2 (mu times mu).$
    Then $aa$ is a Hilbert-Schmidt operator in part. compact.
    Since $A(x,y) = overline(A(y,x))$, it follows that $aa$ is self-adjoint.
    Hence $"spec"(aa) = {0, lambda_1, lambda_2, ...}l$
    There is $phi_j in L^2 (mu)$ s.t. $aa phi_j = lambda_j phi_j$ for $j=1,2,....$
    By the spectral decomposition of $aa$: $ aa = sum_(j=1)^oo lambda_j chevron.l dot, phi_j chevron.r phi_j. $
  + The systemk ${phi.alt_j (x, y) = phi_j (x) overline(phi_j (y))$ is an orthonormal system in $L^2 (X' times X', mu times mu).$
    $ sum_(j=1)^oo chevron.l A, phi.alt_j chevron.r_(L^2 (mu times mu)) phi.alt_j (x,y) $
    This converges in $L^2 (X', times X', mu times mu)$ (due to Bessel inequality)
    to a $G in L^2 (X' times X', mu times mu)$:
    $ chevron.l A, phi.alt_j chevron.r_(L^2 (mu times mu)) = integral_X' integral_X' A(x,y) phi_j (x) overline(phi_j (y)) dif mu(x) dif mu(y) = chevron.l aa phi_j, phi_j chevron.r_(L^2 (mu)) = lambda_j. $
    Consequently, $G(x,y) = sum_(j=1)^oo lambda_j phi_j (x) overline (phi_j (y).$
    For $f, g, L^2 (mu)$ let $F(x,y) = g(x) overline(f(y)).$
    Now $g = g_0 + sum_(j=1)^oo chevron.l g, phi_j chevron.r phi_j,$ then $chevron.l aa f, g chevron.r_(L^2 (mu)) = sum_(j=1)^oo lambda_j chevron.l f, phi_j chevron.r chevron.l phi_j, g chevron.r.$
    Therefore, $ chevron.l A, F chevron.r_(L^2 (mu times mu)) = chevron.l A f, g chevron.r_(L^2 (mu)) = sum_(j=1)^oo lambda_j chevron.l phi.alt_j, F chevron.r. $

    We see $chevron.l A - G, F chevron.r_(L^2 (mu times mu)) = 0.$
    Since ${f = g times.o overline(f) | f,g in L^2 (mu)}$ is dense in $L^2 (mu times mu).$
    Thus, $A(x,y) = G(x,y)$ for $mu times mu$-almost all $(x,y) in X' times X'.$
    In particular, $A(x,y) = sum_(j=1)^oo lambda_j phi_j (x) overline(phi_j) (y) $ almost everywhere.
    It remains to show that the series in @eq:definitioni_of_aa converges absolutely and uniformly if $lambda_j > 0.$
    Since $A in C(X' times X')$, we have $aa f in C(X')$ for every $f in C(X')$.
    In particular, $phi_j in C(X').$
    For $n in NN$,
    $ A_n (x, y) = A(x,y) - sum_(j=1)^n lambda_j phi_j (x) overline(phi_j (y)).$
    Then $ A_n in C(X' times X'). $ 
    $ integral_X' integral_X' A_n (x,y) f(x) overline(f(y)) dif mu(x) dif mu(y) = .... = sum_(j=n+1)^oo lambda_j chevron.l phi_j, f chevron.r chevron.l f, phi_j chevron.r >= 0. $
    Hence $A_n (x,x) >= 0 med forall x in X'.$
    We have $ sum_(j=1)^oo lambda_j |phi_j (x)|^2 <= A(x,x), $
    further, $ |sum_(j=1)^oo lambda_j phi_j (x) overline(phi_j (y))| <= (sum_j lambda_j |phi_j (x)|^2)^(1/2)(sum_j lambda_j |phi_j (y)|^2)^(1/2). $
    Hence $sum_j lambda_j phi_j (x) overline(phi_j (y))$ converges uniformly w.r.t all $x in X'.$
    It defines $B(x, dot) in C(X')$ for every $x in X'.$
    For $f in C(X')$ we have $ integral_X' B(x,y) f_(y) dif mu(y) = ... = aa f(x). $
    Thus $ integral_X' (B(x,y) - A(x,y))f(y) dif mu(y) = 0 $
    and $ B(x,y) = A(x,y)$ for almost all $y in X'.$
    By continuity of $A,B$ we have $A(x,y) = B(x,y)$ for all $x,y in X'.$
    Thus $ B(x,x) = A(x,x) = sum_(j=1)^oo lambda_j |phi_j (x)|^2. $
    Since the limit of $sum_(j=1)^n lambda_j |phi_j (x)|^2$ exists and is continuous.
    The theorem of Dini shows the uniform convergence of the series.
]

#box(stroke: 1pt, radius: 5pt, outset: 5pt)[
*Recap:*
$(X', d)$ a compact metric space, $mu$ a finite measure on $X'$ s.t. $"supp"(mu) = X'$, $A in C(X' times X'), A(x,y) = overline(A(y,x))$.
$ aa: L^2 (mu) --> L^2 (mu), quad aa f(x) = integral_X' f(y) A(x,y) dif mu(y) $
$aa$ compact and self-adjoint.
$ A(x,y) = sum_(j=1)^oo  lambda_j phi_j (x) overline(phi_j)(y), quad aa phi_j = lambda_j phi_j. $
The series converges absolutly and uniformly
$ "spec"(aa) without {0} subset RR_(>0) $
]

Apply @thm:mercer to RKHS theory. $ K in C(X' times X')$ positive definite.
The operator $T_K = S^*_K S_K$ has kernel $K$ (recall $S^*_K$ is the embedding operator).
Thus $T_K$ satisfies all conditions of @thm:mercer.
$ K(x,y) = sum_(j=1)^(oo) lambda_j phi_j (x) overline(phi_j) (y) $
converges uniformly and absolutely.
Now let $ H = {sum_(j=1)^(oo) a_j sqrt(lambda_j) phi_j | (a_j)_(j=1)^oo in cal(l)^2 (NN) }, $
and define an inner product on $H$: For $f, g in H$,
$ f = sum_(j=1)^(oo) a_j sqrt(lambda_j) phi_j, quad g = sum_(j=1)^(oo) b_j sqrt(lambda_j) phi_j, $
the inner product is
$ chevron.l f,g chevron.r_H = sum_(j=1)^(oo) a_j overline(b_j). $

Note that
$ |sum_(j=1)^(oo) a_j sqrt(lambda_j) phi_j (x) | <= underbrace((sum_(j=1)^(oo) |a_j|)^(1/2), ||(a_j)||_(cal(l)^2)) underbrace((sum_(j=1)^(oo) lambda_j |phi_j (x)|^2)^(1/2), "bounded by Th. 4.23") $
i.e. all objects are well-defined.

#note[
  Question: Do we have $H = hh_K$?
]

#proposition[
  Let $(X', d)$ a compact metric space, $mu$ a finite Borel measeure, $"supp"(mu) = X'$, $K in C(X' times X')$ is positive definite.
  Further, let ${phi_j | j in NN}, {lambda_j | j in NN}$defined by $T_K phi_j = lambda_j phi_j, j in NN.$
  Then
  + $H = hh_K$,
  + $T_K^(1/2): ker(T_K)^perp --> H$ is an isometric isomorphism.
]

#proof[
  + For $x in X'$ we have (from @thm:mercer) $ K(x, dot) = sum_(j=1)^(oo) sqrt(lambda_j) phi_j (x) sqrt(lambda_j) overline(phi_j). $
    Recall $ sum_(j=1)^(oo) |sqrt(lambda_j) phi_j (x)|^2 = sum_(j=1)^(oo) lambda_j |phi_j (x)|^2 < oo. $
    Let $ f = sum_(j=1)^(oo) a_j sqrt(lambda_j) phi_j, (a_j)_(j=1)^oo subset cal(l)^2 (NN), x in X'. $
    Then $chevron.l f, K(x, dot) chevron.r_H = ... = f(x). $
    Hence $K$ is the reproducing kernel for $H$, thus $H = hh_K.$
  + Since  $lambda_j > 0, j in NN$, we have $ T_K^(1/2) = sum_(j=1)^(oo) lambda_j^(1/2) chevron.l dot, phi_j chevron.r_(L^2 (mu)) phi_j. $
    Let $f in ker(T_K^(1/2))^perp$, then $(chevron.l f, phi_j chevron.r)_(j=1)^oo in cal(l)^2 (NN).$
    Thus $T_K^(1/2) in H$.
    Moreover, $ ||T_K^(1/2) f||_H^2 = sum_(j=1)^(oo) |chevron.l f,phi_j chevron.r|^2 = ||f||^2_(L^2(mu)). $
    Hence $T_K^(1/2)$ is an isometry.
    ...
    Take $(a_j)_j$ and define $g = sum_(j=1)^(oo) a_j phi_j in ker(T_K)^perp.$
    Apply $T_K^(1/2)$ to $g$:
    $ |T_K^(1/2) g(x)| <= ||(a_j)_j||_(cal(l)^2 (NN)) underbrace((sum_(j=1)^(oo) lambda_j |phi_j (x)|^2)^(1/2), "converges pointwise") $
]


#remark[
  + If $f in L^2 (mu)$ with $(lambda_j^(-1/2) chevron.l f,phi_j chevron.r_(L^2 (mu)) in cal(l)^2 (NN),$ then $sum_(j=1)^(oo) 1/sqrt(lambda_j) chevron.l f,phi_j chevron.r sqrt(lambda_j) phi_j in H.$
    Conversly, $f in H$, then $(lambda_j^(-1/2) chevron.l f, phi_j chevron.r_(L^2 (mu))) in cal(l)^2 (NN).$
    That means $ H = {f in L^2 (mu) : sum_(j=1)^(oo) 1/lambda_j |chevron.l f,phi_j chevron.r_(L^2 (mu))|^2 < oo}. $
    Thus, $H$ is a Sobolev-type space.
    If, in particular, $"spec"(T_K) without {0} = {lambda_1, ..., lambda_N},$ then $dim H = N$, i.e. $H$ contains only #link("https://en.wikipedia.org/wiki/Bandlimiting")[_band-limited functions_].
    That is $ H = "span"_CC {phi_j : 1 <= j <= N}. $
  + Consider Example 4.6 (b) again.
    ${phi_j | j in NN}$ an ONB of $L^2 (mu)$, $(w_j)_(j=1)^oo$ a sequence with $w_j >= 0 med forall j in NN$, and $sum_(j=1)^(oo) w_j |phi_j (x)|^2 < oo. $
    Then $ K(x,y) = sum_(j=1)^(oo) w_j phi_j (x) overline(phi_j) (y)$ is positive definite.
    We have $ S_K f(x) = integral_X' f(y) K(x,y) dif mu(y)$ and $T_K phi_j = w_j phi_j.$
    Consequently, $ H = {f in L^2 (mu) | sum_(j=1)^(oo) w_j^(-1) |chevron.l f,phi_j chevron.r|^2 < oo}. $
]

#example[
  + Let $X_' = TT^d tilde.equiv RR^d \/ 2 pi ZZ^d.$
    Let $K(x,y) = sum_(|k|<=N)^() w_k e^(i k (x-y))$, $k in ZZ^d$, $x in RR^d$, $w_k >= 0$, and $k dot x = k_1 x_1 + ... + k_d x_d.$
    Then $K$ is positive definite and $H = "span"_CC {e^(i k dot x) | |k| <= N}$ is the space of trigonometric polynomials of degree $<= N.$
  + Let $X'$ be a compact Riemannian manifold, $d: X' times X' ->[0,oo)$ be a Riemannian metric (geodesic distance on the manifold), and the Riemannian volume measure $mu$ (sort of a Lebesgue measure on the manifold).\
    #box()[ *Laplace-Beltrani operator*: $Delta_X' = 1/sqrt(det(g)) sum_(i=1)^(d) sum_(j=1)^(d) partial_j (sqrt(det(g)) g^(i j) partial i).$ ]\
    $g = (g_(i j))_(i,j=1)^d$, $g^(-1) = (g^(i j))_(i,j=1)^d$
    $g_(i,j) = chevron.l (partial_i)_X, (partial_j)_X chevron.r_X$
    The LBO is elliptic and essentially self-adjoint, compact.
    Consider $Delta_X' phi_j = lambda_j phi_j, med j in NN.$
    Define $ K(x,y) = sum_(j=1)^(oo) w_j phi_j (x) phi_j (y), $ $(w_j)_j$ as before.

    The prototype of $X'$ is $SS^d = {v in RR^(d+1) : |v|_2 = 1}.$
    Here $ rho(x,y) = arccos (x dot y), $
    and $ dif mu(x) = product_(k=1)^d sin^(k-1) theta_k d theta_k $
    #box(stroke: black, radius: 5pt, outset: 10pt)[
      *Polar Coordinates*:
      $ x_k = cases(product_(j=1)^d sin(theta_j)"," &k-1, cos(theta_(k-1)) product_(j=k)^d sin(theta_j)"," quad &2 <= k <= d, cos(theta_d)"," &k=d+1), $
      where $theta_1 in [-pi, pi], theta_2,...,theta_d in [0,pi].$
    ]
    #v(1em)
    #box(stroke: black, radius: 5pt, outset: 10pt)[
      Laplace operator in $RR^(d+1)$ in polar coordinates:
      $ Delta = 1/r^d partial_r (r^d partial_r) + 1/r^2 Delta_(SS^d), $
      where $Delta_(SS^d)$ is the #link("https://en.wikipedia.org/wiki/Laplace%E2%80%93Beltrami_operator")[Laplace-Beltrami] operator on $SS^d$:
      $ -Delta_(SS^d) gamma_k = k(k+d-1) gamma_k,med k in NN_0. $
      $gamma_k$ are the so-called spherical harmonics.
      The eigenspace $H_k$ w.r.t. $lambda_k = k(k+d-1)$ has dimension $ h_d (k) = (2k + d - 1) ((k+d-2)!)/(k!(d-1)!). $
      Moreover, $H_K perp H_k'$ for $k, k' in NN_0, k != k'$.
      An ONB in $H_k$ is given by ${gamma_(k,l) | l=1,...,h_d (k)},$
      therefore $H_k = "span"{gamma_(k,l) | l=1,...,h_d (k)}$
    ]
    #v(2em)
    #align(center)[
      #table(
        columns: (auto, auto),
        align: (center, left),
        stroke: (x,y) => (
          top: if (y > 0) {0.7pt} else {0pt},
        ),
        [$H_0$], [$gamma_(0,0)$],
        [$H_1$], [$gamma_(1,0), gamma_(1,1), ..., gamma_(1,h_d (1))$],
        [$dots.v$], [$dots.v$], 
        [$H_k$], [$gamma_(k,0), gamma_(k,1), ..., gamma_(k,h_d (k))$]
      )
    ]
    #v(1em)
    We have $ "cl"_(||dot||_2) plus.o_(k>=0) H_k = L^2 (SS^d). $
    Define $ K(x,y) = sum_(k=0)^(oo) sum_(l=1)^(h_d (k)) w_(k,l) gamma_(k,l) (x) gamma_(k,l) (y). $
    If $w_(k,l) = $
    $ K(x,y) &= sum_(k=0)^(oo) w_k sum_(l=1)^(h_d (k))  gamma_(k,l) (x) gamma_(k,l) (y) wide "(zonal kernel)"\
    &= sum_(k=0)^(oo) w_k P_k^((d)) (x dot y). $
    $P_k^((d))  (t) = C_(k,d) underbrace(P_n^((d/2 - 1, d/2 -1)) (t), "Jacobi polynomial").$
]

#pagebreak()

= Regularization of Risk Functionals
Let $(X', aa)$ be a measurable space, $Y subset RR$ closed subset, $P$ a probability measure on $X' times Y$.
Risk functional $ rr_(L,P) (f) integral_(X' times Y) L(x,y,f(x)) dif P(x,y). $
Minimization $ inf {rr_(L,P) (f) | f in ll^0 (X', Y)} = rr_(L,P)^*. $
Bayes decision function $f_(L,P)^*: X' times Y$ is defined by $ rr_(L,P) (f_(L,P)^*) = rr_(L,P)^*. $

#note[*Problems*][
  + $ll^0 (X',Y)$ is too big to do "reasonable" analysis.
  + How to determine $f_(L,P)^*$?
  Way out: Replace $ll^0 (X',Y)$ by some suitable RKHS $hh_K.$
]

*Regularization*:
For $lambda in (0,oo)$ define $ rr_(L,P,lambda) = rr_(L,P) (f) + lambda ||f||^2_(hh_k). $
*Aim*: $ inf{rr_(L,P,lambda) (f) | f in hh_K}. $

#note[*Questions*][\
  *Q#sub("1")*: Existence: Is there $f_(L,P,lambda)^* in hh_K$ s.t. $rr_(L,P,lambda) (f^*_(L,P,lambda) = inf {rr_(L,P,lambda) (f) | f in hh_K}$?\
  *Q#sub("2")*: Uniqueness: Is $f_(L,P,lambda)^*$ uniquely determined?\
  *Q#sub("3")*: Representation: How can $f_(L,P,lambda)^*$ be represented?\
  *Q#sub("4")*: Dependence on $lambda$: How does $f_(L,P,lambda)^*$ depend on $lambda$?\
  *Q#sub("5")*: Error Analysis: What can be said about $|rr_(L,P) (f_(L,P,lambda)^*) - rr_(L,P)^*|$?
]

For data $D = ((x_1,y_1), ..., (x_n,y_n)) in (X' times Y)^N$ define the _empirical risk_:
$ rr_(L,D,lambda)(f) = rr_(L,D)(f) + lambda||f||^2_hh_K = 1/N sum_(k=1)^(N) L(x_k,y_k,f(x_k)) + lambda ||f||^2_hh_K. $
Minimization:
$ inf{rr_(L,D,lambda)(f) | f in hh_K}. $

#note[*More Questions*][\
  *Q#sub("6")*: Existence for $rr_(L,D,lambda)$?\
  *Q#sub("7")*: Representation of $f^*_(L,D,lambda)$?\
  *Q#sub("8")*: What is the relation between $f^*_(L,P,lambda)$ and $f^*_(L,D,lambda)$?
]

== Existence and Uniqueness
Let $L: X' times Y times RR --> [0,oo)$ be a loss functions, $hh_K$ a RKHS with a measurable kernel $K$, P be a probability measure on $X' times Y.$\
#note[Notation][If $L$ is fixed, write $f^*_(P,lambda)$ instead of $f^*_(L,P,lambda).$]
*Observation*:
$ lambda ||f^*_(P,lambda)||^2_hh_K <= lambda ||f^*_(P,lambda)||^2_hh_K + rr_(L,P)(f^*_(P,lambda)) = inf{rr_(L,P,lambda)(f) | f in hh_K} <= rr_(L,P)(0). $
Consequently $ ||f^*_(P,lambda)||_hh_K <= ((rr_(L,P)(0))/lambda)^(1/2). $

#proposition[Uniqueness][
  Let $L$ be a convex loss function, $hh_K$ a RKHS with a measurable kernel $K$, $P$ a probabilitye measure on $X' times Y$ with $rr_(L,P)(f) < oo$ for some $f in hh_K.$
  There is at most one minimizer of $rr_(L,P,lambda).$
]
#proof[
  Assume there are $f_1,f_2 in hh_K, med f_1 != f_2$ s.t. $ rr_(L,P)(f_1) = inf{rr_(L,P,lambda)(f) | f in hh_K} = rr_(L,P)(f_2). $
  Then $ ||1/2 (f_1 + f_2)||^2_hh_K + ||1/2 (f_1-f_2)||^2_hh_K = ||1/2 f_1||^2_hh_K + ||1/2 f_2||^2_hh_K. $
  Thus $||1/2 (f_1 + f_2)||^2_hh_K < ||1/2 f_1||^2_hh_K + ||1/2 f_2||^2_hh_K. $
  Due to convexity of $L$ and $rr_(L,P,lambda)(f_1) = rr_(L,P,lambda)(f_2)$ we get
  $ rr_(L,P,lambda)(1/2 (f_1 + f_2)) < rr_(L,P,lambda)(f_1). $
  That contradicts the assumption.
]

#lemma[Existence of Global Minimizers][
  Let $E$ be a reflexive Banach space (i.e. $E^(**) tilde.equiv E$, this holds for every Hilbert space).
  Let $phi: E -> RR union {oo}$ is convex lower semi-continuous functional.
  Suppose that there is $M>0$ s.t. ${x in E | phi(x) <= M} != emptyset$ and is bounded.
  Then $phi$ has a global minimum.
  The minimum of $phi$ is unique, provided $phi$ is strictly convex.
]

#theorem[Existence][
  Let $P$ be a probability measure on $X' times Y$, and $L$ be a $P$-integrable Nemitski loss function, and $hh_K$ a RKHS with bounded measurable kernel $K.$
  Then for every $lambda>0$ there is a minimizer $f^*_(L,P,lambda)$ of $rr_(L,P,lambda).$
]<thm:existence>
#proof[
  Since $K$ is bounded and measureable, every $f in hh_K$ is bounded and measurable, and the embedding $iota: hh_K->ll^oo (X')$ is continuous (Prop 4.9).
  $L(x,y,dot)$ is convex, therefore continuous for every $(x,y) in X' times Y$.
  Proposition 3.7 (ii) shows continuity of $rr_(L,P)$, and by Proposition 3.4 it is convex.
  The mapping $hh_K in.rev f |-> lambda ||f||^2_hh_K$ is convex and continuous.
  Hence $rr_(L,P,lambda)$ is convex and continuous.
  Let $ A := { f in hh_K | rr_(L,P,lambda)(f) <= rr_(L,P)(0) } != emptyset. $
  If $f in A$, then $lambda ||f||^2_hh_K <= rr_(L,P)(0).$
  In part $ A subset (rr_(L,P)(0))/lambda B_1 (0), $
  where $B_1 (0) = {f in hh_K | ||f||_hh_K <= 1.$
  Hence $A$ is not empty and bounded.
  Now apply Lemma 5.2.
]

#note[
  Now consider the empirical risk functional $rr_(L,D,lambda).$\
  *Q*: Can we represent the minimizer of nicely?
]

#theorem[Representer Theorem][
  Let $dd = ((x_1,y_1), ..., (x_N, y_N)) in (X' times Y)^N$, $hh_K$ a RKHS with kernel $K$, $L: X' times Y times RR -> [0, oo)$ convex loss function.
  Then $ rr_(L,D,lambda)(f) = 1/N sum_(i=1)^(N) L(x_i, y_i, f(x_i)) + lambda ||f||^2_hh_K $
  has a uniquely determined minimizer $f^*_(L,D,lambda) (=f^*)$ for every $lambda in (0,oo).$
  There are uniquely determined $a_1, ..., a_N in RR$ s.t. $ f^* (x) = sum_(i=1)^(N) a_i K(x,x_i), med x in X'. $<eq:f_star>
]<thm:representer>

#proof[
  Existence and uniqueness follows from @thm:existence.\
  Show @eq:f_star: $xx' = {x_1, ..., x_N}$ and $H_xx' = "span"{K(dot,x_i) | i in {1,...,N}}.$
  Then $H_xx' subset hh_K$ and $K' = K|_(xx' times xx')$ is the representing kernel for $H_xx'.$
  There is a minimizer $f^*_X'$ for $rr_(L,D,lambda): H_xx' -> [0,oo).$
  Consider $H^perp_xx'$ in $hh_K$.
  Then $ f(x) = chevron.l f, K(dot,x_i) chevron.r = 0 med forall i = 1, ...,N med forall f in H^perp_xx'. $
  Let $pp_xx': hh_K -> H_xx'$ be an orthogonal projector.
  Then $f = pp_xx' f + (I-pp_xx')f$ for every $f in hh_K.$
  This implies
  $ rr_(L,D)(f) &= rr_(L,D)(pp_xx' f + (I-pp_xx')f)\
                &= 1/N sum_(i=1)^(N) L(x_i, y_i, pp_xx' f(x_i) + (I-pp_xx')underbrace(f(x_i),=0))\
                &= rr_(L,D)(pp_xx' f). $ 
  Use $||pp_xx'||_hh_K <= ||f||_hh_K$ to get
  $ inf_(f in hh_K) rr_(L,D)(f) + lambda ||f||^2_hh_K &<= inf_(f in H_xx') rr_(L,D)(f) + lambda ||f||^2_hh_K \
                                                      &<= inf_(f in hh_K) rr_(L,D)(f) + lambda ||pp_xx' f||^2_hh_K \
                                                      &<= inf_(f in hh_K) rr_(L,D)(f) + lambda ||f||^2_hh_K $
  Hence, $f^*_xx'$ minimizes $rr_(L,D,lambda)$ over $hh_K$.
  Since the minimizer is unique, there are $a_1, ..., a_N in RR$ s.t. $ f^* = sum_(i=1)^(N) a_i K(dot, x_i). $
]

#remark[
  + The proof of @eq:f_star is not constructive.\
    *Q*: How to find the coefficients $a_1,...,a_N$?
  + It is not clear if $f^* eq.triple.not 0.$ To exclude this, further assumptions on $L$ are necessary.
]

#proposition[
  Let $P$ be a probability measure on $X' times Y$, $L: X' times Y times RR -> [0,oo)$ is convex $P$-integrable Nemitski loss function, $hh_K$ a RKHS with a bounded and measurable kernel $K$.
  If $inf_(f in hh_K) rr_(L,P)(f) < rr_(L,P)(0)$ (\*), then $f^*_(L,P,lambda) eq.not 0$ for every $lambda in (0,oo).$
]
#proof[
  According to the assumptions there is $tilde(f) in hh_K$ s.t. $rr_(L,P)(tilde(f)) < rr_(L,P)(0).$
  Convexity of $L$ gives for $alpha in [0,1]$:
  $ lambda ||alpha tilde(f)||^2_hh_K + rr_(L,P)(alpha tilde(f)) <= lambda alpha^2 ||tilde(f)||^2_hh_K + alpha rr_(L,P)(tilde(f)) + (1-alpha) rr_(L,P)(0) =: h (alpha). $
  The assumption shows that there is $tilde(alpha) in (0,1]$ s.t. $h(tilde(alpha)) <= h(alpha) med forall alpha in [0,1]. $
  This implies:
  $ lambda ||tilde(alpha) tilde(f)||^2_hh_K + rr_(L,P)(tilde(alpha)tilde(f)) <= h(tilde(alpha)) < h(0) = rr_(L,P)(0). $ 
]

#remark[
  + The assumption (\*) does not follow from the fact that $L$ is convex $P$-integrable Nemitski.
    Although $hh_K subset L^oo (X', P_X')$ and $inf_(f in L^oo (X')) rr_(L,P)(f) <= rr_(L,P)(0),$ the condition (\*) does not follow.
  + Is there a similar representation of the minimizer of $rr_(L,P,lambda)$?
]

To clarify, let $(X', aa)$ be a measurable space, $P$ a probability measure on $X' times Y,$ and $L: X'times Y->[0,oo)$ a convex differentiable $P$-integrable Nemitski loss function.
By @prop:frechet the functional $rr_(L,P): L^oo (X', P_X') -> [0,oo)$ is Fréchet differentiable, $rr'_(L,P)(f) in B(L^oo (X', P_X'))$ ($rr'_(L,P)(f)$ is a bounded linear functional), and 
$ rr'_(L,P)(f)g = integral_(X' times Y) g(x) L'(x,y,f(x)) dif P(x,y) wide forall f in L^oo (X', P_X'). $

Let $hh_K$ be a RKHS, $K$ bounded and measurable.
Then the embedding $iota: hh_K -> L^oo (X',P_X')$ is well-defined and continuous.
For $f_0 in hh_K$:
$ (rr_(L,P) compose iota)' = (rr'_(L,P) compose iota) compose iota' = rr'_(L,P) compose iota. $
$ ==> (rr_(L,P) compose iota)' (f_0) f &= integral_(X' times Y) f(x) L' (x,y,f_0 (x)) dif P(x,y) \
                                       &= integral_(X' times Y) chevron.l f, K(dot,x) chevron.r_hh_K L'(x,y,f_0 (x)) dif P(x,y) \
                                       &= integral_(X' times Y) chevron.l f,L'(x,y,f_0 (x)) K(dot,x) chevron.r_hh_K dif P(x,y) \
                                       &= chevron.l f, integral_(X' times Y) L'(x,y,f_0 (x)) K(dot,x) dif P(x,y) chevron.r, $
where $integral_(X' times Y) L'(x,y,f_0 (x)) K(dot, x) dif P(x,y)$ is a #link("https://en.wikipedia.org/wiki/Bochner_integral")[Bochner integral].\
By the Riesz representation theorem (for Hilbert spaces) the mapping $rho: hh_K -> hh'_K, med f |-> chevron.l dot,f chevron.r$ is an *isometric isomorphism*.
This implies:
$ (rr_(L,P) compose iota)' (f_0) = rho(integral_(X' times Y) L'(x,y,f_0 (x)) K(dot,x) dif P(x,y)). $
Let $N: hh_K -> [0,oo), N(f) = ||f||^2_hh_K$.
Then $N'(f) = 2rho(f).$
Necessary condition for minimizer $f^* = f^*_(L,P,lambda)$ for $ rr_(L,P,lambda)(f) = rr_(L,P)(f) + lambda N(f)$:
$ 0 &= ((rr_(L,P) compose iota) + lambda N)'(f^*) \
    &= rho (integral_(X' times Y) L'(x,y,f^*(x)) K(dot,x) dif P(x,y) + 2 lambda f^*) $
since $rho$ is intjective.
This implies $ - integral_(X' times Y) L'(x,y,f^*(x)) K(dot,x) dif P(x,y) = 2 lambda f^*. $
This is an integral equation for $f^*.$
For the empirical measure $D$ we know $ f^* = sum_(i=1)^(N) a_i K(dot,x_i). $
This gives:
$ -1/N sum_(i=1)^(N) L'(x_i,y_i,sum_(j=1)^(N) a_j K(x_i,x_j)) K(x,x_i) = 2 lambda sum_(j=1)^(N) a_j K(x,x_j) $
for every $x in X'$, and $ a_k = -1/(2 lambda N) L'(x_k,y_k,sum_(i=1)^(N) a_i K(x_k,x_i)) $<eq:ak_coefficients>
for every $k in {1,...,N}.$

#note[Algebraic vs Topological dual of a space][$hh_K^*$ is an algebraic dual of $hh_K$, i.e. the space of all linear functionals, and $hh'_K$ is a topological dual, i.e. the space of all continuous (bounded) linear functionals.]

#example[
  $X',P,K,hh_K$ as before, and
  $ L(y,t) = (y-t)^2 $
  We have $ L'(y,t) = partial_t L(y,t) = -2(y-t). $
  Using @eq:ak_coefficients we get
  $ a_k = -1/(2 lambda N) (-2 (y_n - sum_(i=1)^(N) a_i K(x_k,x_i)) = 1/(N lambda) (y_n - sum_(i=1)^(N) a_i K(x_k, x_i)) $
  With the notation
  $ 
    underline(a) = (a_1,...a_N)^top \
    underline(y) = (y_1,...y_N)^top \
    underline(K) = (K(x_n,x_j))_(n,j=1)^N
  $
  we get a linear system for $underline(a)$:
  $ (underline(K) + lambda N I) underline(a) = underline(y) $

  Let again $L(y,t) = (y-t)^2$, $(X',aa)$ be a measurable space, $mu$ a $sigma$-finite Borel measure.
  Let ${phi_k}_(k=1)^oo subset C(X')$ be an ONB for $L^2 (X', mu).$
  Let $ K(x,y) = sum_(k=1)^(oo) w_k phi_k (x) overline(phi)_k (y). $
  With $w_k >= 0 med forall k,$ and $sum_(k=1)^(oo) w_k |phi_k|^2 < oo med forall x in X'.$
  then $K in C(X' times X')$, and $K$ is positive definite.
  Let $hh_K = {f in L^2 (X', mu) | sum_(k=1)^(oo) w_k^(-1) |chevron.l f,phi_k chevron.r|^2  < oo}.$
  // This space consists of functions that have a finite expansion $f = sum_(k=1)^(oo) chevron.l f,phi_k chevron.r phi_k$.
  // If a function didn't have a finite expansion, 
  According to @thm:representer, the minimizer $f^*$ of $rr_(L,D,lambda)$ is
  $ f^* = sum_(i=1)^(N) a_i K(dot,x_i) = sum_(k=1)^(oo) c_k phi_k. $
  Then
  $ ||f||^2_hh_K &= sum_(i=1)^(N) sum_(j=1)^(N) a_i overline(a)_j K(x_i,x_j) \
                 &= sum_(k=1)^(oo) w_k sum_(i=1)^(N) sum_(j=1)^(N) a_i overline(a)_j phi_k (x_i) overline(phi)_k (x_j) $ 
  and $ c_l = integral_X' f(x) overline(phi)_l (x) dif mu(x) = ... = w_l sum_(i=1)^(N) a_i phi_l (x_i). $
  Then $||f||^2_hh_K = sum_(k=1)^(oo) 1/w_k |c_k|^2. $
  Therefore:
  $ rr_(L,D,lambda)(f) = 1/N sum_(i=1)^(N) (y_i - sum_(k=1)^(oo) c_k phi_k)^2 + lambda sum_(k=1)^(oo) 1/w_k |c_k|^2. $
  Use $(partial rr_(L,D,lambda)) / (partial c_k)$ to arrive at $ (K + lambda N I) a = y. $
  #align(right)[_This last step might be a bonus question in the exam._]
]

#note[
  *Q*: Generalization to non-differentiable loss functions?\
  Seen earlier: $f(y,t) = ||x-t| - 1|.$ \
  *A*: Modify the concept of the derivative.\
]

#definition[
  Let $E$, $F$ be Banach spaces over $RR$.
  Let $f: E -> R union {oo}$ be convex, $w in E$ with $f(w) < oo$.
  The subdifferential of $f$ at $w$ is
  $ partial f(w) = \{w' in E' | underbrace(chevron.l w'"," v-w chevron.r, w'(v-w)) <= f(v) - f(w) med forall v in E\}, $
  The subdifferential is a set of continuous linear funcitonals.
  For interpretation in $RR$ see @fig:subdifferential.
]
#figure(
  image("images/subdifferential.png", width: 70%),
  caption: [Interpretation of the subdifferential.]
)<fig:subdifferential>

#example[
  Let $E = RR$ and $f(x) = |x|.$
  Then
  $
    partial f(x) = cases({-1}"," &x<0, [-1,1]"," &x=0, {1}"," & x>0).
  $
]

#proposition[
  Let $E$ be a Banach space, $f: E -> RR union {oo}$ be convex, and $w in E$ s.t. $f(w)<oo$.
  If $f$ is continuous, then $partial f(w)$ is non-empty, convex, and weak#super("*") compact.
  If for $delta > 0$, $c >= 0$ with $|f(w)-f(v)| <= c ||v - w||$ for every $v in w + B(0,delta)$, then $||w'|| <= c$ for every $w' in partial f(w)$.
]

#proposition[
  Let $f,g: F->RR union {oo}$ be convex, $lambda >=0, A in B(E,F).$
  Then
  + $partial (lambda f)(w) = lambda partial f(w) quad forall w in F, f(w) < oo,$
  + if $f$ is continuous at $w_0 in F$ and $f(w_0),g(w_0) < oo$, then $ partial (f+g) (w) = partial f(w) + partial g(w) med forall w in F,$
  // + (Chain Rule) if $v_0 in E$ s.t. $f$ is continuous at $A v_0$ and $f(A v_0) < oo$, then $ partial (f compose A) (v) = A^* partial f(A v) quad forall v in E " s.t. " f(A v) < oo, $
  + (Chain Rule) if $v_0 in E$ s.t. $f$ is continuous at $A v_0$ and $f(A v_0) < oo$, then $ partial (f compose A) (v_0) = A^* partial f(A v_0), $
  + $f$ has a global minimum at $w in F$ if and only if $0 in partial f(w),$
  + if $f(w) < oo$ and $f$ is continuous at $w in F$, then $f$ is Gateaux differentiable at $w$ if and only if $partial f(w)$ contains only one point.
  + if $f(w)<oo$ and $f$ is continuous at $w in E$, then $partial f$ is a monotone operator, i.e. for all $v,w in E, v' in partial f(v), w' in partial f(w): chevron.l v' - w', v - w chevron.r >= 0.$
]

#proposition[
  Let $L: X' times Y times RR -> [0,oo)$ be a convex loss function, $P$ a probability measure on $X' times Y$, and for $1 <= p <= oo:$ $ rr: L^oo (X' times Y, P) -> [0,oo), quad rr(f) = integral_(X' times Y) L(x,y,f(x,y)) dif P(x,y). $
  If $rr(f) < oo$ for every $f in L^p (X' times Y, P)$, then
  $ partial rr(f) = {h in L^p' (X' times Y, P) | h(x,y) in partial L(x,y,f(x,y)) "for" P "-a.a." (x,y) in X' times Y }, wide $
  where $partial L(x,y,t)$ is the subdifferential of $L(x,y,dot).$
]<prop:five_twelve>

#theorem[Representer Theorem for $f^*_(L,P,lambda)$][
  Let $P$ be a probability measure on $X' times Y$, $L: X' times Y times RR -> [0,oo)$ be a convex $P$-integrable Nemitski loss function of order $p in [1,oo]$,
  $hh_K$ a RKHS with $K$ a measurable and bounded kernel.
  Then for every $lambda in (0,oo)$ there is $h in L^p' (X' times Y, P), med 1/p + 1/p' = 1$,
  with $h(x,y) in partial L(x,y,f^*_(L,P,lambda)(x), med (x,y) in X' times Y$ and
  $ f^*_(L,P,lambda) = - 1/(2 lambda) integral_(X' times Y) h(x,y) K(dot,y) dif P(x,y). $
]

#proof[
  $L$ convex $==>$ $L$ continuous (Why?).
  $L$ is $P$-integrable, Nemitski of order $p in [1,oo].$
  Then $ rr: L^p (X' times Y, P) -> [0,oo), quad rr f = integral_(X' times Y) L(x,y,f(x,y)) dif P(x,y) $
  is well-defined and continuous (Prop 3.7 (iii)).
  Use @prop:five_twelve
  $ partial rr(f) = {h in L^p' (X' times Y, P) | h(x,y) in partial L (x,y,f(x,y)) "for a.a." (x,y) in X' times Y } $
  Consider $ E: hh_K -> L^p (X' times Y, P), quad E f(x,y) = f(x). $
  Then
  $ ||E f||^p_p &= integral |E f(x,y)|^p dif P(x,y) = integral_(X' times Y) |f(x)|^p dif P(x,y) \
                &= integral_(X' times Y) |chevron.l f, k(dot, x) chevron.r|^p dif P(x,y) <= integral_(X' times Y) (K(x,x))^(p/2) dif P(x,y) ||f||^p_hh_K \
                &<= c ||f||^p_hh_K. $
  For $h in L^p' (X' times Y , P), med 1/p + 1/p' = 1, med f in hh_K$
  $ integral_(X' times Y) E underbrace(f(x","y), =f(x)) dif P(x,y) &= integral_(X' times Y) chevron.l f, h(x,y) K(dot, x) chevron.r_hh_K dif P(x,y) \
  &= chevron.l f, rho(integral_(X' times Y) h(x,y) K(dot,x) dif P(x,y)) chevron.r_(hh_K). $
  Thus
  $ E^*: (L^p (X' times Y, P))' -> hh_K, quad E^* h = rho(integral_(X' times Y) h(x,y) K(dot, x) dif P(x,y)). $
  The risk functional $rr_(L,P)$ is just $rr compose E.$
  The chain rule for the subdifferential gives $ partial rr_(L,P)(f) = partial (rr compose E)(f) = E^* partial (rr(E f)). $
  Consequently, $partial rr_(L,P)(f) = {rho(E^* h) | h in L^p' (X' times Y, P) and h(x,y) in partial L(x,y,f(x))}. $
  For $N(f) := ||f||^2_hh_K$, we have $N'(f) = 2 rho(f). $
  All in all, $partial rr_(L,P,lambda)(f) = 2 lambda rho(f) + partial rr_(L,P)(f)$ for every f in $hh_K$.
  The functional $rr_(L,P,lambda)$ has a minimum at $ f^*_(L,P, lambda).$
  Thus $0 in partial rr_(L,P,lambda) (f^*_(L,P,lambda))$ since $rho$ is injective the statement follows.
]

== Dependence on the regularization parameter
*Setup*: $P$ a probability measure on $X' times Y$, $L: X' times Y times RR -> [0,oo)$ a loss function, $hh_K$ a RKHS with a measurable kernel $K$.
Let $rr^*_(L,P,hh_K) = inf_(f in hh_K) rr_(L,P)(f)$.
A function $f^*_(L,P,hh_K)$ with $rr_(L,P)(f^*_(L,P,hh_K)) = rr^*_(L,P,hh_K)$ is the minimizer of $rr_(L,P)$.

#definition[Approximation error][
  Define $ A: [0,oo) -> [0,oo), med lambda |-> A(lambda) $
  with $A(lambda) = inf{rr_(L,P)(f) + lambda ||f||^2_hh_K} - rr^*_(L,P,hh_K).$
  $A$ is called _approximation error_.
]

#proposition[
  + $A$ is non-decreasing, concave, and continuous.
  + $A(0) = 0$
  + For $0 < lambda <= theta$ we have $ A(theta) / theta <= A(lambda) / lambda.$
  + for $0 <= lambda < oo$ we have $A(lambda) <= rr_(L,P)(0) - rr^*_(L,P,hh_K).$
  + $A$ is subadditive, i.e. $A(lambda + theta) <= A(lambda) + A(theta) thick forall lambda, theta in [0,oo).$
  + If $h: [0,1] -> [0,oo), med h(lambda) -> 0$ as $lambda -> 1_-$ and $A(lambda) <= lambda h(lambda)$ for every $lambda in [0,1]$, then $ A(lambda) = 0 thick forall lambda >= 0 "and" f^* = 0. $
]

#proof[
  + Use the result\
    #box(stroke: 0.1pt, outset: 4pt, width: 100%)[
      Let ${f_iota | iota in I}$ be a family of affine linear $f_iota: RR->RR.$
      Then $f(x) = sup_(iota in I) f_iota (x)$ is convex, lower-semicontinuous $f: RR->RR union {oo}.$
      The function $f: "dom"(f) -> RR$ is continuous.
    ]
    Apply this to get (i).
  + Clear.
  + Use (i) to get for $0 < lambda <= theta$
    $ A(lambda = A(lambda/theta theta + (1-lambda/theta) dot 0)
               >= lambda/theta A(theta) + (1-lambda/theta) underbrace(A(0),=0)
               = lambda/theta A(theta). $
  + Clear.
  + Let $lambda <= theta.$
    By (iii) $ A(lambda + theta) <= (lambda + theta) theta^(-1) A(theta) = lambda theta^(-1) A(theta) + A(0) <= A(lambda) + A(theta). $
  + Let $A(lambda) <= lambda h(lambda)$ for all $lambda in [0,1].$
    For $lambda->1_-$ we have $A(1) = 0.$
    Since $A(dot)$ is non-decreasing, non-negative, and concave with $A(0) = 0$, it follows $A(lambda) = 0$ for all $lambda >= 0.$
    If there is a minimizer $f^*_(P,lambda)$ of $rr_(L,P,lambda)$ for every $lambda >= 0$, then
      - $lim_(lambda->0_+) rr_(L,P,lambda)(f^*_(L,P,lambda) = rr^*_(L,P,hh_K)$.
      - $lim_(lambda->0_+) rr_(L,P) (f^*_(L,P,lambda)) = rr^*_(L,P,hh_K)$
]

#proposition[Minimizer of minimal norm][
  Let $L$ be a conve loss function, $hh_K$ a RKHS with a measurable kernel $K$, $P$ a probability measure on $X' times Y$ with $rr^*_(L,P,hh_K) < oo$.
  Let $M = {f^* in hh_K | rr_(L,P)(f^*) = rr^*_(L,P,hh_K)}$ be non-empty.
  Then there is a unique $f^* = f^*_(L,P,lambda) in M$ of minimal norm.
]<prop:5.15>

#proof[
  *Uniqueness:* Assume $f^*_1,f^*_2 in M, f^*_1 != f^*_2.$
  Moreover, $||f^*_i||_hh_K <= ||f||_hh_K$ for all $f in M$ and $i in {1,2}$.
  Since $rr_(L,P)$ is convex (from convexity of $L$), $M$ is a convex set.
  Hence $1/2 (f_1+f_2) in M.$
  From the parallelogram identity $ ||1/2 (f_1 + f_2)||^2_hh_K < 1/2(||f_1||^2_hh_K + ||f_2||^2_hh_K) = ||f_1||^2_hh_K $ we get a contradiction.\
  *Existence:* Since $L$ is convex, $rr_(L,P): hh_K -> [0,oo)$ is lower-semi continuous (by Prop 3.5).
  This implies closedness of $M$ in $hh_K.$
  Further, $ N: hh_K -> RR union {oo}, N(f) = cases(|ff|_hh_K"," &f in M, oo "," &"otherwise") $
  is lower semi-continuous and convex.
  Let $f_0 in M.$
  Then ${f in hh_K | N(f) <= ||f||_hh_K} != emptyset$ is a bounded set.
  Apply Theorem 5.3 to see that $N$ has a global minimum, which is $f^*_(L,P,hh_K).$
]

We get for $f^*_(L,P,lambda), f^*_(L,P,hh_K)$
$ ||f^*_(L,P,lambda)||_hh_K <= ||f^*_(L,P,hh_K)||_hh_K. $
To see this, use norm minimality (minimizer?) and consider $ rr_(L,P,lambda)(f^*_(L,P,hh_K)).$
If $lambda = 0$, then $ rr_(L,P,0)(f^*_(L,P,hh_K)) = rr_(L,P)(f^*_(L,P,hh_K)) <= rr_(L,P)(f) quad forall f in hh_K. $
Thus $0 dot ||f^*_(L,P,hh_K)||^2_hh_K + rr_(L,P)(f^*_(L,P,hh_K)) = inf_(f in hh_K) rr_(L,P,0)(f).$
Hence $f^*_(L,P,0) = f_(L,P,hh_K).$

#theorem[Depenndence on the regularization parameter][
  Let $P$ be a probability measure on $X' times Y$, $L$ a convex, $P$-integrable Nemitski loss function, and $hh_K$ a RKHS with an measurable kernel $K.$
  Let $(lambda_n)_(n in NN) subset (0,oo)$ with $lambda_n -->_(n->oo) lambda.$
  If $(f^*_(L,P,lambda_n))_(n in NN) subset hh_K$ is bounded, then there is $f^*_(L,P,lambda) in hh_K$ with $||f^*_(L,P,lambda_n) - f^*_(L,P,lambda)||_hh_K -->_(n->oo) 0.$
]<thm:5.16>
#proof[
  $(f^*_lambda_n)_(n in NN)$ is bounded by assumption.
  There is a subsequence $(f^*_lambda_n_k)_(k in NN)$ s.t. $f^*_lambda_n_k -->_(n -> oo)^w f^*$.
  Then $(f^*_lambda_n_k)_(k in NN)$ is bounded in norm.
  Thus there is $c > 0$ s.t. $||f^*_lambda_n_k||_hh_K -->_(k->oo) 0$since $delta_x in hh'_K$ for every $x in X'$.
  Hence, weak convergence implies pointwise convergence.
  Use Prop 3.7 to get $ rr_(L,P)(f^*_lambda_k) -> rr_(L,P)(f^*). $
  Weak convergence implies $ ||f^*||_hh_K <= liminf_(k->oo) ||f^*_lambda_n_k||_hh_K = lim_(k->oo)||f^*_lambda_n_k||_hh_K = c. $
  $A(dot)$ is continuous, hence
  $
    lambda ||f^*||_hh_K + rr_(L,P)(f^*) - rr^*_(L,P,hh_K) <= lambda c^2 + rr_(L,P)(f^*) - rr^*_(L,P,hh_K)\
    = lim_(k->oo){rr_(L,P,lambda_n_k)(f^*_lambda_n_k) - rr^*_(L,P,hh_K)} = lim_(k->oo) A(lambda_k) = A(lambda).
  $<eq:lambda_ineq>
  Hence, $f^*$ implies $rr_(L,P,lambda).$

  For
  - $lambda>0$: $f^* = f^*_lambda$ due to uniqueness (Prop 5.1).
  - $lambda=0$: $f^*$ minimizes the functional $rr_(L,P)$ over $hh_K$.
    By @eq:lambda_ineq $||f||_hh_K <= ||f^*_(L,P,hh_K)||_hh_K$.
    Since $f^*_(L,P,hh_K)$ is uniquely determined minimizer of minimal norm.
    Hence, $f^* = f^*_(L,P,hh_K) = f^*_(L,P,0)$.
  \ #math.dots.v\
  $lambda ||f^*_lambda||^2_hh_K + rr_(L,P)(f^*_lambda) - rr^*_(L,P,hh_K) = lambda c^2 + rr_(L,P)(f^*_lambda) - rr^*_(L,P,hh_K)$
  \ #math.dots.v\
  Then there is $epsilon > 0$ and a subsequence $(f^*_lambda_n_j)_(j in NN)$ s.t. $||f^*_lambda_n_j - f^*_lambda||_hh_K > epsilon > 0$ for every $j in NN.$
  Apply the argument above to $(f^*_lambda_n_j)_(j in NN.)$
  Then there is a subsequence which converges to $f^*_lambda.$
]

#corollary[
  Let $P$ be a probability measure on $X' times Y$, $L$ convex, $P$ integrable Nemitski loss function, $hh_K$ a RKHS with bounded and measurable kernel.
  Then the following are equivalent:
  1. There is a  minimizer $f^* in hh_K$ of $rr_(L,P).$
  2. The function $(0,oo) in.rev lambda |-> ||f^*_lambda||_hh_K in [0,oo)$ is bounded.
  3. There is $c > 0$ s.t. $A(lambda) <= c lambda med forall lambda >= 0.$
]<cor:5.17>

#proof[
  (ii) $==>$ (iii): Use @thm:5.16.\
  (i) $==>$ (iii): By @prop:5.15 there is $f^*_(L,P,hh_K)$
  $ A(lambda) <= ... "(exam)" $
  (iii) $==>$ (ii): Note that
  $ lambda ||f^*_lambda||^2_hh_K <= lambda ||f^*_lambda||^2_hh_K + rr_(L,P)(f^*_lambda) - rr^*_(L,P,hh_K) = A(lambda) <= c quad (arrow.squiggly "exam"). $
]

#remark[
  Assume one of (i)-(iii) from @cor:5.17.
  Then, assuming $L$ satisfies the conditions in @cor:5.17, we have $A(lambda) <= lambda||f^*_(L,P,hh_K)||^2_hh_K$ and $ ||f^*_lambda - f^*_(L,P,hh_K)||_hh_K -->_(lambda->0_+) 0. $
  For $lambda > 0$, $f^*_lambda$ is a minimizer of $rr_(L,P,lambda)$, since
  $ lambda ||f^*_lambda||^2_hh_K <= rr_(L,P) (f) + lambda||f||^2_hh_K - rr^*_(L,P,hh_K) $ 
  for every $f in hh_K.$
  Then $lambda ||f^*_lambda||^2_hh_K <= A(lambda) <= rr_(L,P)(0) - rr^*_(L,P,hh_K).$
  Hence, $A(dot)$ is a bounded function of $lambda$ and $ ||f^*_lambda||^2_hh_K <= (A(lambda))/lambda -->_(lambda->oo) oo. $
  Hence $lim_(lambda->oo) f^*_lambda = f^*_oo = 0.$
  #figure(
    image("images/L_curve.jpeg", width: 70%),
    caption: [L curve]
  )
]

#corollary[
  Let $P$ be a probability measure on $X' times Y$, $L$ a convex $P$-integrable Nemitski loss function, $hh_K$ a RKHS with $K$ measurable and bounded.
  Then the mappings
  $ (0,oo] -> hh_K&, quad lambda |-> f^*_lambda\
    (0,oo] -> [0,oo)&, quad lambda |-> rr_(L,P)(f^*_lambda) $
  are continuous.
]
#proof[
  Recall Theorems 5.3 and 5.18 and Prop. 3.7.
]

== Dependence of the Minimizer on the Measure.
#theorem[
  Let $p,p' in [1,oo)$ s.t. $1/p + 1/p' = 1$, $P$ a probability measure on $X' times Y$, $L$ a convex $P$-integrable Nemitski loss function of order $p$, $hh_K$ a RKHS with $K$ measurable and bounded.
  Then for every $lambda > 0$ there is $h in cal(L)^p' (X' times Y, P)$ with
  1. $h(x,y) in partial L(x,y,f^*_lambda (x))$ for $(x,y) in X' times Y,$
  2. $f^*_lambda = -1/(2 lambda) integral_(X' times Y) h(x,y) K(dot,y) dif P(x,y) =: cal(K)_p h,$
  3. $h in cal(L)^1 (X' times Y, P),$
  4. $||f^*_(P,lambda) - f^*_(tilde(P),lambda)||_hh_K <= 1/lambda ||kk_p h - kk_tilde(P) h||_hh_K$ for every probability measure $tilde(P)$ for which $L$ is a $tilde(P)$-integrable Nemitski loss function.
]<thm:5.19>

#note[
  - $L^p (X', mu)$ contains equivalence classes of functions.
  - $ll^p (X', mu)$ contains the functions themselves.
]

#proof[
  (i) and (ii) follow from Thm 5.13.\
  (iii) using reproducing property to get
  $ ||f^*_(P,lambda)||_oo <= ||K||_oo ||f^*_(P,lambda)||_hh_K <= ||K||_oo ((rr_(L,P)(0))/lambda)^(1/2) =: B_lambda < oo. $
  $L$ is $tilde(P)$ integrable Nemitski loss function.
  Hence there is $tilde(b) in ll^1 (tilde(P))$, and increasing $tilde(h): [0,oo) -> [0,oo)$ s.t.
  $ L(x,y,t) <= tilde(b)(x,y) + tilde(h)(|t|) quad forall (x,y,t) in X' times Y times RR. $
  Use (i) and Prop 5.10 to get
  $ |h(x,y) <= sup|partial L(x,y,f^*_(P,lambda)(x)| <= |L(x,y,dot)|_([-1+||f^*_(P,lambda)||_oo, 1+||f^*_(P,lambda)||_oo]). $
  This gives
  $ |h(x,y)| &<= |L(x,y,dot)|_([-1+B_lambda,1+B_lambda]) <=^((*)) 1/(1+B_lambda) ||L(x,y,dot)|_([-2+2B_lambda,2+2B_lambda])||_oo \
             &<= (tilde(b)(x,y) + tilde(h)(2+2B_lambda))/(1+B_lambda) $
  #box(width: 100%, stroke: 0.5pt, outset: 5pt)[
    (\*): For every convex function $phi: RR -> RR$ which is locally Lipschitz continuous on $[-t,t]$, we have
    $ |phi|_([-t,t]) |_1 <= 2/t ||phi_([-2t,2t])||_oo. $
  ]
  Hence $h in ll^1 (X' times Y, tilde(P)).$\
  (iv) By definition of the subdifferential
  $ h(x,y) [f^*_(tilde(P),lambda)(x) - f^*_(P,lambda)(x)] <= L(x,y,f^*_(tilde(P),lambda)(x) - L(x,y,f^*_(P,lambda)(x). $
  Integrating w.r.t. $tilde(P)$, we get
  $ integral_(X' times Y) h(x,y) [f^*_(tilde(P),lambda)(x) - f^*_(P,lambda)(x)] dif tilde(P)(x,y) <= rr_(L,tilde(P))(f^*_(tilde(P),lambda)) - rr_(L,tilde(P))(f^*_(P,lambda)) <= 0. $
  Moreover,
  $ integral_(X' times Y) h(x,y) [...] dif tilde(P)(x,y) &= integral_(X' times Y) h(x,y) chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda), K(dot,y) chevron.r_hh_K dif tilde(P)(x,y) \
   &= chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda),  integral_(X' times Y) h(x,y) K(dot, y) dif P(x,y) chevron.r_hh_K \
   &= chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda) , kk_tilde(P) h chevron.r_hh_K $
  Further,
  $ chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda), kk_tilde(P) h - kk_P h chevron.r_hh_K <= ||f^*_(tilde(P),lambda) - f^*_(P,lambda)||hh_K dot ||kk_tilde(P) h - kk_P h||_hh_K. $

  Claim: $ chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda), kk_tilde(P) h - kk_P h chevron.r_hh_K >= lambda ||f^*_(tilde(P),lambda) - f^*_(P,lambda)||_hh_K (**)$
  $ 2lambda chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda), f^*_(P,lambda) chevron.r_hh_K + lambda ||f^*_(tilde(P),lambda) - f^*_(P,lambda)||^2_hh_K = lambda||f^*_(tilde(P),lambda)||^2_hh_K - 2||f^*_(P,lambda)||^2_hh_K. $
  Therefore,
  $ chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda), kk_tilde(P) h + 2 lambda f^*_(P,lambda) chevron.r_hh_K + lambda ||f^*_(tilde(P),lambda) - f^*_(P,lambda)||^2_hh_K = rr_(L,tilde(P),lambda)(f^*_(tilde(P)_lambda - rr_(L,tilde(P),lambda)(f^*_(P,lambda) <= 0. $
  We also have $ f^*_(P,lambda) = -1/(2lambda) kk_P h "("arrow.squiggly"representer theorem)". $
  $ chevron.l f^*_(tilde(P),lambda) - f^*_(P,lambda), kk_tilde(P) h - kk_P h chevron.r_hh_K >= lambda ||f^*_(tilde(P),lambda) - f^*_(P,lambda)||^2_hh_K. $ 
  With this the statement follows.
]

*Exam question*: Representer theorem.
