#import "/template.typ": *

// Local notation for this chapter: the torus and the sphere (blackboard bold).
#let TT = math.bb("T")
#let SS = math.bb("S")

= Integral Operators and Mercer's Theorem <sec:mercer>

In @sec:rkhs we met reproducing kernel Hilbert spaces from two sides: as Hilbert spaces of functions on
which point evaluations are continuous, and as the spaces generated by positive definite kernels through
the Moore–Aronszajn construction (@thm:rkhs-moore-aronszajn). Both points of view are elegant but
abstract. Apart from a few examples, such as the Brownian-motion kernel $K(x, y) = min{x, y}$ whose RKHS
we identified by hand with a Sobolev space (@prop:rkhs-sobolev), they say little about _which_ functions $H_K$ contains and
_what_ its norm measures. For learning, these are the decisive questions. In the regularized problem
(@def:reg-regularized-risk)
$ min_(f in H_K) risk(L, D)(f) + lambda norm(f)_(H_K)^2 $
the risk sees a function only through its values at the data, that is, through an integral with respect to
the data distribution, whereas the regularizer measures it in $H_K$. To understand what regularization
penalizes, and which functions can be learned at all, we must understand how the norm of $H_K$ relates to
$L^2$-type norms.

The tool that makes this possible is the _integral operator_
$ (T_K g)(x) = integral_X K(x, y) g(y) dif mu(y), $
through which the kernel acts on square-integrable functions. The main results of this chapter are:

- If $abs(K)_p < oo$, then $H_K$ sits continuously inside $L^p (mu)$, and the "adjoint" of this inclusion
  is the integral operator with kernel $K$ (@thm:mercer-lp-embedding).
- $T_K$ is a compact, positive, self-adjoint trace-class operator on $L^2(mu)$ whose trace is
  $integral K(x, x) dif mu(x)$ (@thm:mercer-integral-operator). Its eigenfunctions have distinguished
  representatives in $H_K$ which, suitably rescaled, are orthonormal there
  (@prop:mercer-eigenfunctions).
- *Mercer's theorem* (@thm:mercer): for a continuous positive definite kernel on a compact metric space
  and a measure of full support,
  $ K(x, y) = sum_j lambda_j e_j (x) overline(e_j (y)) $
  with absolute and uniform convergence, where $(lambda_j, e_j)$ are the eigenpairs of $T_K$.
- The resulting *spectral picture* (@prop:mercer-rkhs-spectral):
  $ H_K = {sum_j a_j sqrt(lambda_j) e_j : (a_j) in ell^2}, quad
    norm(f)_(H_K)^2 = sum_j abs(ip(f, e_j)_(L^2(mu)))^2 / lambda_j . $
  An RKHS is a space of functions whose "generalized Fourier coefficients" decay faster than the
  eigenvalues of $T_K$. Since eigenfunctions with small eigenvalues are typically highly oscillating, $H_K$
  behaves like a space of smooth functions, and $lambda norm(f)_(H_K)^2$ is a penalty on roughness. On the
  torus and on the sphere this recovers Fourier series, spherical harmonics and Sobolev spaces
  (@ex:mercer-torus, @ex:mercer-sphere).

These results are used throughout the rest of the book: the Fourier kernels of @ex:mercer-torus
reappear as universal kernels in @ex:univ-fourier, and the spectral picture explains how kernel ridge
regression (@ex:reg-krr) filters the data.

Throughout the chapter $KK in {RR, CC}$, and $overline(z) = z$ if $KK = RR$. We use the conventions of
@sec:rkhs: $K_x = K(dot, x)$, $K(x, x') = ip(K_(x'), K_x)_(H_K) = K_(x') (x)$, and the reproducing
property $f(x) = ip(f, K_x)_(H_K)$ (@eq:rkhs-reproducing). Inner products are linear in the first and
conjugate-linear in the second argument.

== Why integral operators? <sec:mercer-motivation>

Before developing the general theory, let us look at a case in which everything is linear algebra. It
contains, in miniature, every result of this chapter.

#example(title: [Finite input spaces])[
  Let $X = {x_1, ..., x_N}$ consist of $N$ distinct points, let $mu = 1/N sum_(i=1)^N delta_(x_i)$ be the
  uniform distribution on $X$, and let $K$ be a strictly positive definite kernel on $X$ (@def:rkhs-pd).
  We identify a function $f: X -> KK$ with the vector $bold(f) = (f(x_1), ..., f(x_N))^top in KK^N$ and
  write $bold(K) = (K(x_i, x_l))_(i,l=1)^N$ for the Gram matrix, which is Hermitian and positive definite.

  + *The RKHS.* $H_K = KK^X$ with inner product $ip(f, g)_(H_K) = bold(g)^* bold(K)^(-1) bold(f)$. Indeed,
    this is an inner product because $bold(K)^(-1)$ is positive definite, the kernel section $K_(x_i)$ is
    the $i$-th column $bold(K) epsilon_i$ of $bold(K)$ ($epsilon_i$ the $i$-th unit vector), and
    $ip(f, K_(x_i))_(H_K) = (bold(K) epsilon_i)^* bold(K)^(-1) bold(f) = epsilon_i^top bold(f) = f(x_i)$.
    By uniqueness of the RKHS of a kernel (@thm:rkhs-moore-aronszajn), this is $H_K$.
  + *The integral operator.* $L^2(mu) = KK^X$ with $ip(g, h)_(L^2(mu)) = 1/N sum_i g(x_i) overline(h(x_i))$,
    and $(T_K g)(x_i) = integral K(x_i, y) g(y) dif mu(y) = 1/N sum_l K(x_i, x_l) g(x_l)$. So $T_K$ is the
    matrix $1/N bold(K)$, which is self-adjoint and positive with respect to $ip(dot, dot)_(L^2(mu))$.
    Let $lambda_1 >= ... >= lambda_N > 0$ be its eigenvalues and $e_1, ..., e_N$ corresponding eigenvectors,
    orthonormal in $L^2(mu)$, i.e. $1/N bold(e)_j^* bold(e)_l = delta_(j l)$.
  + *Mercer's expansion.* Since $bold(K) bold(e)_l = N lambda_l bold(e)_l$ and
    $bold(e)_j^* bold(e)_l = N delta_(j l)$, the matrix $sum_j lambda_j bold(e)_j bold(e)_j^*$ agrees with
    $bold(K)$ on the basis $(bold(e)_l)$, so
    $ K(x_i, x_l) = sum_(j=1)^N lambda_j e_j (x_i) overline(e_j (x_l)), quad i, l = 1, ..., N. $
  + *The spectral picture.* Similarly $bold(K)^(-1) = sum_j (N^2 lambda_j)^(-1) bold(e)_j bold(e)_j^*$, and
    since $ip(f, e_j)_(L^2(mu)) = 1/N bold(e)_j^* bold(f)$,
    $ norm(f)_(H_K)^2 = bold(f)^* bold(K)^(-1) bold(f) = sum_(j=1)^N abs(ip(f, e_j)_(L^2(mu)))^2 / lambda_j . $
] <ex:mercer-finite>

The last formula is the heart of the matter. The $L^2(mu)$-norm weighs all directions $e_j$ equally,
$norm(f)_(L^2(mu))^2 = sum_j abs(ip(f, e_j))^2$, whereas the $H_K$-norm divides the $j$-th coefficient by
$lambda_j$. Directions with small eigenvalue are expensive. If $mu$ is the empirical distribution of a
data set, the eigen-decomposition of $1/N bold(K)$ is (uncentered) *kernel principal component analysis*
@schoelkopf1998: the $e_j$ with large $lambda_j$ are the directions of large variance of the data in
feature space, and the $H_K$-norm is cheap along them.

For infinite $X$ the same structure appears, but now with an operator on an infinite-dimensional space.
The classical example is Fourier analysis. On the circle $TT = RR \/ 2 pi ZZ$ with the normalized Lebesgue
measure, consider $K(x, y) = sum_(k in ZZ) w_k e^(i k (x - y))$ with weights $w_k >= 0$, $sum_k w_k < oo$. A
short computation (@ex:mercer-torus) shows that the integral operator $T_K$ multiplies the $k$-th Fourier
coefficient by $w_k$, i.e. its eigenfunctions are $e^(i k x)$ with eigenvalues $w_k$, and that
$ norm(f)_(H_K)^2 = sum_(k in ZZ) abs(hat(f)(k))^2 / w_k . $
For $w_k = (1 + k^2)^(-1)$ this is $norm(f)_(L^2)^2 + norm(f')_(L^2)^2$: the RKHS is the Sobolev space
$H^1(TT)$, and the norm measures smoothness. The general theory of this chapter replaces the Fourier basis
by the eigenfunctions of $T_K$, which exist for every kernel with $integral K(x, x) dif mu(x) < oo$.

#intuition[
  Think of the eigenfunctions $e_j$ of $T_K$ as the "frequencies" adapted to the kernel $K$ and the
  measure $mu$. For the kernels used in practice, $e_j$ oscillates more and more as $j$ grows while
  $lambda_j -> 0$. A function belongs to $H_K$ if its coefficients along the high frequencies are small
  enough to compensate for the tiny $lambda_j$. The regularizer $lambda norm(f)_(H_K)^2$ therefore charges
  the price $lambda \/ lambda_j$ per unit of squared coefficient along $e_j$: coarse structure is cheap,
  fine structure is expensive. How fast $lambda_j$ decays determines how smooth the functions in $H_K$
  are.
]

#context-note[
  The same mathematics appears in statistics as the *Karhunen–Loève expansion*. If $(Z_x)_(x in X)$ is a
  centered stochastic process with covariance function $K(x, y) = EE[Z_x overline(Z_y)]$, the eigenpairs
  of $T_K$ provide the expansion $Z_x = sum_j sqrt(lambda_j) xi_j e_j (x)$ with uncorrelated coefficients
  $xi_j$ of unit variance. This is principal component analysis for random functions, and Mercer's
  theorem is its deterministic backbone. See @berlinet2004 for the connection between RKHSs, Gaussian
  processes and such expansions, and @rasmussen2006 for Gaussian processes in machine learning.
]

== The RKHS inside $L^p (mu)$ <sec:mercer-lp>

To let a kernel act on $L^2(mu)$ we first have to understand how $H_K$ and $L^p (mu)$ are related. One
point needs care from the start: elements of $H_K$ are genuine functions, which can be evaluated at
every point, whereas elements of $L^p (mu)$ are equivalence classes of functions that agree
$mu$-almost everywhere. We write $cal(L)^p (mu)$ for the space of $p$-integrable measurable functions and
$[f] in L^p (mu)$ for the class of $f in cal(L)^p (mu)$. The map $f |-> [f]$ forgets information: two
different functions in $H_K$ may have the same class, and then no $L^p$-argument can distinguish them.
Keeping track of this distinction is the main technical point of the chapter.

*The measurable setting.* For @sec:mercer-lp – @sec:mercer-spectral we fix:
- a measurable space $(X, cal(A))$ and a $sigma$-finite measure $mu$ on $(X, cal(A))$;
- a positive definite kernel $K: X times X -> KK$ with RKHS $H_K$ such that
  #set enum(numbering: "(M1)")
  + $K_x = K(dot, x): X -> KK$ is measurable for every $x in X$, and
  + $H_K$ is separable.

Condition (M1) makes the functions in $H_K$ measurable, and (M2) is needed to integrate $H_K$-valued
functions (Bochner integrals, @def:app-bochner). Both hold in the most important situation: if $X$ is a
separable metric space (with its Borel $sigma$-algebra) and $K$ is continuous, then each $K_x$ is
continuous, hence measurable, and $H_K$ is separable by @prop:rkhs-separable. Condition (M2) is a genuine
restriction, though. The kernel $K(x, y) = ind_({x = y})$ on $X = RR$ is jointly measurable, but its RKHS
is $ell^2(RR)$, the space of square-summable functions on $RR$ (with countable support), which is not
separable.

By @prop:rkhs-measurable, the measurable setting has the following consequences, which we use without
further mention: every $f in H_K$ is measurable; the canonical feature map $Phi_K: X -> H_K$,
$x |-> K_x$, is strongly measurable; and for every orthonormal basis $(v_n)_(n in I)$ of $H_K$ ($I$
countable),
$ K(x, x') = sum_(n in I) v_n (x) overline(v_n (x')) quad "and" quad K(x, x) = sum_(n in I) abs(v_n (x))^2, quad x, x' in X, $ <eq:mercer-onb-kernel>
so that $K$ is $cal(A) times.o cal(A)$-measurable and $x |-> K(x, x)$ is measurable. In particular the
kernel "norms" of @def:rkhs-kernel-norms are defined:
$ abs(K)_p = (integral_X K(x, x)^(p\/2) dif mu(x))^(1\/p) in [0, oo], quad 1 <= p < oo. $
Note the exponent $p\/2$: since $K(x, x) = norm(K_x)_(H_K)^2$, $abs(K)_p$ is the $L^p (mu)$-norm of
$x |-> norm(Phi_K (x))_(H_K) = sqrt(K(x, x))$.

When is the map $f |-> [f]$ injective on $H_K$? In general it is not, as the following example shows,
but for continuous functions and measures that charge every open set it is. Recall that the *support* of
a Borel measure $mu$ on a topological space $X$ is
$ supp mu = {x in X : mu(U) > 0 "for every open set" U "containing" x}. $

#example[
  Let $X = [0, 2]$ and let $mu$ be the Lebesgue measure restricted to $[0, 1]$, so $supp mu = [0, 1]$. For
  the kernel $K(x, y) = f_0 (x) f_0 (y)$ with $f_0 (x) = max{x - 1, 0}$, the RKHS is $H_K = spn{f_0}$ (use
  the feature map $x |-> f_0 (x) in RR$ and @prop:rkhs-feature-representation). The function $f_0 != 0$
  vanishes on $[0, 1]$, so $[f_0] = 0$ in $L^p (mu)$: the inclusion $H_K -> L^p (mu)$ is the zero map.
] <ex:mercer-noninjective>

#proposition[
  Let $X$ be a topological space, $mu$ a measure on the Borel $sigma$-algebra of $X$ with $supp mu = X$, and
  $f, g: X -> KK$ continuous with $f = g$ $mu$-almost everywhere. Then $f = g$ everywhere. In particular,
  every class in $L^p (mu)$ has at most one continuous representative.
] <prop:mercer-support>

#proof[
  The set $U = {x in X : f(x) != g(x)}$ is open, because $f - g$ is continuous, and $mu(U) = 0$ by
  assumption. If there were a point $x in U$, then $U$ would be an open neighbourhood of $x$ of measure zero,
  contradicting $x in supp mu$. Hence $U = emptyset$.
]

The next theorem is the basic result on the relation between $H_K$ and $L^p (mu)$. For $1 <= p < oo$ we
denote by $p' in (1, oo]$ the conjugate exponent, $1\/p + 1\/p' = 1$.

#theorem(title: [RKHS in $L^p$])[
  Let $(X, cal(A))$ be a measurable space, $mu$ a $sigma$-finite measure on $(X, cal(A))$, and $K$ a positive
  definite kernel on $X$ such that $K(dot, x)$ is measurable for every $x in X$ and $H_K$ is separable. Let
  $1 <= p < oo$ with $abs(K)_p < oo$. Then:
  + *(Embedding.)* $H_K subset.eq cal(L)^p (mu)$ and $norm(f)_(L^p (mu)) <= abs(K)_p norm(f)_(H_K)$ for all
    $f in H_K$. Hence the inclusion operator
    $ iota_p: H_K -> L^p (mu), quad f |-> [f], $
    is linear and bounded with $norm(iota_p) <= abs(K)_p$.
  + *(Integral operator.)* For every $g in cal(L)^(p') (mu)$ the $H_K$-valued function $y |-> g(y) K_y$ is
    Bochner integrable. The element
    $ S_p g := integral_X g(y) K_y dif mu(y) in H_K $
    depends only on the class $[g]$, and it is the function
    $ (S_p g)(x) = integral_X K(x, y) g(y) dif mu(y), quad x in X, $ <eq:mercer-S-pointwise>
    where the integral converges absolutely for every $x$. The operator $S_p: L^(p') (mu) -> H_K$ is linear
    and bounded with $norm(S_p) <= abs(K)_p$.
  + *(Adjoint relation.)* For all $f in H_K$ and $g in L^(p') (mu)$,
    $ ip(f, S_p g)_(H_K) = integral_X f overline(g) dif mu . $ <eq:mercer-duality>
  + $iota_p (H_K)$ is dense in $L^p (mu)$ if and only if $S_p$ is injective.
  + $Ran S_p$ is dense in $H_K$ if and only if $iota_p$ is injective, i.e. if and only if the zero function
    is the only $f in H_K$ with $f = 0$ $mu$-almost everywhere. More precisely,
    $(Ran S_p)^perp = Ker iota_p$.
] <thm:mercer-lp-embedding>

#proof[
  We abbreviate $H = H_K$.

  (i) Let $f in H$. It is measurable by @prop:rkhs-measurable, and
  $abs(f(x)) = abs(ip(f, K_x)_H) <= norm(f)_H sqrt(K(x, x))$ for all $x$ by the Cauchy–Schwarz inequality
  (see @prop:rkhs-kernel-properties). Hence
  $ integral_X abs(f)^p dif mu <= norm(f)_H^p integral_X K(x, x)^(p\/2) dif mu(x) = norm(f)_H^p abs(K)_p^p . $

  (ii) and (iii). Fix a representative $g in cal(L)^(p') (mu)$. Hölder's inequality
  (@sec:app-lp) with exponents $p'$ and $p$ gives
  $ integral_X abs(g(y)) sqrt(K(y, y)) dif mu(y) & <= norm(g)_(L^(p') (mu)) (integral_X K(y, y)^(p\/2) dif mu(y))^(1\/p) \
    & = abs(K)_p norm(g)_(L^(p') (mu)) < oo . $ <eq:mercer-holder>
  This is the hypothesis of @prop:app-bochner-feature-map. Hence $g Phi_K: y |-> g(y) K_y$ is Bochner
  integrable, and for all $f in H$ and $x in X$
  $ ip(f, S_p g)_H = integral_X overline(g(y)) f(y) dif mu(y), quad (S_p g)(x) = integral_X g(y) K(x, y) dif mu(y), $
  which are @eq:mercer-duality and @eq:mercer-S-pointwise. The last integral converges absolutely, since
  $abs(K(x, y)) <= sqrt(K(x, x)) sqrt(K(y, y))$ (@prop:rkhs-kernel-properties) and @eq:mercer-holder.
  Since $norm(g(y) K_y)_H = abs(g(y)) sqrt(K(y, y))$, @thm:app-bochner-properties (i) and
  @eq:mercer-holder give $norm(S_p g)_H <= abs(K)_p norm(g)_(L^(p') (mu))$. If $g = tilde(g)$ $mu$-almost
  everywhere, the same estimate applied to $g - tilde(g)$ shows $S_p g = S_p tilde(g)$; thus $S_p$ is well
  defined on classes, and it is clearly linear.

  (iv) By the Hahn–Banach theorem (@thm:app-hahn-banach (iii)), $iota_p (H)$ is dense in $L^p (mu)$ if and
  only if the only functional $phi in L^p (mu)'$ vanishing on $iota_p (H)$ is $phi = 0$. By the duality of
  $L^p$-spaces (@thm:app-lp-duality; $mu$ is $sigma$-finite and $1 <= p < oo$), every $phi in L^p (mu)'$ is
  of the form $phi(h) = integral h g_0 dif mu$ for a unique $g_0 in L^(p') (mu)$. Writing $g := overline(g_0)$,
  we get $phi = phi_g := integral (dot) overline(g) dif mu$, and $g |-> phi_g$ is a (conjugate-linear)
  bijection $L^(p') (mu) -> L^p (mu)'$. By @eq:mercer-duality, $phi_g$ vanishes on $iota_p (H)$ if and only
  if $ip(f, S_p g)_H = 0$ for all $f in H$, i.e. if and only if $S_p g = 0$. Hence $iota_p (H)$ is dense if
  and only if $S_p g = 0$ implies $g = 0$.

  (v) In the Hilbert space $H$, a subspace is dense if and only if its orthogonal complement is ${0}$
  (@thm:app-projection (iv)), so it suffices to prove $(Ran S_p)^perp = Ker iota_p$. By @eq:mercer-duality,
  $f perp Ran S_p$ if and only if $integral f overline(g) dif mu = 0$ for all $g in L^(p') (mu)$. This
  holds if $[f] = 0$. Conversely, suppose it holds and put $g := abs(f)^(p - 2) f$ on ${f != 0}$ and $g := 0$
  elsewhere. For $p > 1$ we have $abs(g)^(p') = abs(f)^((p-1) p') = abs(f)^p$, and for $p = 1$ we have
  $abs(g) <= 1$; in both cases $g in cal(L)^(p') (mu)$. Then
  $0 = integral f overline(g) dif mu = integral abs(f)^p dif mu$, so $[f] = 0$.
]

#remark(title: [Which adjoint?])[
  The operator $S_p$ is the adjoint of $iota_p$ in the following precise sense. The Banach-space adjoint
  of $iota_p$ is $iota'_p: L^p (mu)' -> (H_K)'$, $phi |-> phi compose iota_p$. Let
  $tilde(J): L^(p') (mu) -> L^p (mu)'$, $tilde(J) g := phi_g = integral (dot) overline(g) dif mu$; in terms of
  the linear isometric isomorphism $J$ of @thm:app-lp-duality (which uses the _bilinear_ pairing),
  $tilde(J) g = J overline(g)$. Let $R: (H_K)' -> H_K$ be the Riesz map (@thm:app-riesz), whose inverse is
  $h |-> ip(dot, h)_(H_K)$. Both $tilde(J)$ and $R$ are conjugate-linear isometric bijections, and
  @eq:mercer-duality says $iota'_p (tilde(J) g) = ip(dot, S_p g)_(H_K) = R^(-1)(S_p g)$, i.e.
  $ S_p = R compose iota'_p compose tilde(J) . $
  The two conjugations cancel, so $S_p$ is linear. If $KK = RR$, both $tilde(J)$ and $R$ are the standard
  linear identifications, and $S_p$ _is_ the Banach-space adjoint of $iota_p$ up to these
  identifications. For $p = 2$, @eq:mercer-duality reads
  $ip(S_2 g, f)_(H_K) = ip(g, iota_2 f)_(L^2(mu))$, i.e. $S_2$ is the Hilbert-space adjoint of $iota_2$:
  $ S_2 = iota_2^*, quad iota_2 = S_2^* . $
  Moreover $norm(S_p) = norm(iota_p)$: by @eq:mercer-duality,
  $ norm(S_p g)_(H_K) = sup_(norm(f)_(H_K) <= 1) abs(integral f overline(g) dif mu) <= norm(iota_p) norm(g)_(L^(p')), $
  and conversely, testing with the function $g$ from the proof of (v) (normalized) shows
  $ norm(iota_p f)_(L^p) = sup_(norm(g)_(L^(p')) <= 1) abs(integral f overline(g) dif mu) <= norm(S_p) norm(f)_(H_K) . $
] <rem:mercer-banach-adjoint>

#remark[
  + The kernel $Ker iota_p = {f in H_K : f = 0 space mu"-a.e."}$ does not depend on $p$. Hence, by (v),
    either $Ran S_p$ is dense in $H_K$ for every $p$ with $abs(K)_p < oo$, or for none.
  + If $X$ is a topological space with its Borel $sigma$-algebra, $H_K subset.eq C(X)$ (e.g. $K$ bounded
    and continuous, @prop:rkhs-continuous) and $supp mu = X$, then $iota_p$ is injective by
    @prop:mercer-support. This is the situation of Mercer's theorem below. The support condition cannot
    be dropped, as @ex:mercer-noninjective shows.
  + If $mu$ is a probability measure and $K$ is bounded, then $abs(K)_p <= abs(K)_oo$ for every $p$, and
    @thm:mercer-lp-embedding applies for all $1 <= p < oo$. For unbounded kernels, $abs(K)_p < oo$ is a
    moment condition on $mu$; see @ex:mercer-linear below.
  + Density of $H_K$ in $L^p (mu)$ is a first, weak form of the richness properties studied in
    @sec:univ: if $X$ is a compact metric space, $mu$ a finite Borel measure and $K$ universal
    (@def:univ-universal), then $H_K$ is dense in $C(X)$ with respect to $norm(dot)_oo$, and $C(X)$ is
    dense in $L^p (mu)$, so $iota_p (H_K)$ is dense in $L^p (mu)$ for every $1 <= p < oo$.
]

== The integral operators $S_K$ and $T_K$ <sec:mercer-operators>

From now on we concentrate on $p = 2$, where both spaces are Hilbert spaces and the full power of
spectral theory is available. We write
$ iota := iota_2: H_K -> L^2(mu), quad S_K := S_2: L^2(mu) -> H_K, quad T_K := S_K^* S_K = iota S_K : L^2(mu) -> L^2(mu). $

*Hilbert–Schmidt and trace-class operators.* Recall (@def:app-compact-operators) that a bounded operator
$A: H_1 -> H_2$ between Hilbert spaces is a *Hilbert–Schmidt operator* if
$ norm(A)_("HS")^2 := sum_(e in E) norm(A e)_(H_2)^2 < oo $
for an orthonormal basis $E$ of $H_1$. Since $L^2(mu)$ need not be separable, $E$ may be uncountable; a sum
of nonnegative numbers over an arbitrary index set is the supremum of its finite partial sums. The
Hilbert–Schmidt norm does not depend on $E$, it satisfies $norm(A^*)_("HS") = norm(A)_("HS")$ and
$norm(A) <= norm(A)_("HS")$, and Hilbert–Schmidt operators are compact (@thm:app-operator-facts (ii)). A
positive compact operator $T$ with nonzero eigenvalues $(lambda_j)_(j in J)$, repeated according to
multiplicity, is *trace class* if $tr T := sum_j lambda_j < oo$; for positive $T$ the trace is also the trace
norm. For $T = A^* A$ with Hilbert–Schmidt $A$ one has $tr T = sum_(e in E) ip(T e, e) = norm(A)_("HS")^2$
for every orthonormal basis $E$ (@thm:app-operator-facts (iii), (iv)).

#theorem(title: [The integral operators of a kernel])[
  Let $(X, cal(A))$ be a measurable space, $mu$ a $sigma$-finite measure on $(X, cal(A))$, and $K$ a positive
  definite kernel on $X$ such that $K(dot, x)$ is measurable for every $x in X$, $H_K$ is separable, and
  $abs(K)_2^2 = integral_X K(x, x) dif mu(x) < oo$. Let
  $ S_K: L^2(mu) -> H_K, quad S_K g = integral_X g(y) K_y dif mu(y), quad (S_K g)(x) = integral_X K(x, y) g(y) dif mu(y), $
  be the operator $S_2$ of @thm:mercer-lp-embedding, and let $iota: H_K -> L^2(mu)$ be the inclusion. Then:
  + $S_K^* = iota$, i.e. the adjoint of $S_K$ is the embedding of $H_K$ into $L^2(mu)$.
  + $S_K$ and $iota$ are Hilbert–Schmidt operators with $norm(S_K)_("HS") = norm(iota)_("HS") = abs(K)_2$.
    In particular, both are compact.
  + The operator $T_K := S_K^* S_K: L^2(mu) -> L^2(mu)$ satisfies $T_K g = [S_K g]$, that is,
    $ (T_K g)(x) = integral_X K(x, y) g(y) dif mu(y) quad "for" mu"-almost every" x in X, $ <eq:mercer-TK>
    and the right-hand side, defined for every $x$, is the representative $S_K g in H_K$ of $T_K g$. The
    operator $T_K$ is compact, self-adjoint and positive, $Ker T_K = Ker S_K$, and
    $norm(T_K) = norm(S_K)^2 <= abs(K)_2^2$.
  + $T_K$ is trace class: for every orthonormal basis $E$ of $L^2(mu)$,
    $ sum_(e in E) ip(T_K e, e)_(L^2(mu)) = norm(S_K)_("HS")^2 = abs(K)_2^2, $
    and if $(lambda_j)_(j in J)$ are the nonzero eigenvalues of $T_K$, repeated according to multiplicity,
    then
    $ tr T_K = sum_(j in J) lambda_j = integral_X K(x, x) dif mu(x) . $ <eq:mercer-trace>
] <thm:mercer-integral-operator>

#proof[
  (i) This is @rem:mercer-banach-adjoint: by @eq:mercer-duality, for all $g in L^2(mu)$ and $f in H_K$,
  $ ip(S_K g, f)_(H_K) = overline(ip(f, S_K g)_(H_K)) = overline(ip(iota f, g)_(L^2(mu))) = ip(g, iota f)_(L^2(mu)), $
  which is the defining property of $S_K^* = iota$.

  (ii) Let $(v_n)_(n in I)$ be an orthonormal basis of $H_K$ ($I$ countable by (M2)). By monotone
  convergence and @eq:mercer-onb-kernel,
  $ sum_(n in I) norm(iota v_n)_(L^2(mu))^2 = sum_(n in I) integral_X abs(v_n (x))^2 dif mu(x)
    = integral_X sum_(n in I) abs(v_n (x))^2 dif mu(x) = integral_X K(x, x) dif mu(x) = abs(K)_2^2 . $
  Hence $iota$ is Hilbert–Schmidt with $norm(iota)_("HS") = abs(K)_2$, and by (i) and
  @thm:app-operator-facts (ii), $norm(S_K)_("HS") = norm(S_K^*)_("HS") = norm(iota)_("HS")$. Hilbert–Schmidt
  operators are compact (@thm:app-operator-facts (ii)).

  (iii) By (i), $T_K g = iota(S_K g) = [S_K g]$, and @eq:mercer-S-pointwise gives @eq:mercer-TK. By (ii) and
  @thm:app-operator-facts (iii), $T_K = S_K^* S_K$ is compact and positive (in particular self-adjoint),
  since
  $ ip(T_K g, g)_(L^2(mu)) = ip(S_K g, S_K g)_(H_K) = norm(S_K g)_(H_K)^2 >= 0 . $ <eq:mercer-positive>
  This identity shows $Ker T_K subset.eq Ker S_K$; the converse inclusion is obvious. Finally,
  $norm(T_K) <= norm(S_K^*) norm(S_K) = norm(S_K)^2$, and by @eq:mercer-positive
  $norm(S_K g)^2 <= norm(T_K g) norm(g) <= norm(T_K) norm(g)^2$, so $norm(T_K) = norm(S_K)^2$; and
  $norm(S_K) <= abs(K)_2$ by @thm:mercer-lp-embedding (ii).

  (iv) By @eq:mercer-positive, (ii) and @thm:app-operator-facts (iii), for every orthonormal basis $E$ of
  $L^2(mu)$,
  $ sum_(e in E) ip(T_K e, e)_(L^2(mu)) = sum_(e in E) norm(S_K e)_(H_K)^2 = norm(S_K)_("HS")^2 = abs(K)_2^2 , $
  and by @thm:app-operator-facts (iv) the left-hand side equals $sum_(j in J) lambda_j$ (evaluate it in an
  orthonormal basis consisting of eigenvectors for the nonzero eigenvalues, @thm:app-spectral, and of an
  orthonormal basis of $Ker T_K$). This proves @eq:mercer-trace, and in particular $T_K$ is trace class.
]

#warning-block[
  Do not confuse the two norms of $T_K$ that involve $K$. The _trace norm_
  $ tr T_K = norm(S_K)_("HS")^2 = abs(K)_2^2 = integral_X K(x, x) dif mu(x) $
  involves only the diagonal of $K$ and the Hilbert–Schmidt norm of $S_K$ (note the square). The
  _Hilbert–Schmidt norm_ of $T_K$ involves all of $K$:
  $ norm(T_K)_("HS") = norm(K)_(L^2(mu times.o mu)) <= abs(K)_2^2 $
  (@prop:mercer-ae-expansion (iii) below). The inequality holds because
  $abs(K(x, y))^2 <= K(x, x) K(y, y)$, whose double integral is $abs(K)_2^4$; in particular
  $K in L^2(mu times.o mu)$ whenever $abs(K)_2 < oo$. (The general result on integral operators,
  @prop:app-integral-operators, gives "$<=$" and gives equality only for separable $L^2(mu)$; for kernels of
  positive type we will obtain equality without this assumption.)
]

So $S_K g$ is the function $x |-> integral K(x, y) g(y) dif mu(y)$ regarded as an element of $H_K$, and
$T_K g$ is the same function regarded as an element of $L^2(mu)$. The operator $T_K$ is the one that
spectral theory can analyse; $S_K$ remembers the pointwise values. There is a third operator, obtained by
composing in the other order.

#remark(title: [The covariance operator])[
  The operator $C_K := S_K S_K^* = S_K iota: H_K -> H_K$, $C_K f = integral_X f(y) K_y dif mu(y)$, satisfies
  $ ip(C_K f, h)_(H_K) = ip(iota f, iota h)_(L^2(mu)) = integral_X f overline(h) dif mu = integral_X ip(f, Phi_K (x))_(H_K) overline(ip(h, Phi_K (x))_(H_K)) dif mu(x) . $
  If $mu = P_X$ is a probability measure, $C_K$ is therefore the (uncentered) *covariance operator* of the
  random feature vector $Phi_K (x)$, $x tilde P_X$. We will see in @prop:mercer-eigenfunctions that $C_K$
  and $T_K$ have the same nonzero eigenvalues. Eigen-analysis of $T_K$ is thus principal component
  analysis in feature space, and for the empirical measure it becomes kernel PCA
  @schoelkopf1998 @schoelkopf2002.
] <rem:mercer-covariance>

#example(title: [The linear kernel and PCA])[
  Let $X = RR^d$, $KK = RR$, $K(x, x') = ip(x, x')$ the linear kernel, and $mu$ a $sigma$-finite Borel measure on $RR^d$. The
  RKHS consists of the linear functions $f_w = ip(w, dot)$, $w in RR^d$, with $norm(f_w)_(H_K) = abs(w)$
  (@prop:rkhs-feature-representation with the feature map $Phi(x) = x$). Since $K(x, x) = abs(x)^2$,
  $ abs(K)_p = (integral_(RR^d) abs(x)^p dif mu(x))^(1\/p) $
  is the $p$-th absolute moment of $mu$, and @thm:mercer-lp-embedding applies if and only if this moment is
  finite. Here the condition is also necessary: if all $f_w$ are in $cal(L)^p (mu)$, so are the coordinate
  functions, and then $abs(x)^p <= d^(p\/2) sum_i abs(x_i)^p$ is integrable.

  Let $abs(K)_2 < oo$ and let $Sigma := integral y y^top dif mu(y)$ be the second-moment matrix. Then
  $S_K g = f_(m_g)$ with $m_g = integral y g(y) dif mu(y)$, and $C_K f_w = S_K (iota f_w) = f_(Sigma w)$.
  So, under the isometry $w |-> f_w$, the covariance operator is the matrix $Sigma$, and by
  @prop:mercer-eigenfunctions (v) below the nonzero eigenvalues of $T_K$ are those of $Sigma$: kernel PCA
  with the linear kernel is ordinary (uncentered) PCA. The trace formula @eq:mercer-trace becomes $tr Sigma = integral abs(y)^2 dif mu(y)$.
] <ex:mercer-linear>

#example(title: [Empirical measures and Gram matrices])[
  Let $X$ be a separable metric space, $K$ a continuous positive definite kernel on $X$ (so the measurable
  setting holds), $x_1, ..., x_N in X$ pairwise distinct, and $mu = 1/N sum_(i=1)^N delta_(x_i)$ the empirical
  distribution of the inputs of a data set. Then $abs(K)_2^2 = 1/N sum_i K(x_i, x_i) < oo$. As in
  @ex:mercer-finite, $L^2(mu) tilde.equiv KK^N$ via $g |-> (g(x_1), ..., g(x_N))$, and
  $ S_K g = 1/N sum_(i=1)^N g(x_i) K_(x_i), quad (T_K g)(x_i) = 1/N sum_(l=1)^N K(x_i, x_l) g(x_l), $
  so $T_K$ is the matrix $1/N bold(K)$ with the Gram matrix $bold(K) = (K(x_i, x_l))_(i, l)$. Now, however,
  $X$ is much larger than the data. The range of $S_K$ is $spn{K_(x_1), ..., K_(x_N)}$, and by
  @thm:mercer-lp-embedding (v) its orthogonal complement is
  $Ker iota = {f in H_K : f(x_1) = ... = f(x_N) = 0}$. The orthogonal decomposition
  $H_K = spn{K_(x_i)} plus.o Ker iota$ is the geometric core of the representer theorem
  (@thm:reg-representer).
] <ex:mercer-empirical>

== Eigenfunctions of $T_K$ inside $H_K$ <sec:mercer-spectral>

We now combine the spectral theorem for $T_K$ with the fact that $T_K$ factors through $H_K$.
Throughout this section we are in the measurable setting of @sec:mercer-lp and assume
$abs(K)_2 < oo$. By @thm:mercer-integral-operator and the spectral theorem (@thm:app-spectral) there are
- an index set $J = {1, ..., m}$ with $m in NN_0$, or $J = NN$,
- numbers $lambda_1 >= lambda_2 >= ... > 0$, with $lambda_j -> 0$ if $J = NN$,
- and an orthonormal family $(e_j)_(j in J)$ in $L^2(mu)$ which is an orthonormal basis of
  $(Ker T_K)^perp = overline(Ran T_K)$,

such that
$ T_K g = sum_(j in J) lambda_j ip(g, e_j)_(L^2(mu)) e_j quad "for all" g in L^2(mu). $ <eq:mercer-TK-spectral>
The $lambda_j$ are the nonzero eigenvalues of $T_K$, repeated according to multiplicity. We call
$(lambda_j, e_j)_(j in J)$ an *eigensystem* of $T_K$. Within each (finite-dimensional) eigenspace the
orthonormal basis can be chosen arbitrarily; all statements below hold for every such choice.

The $e_j$ are elements of $L^2(mu)$, i.e. equivalence classes, and so far nothing tells us how to evaluate
them at a point. The factorization $T_K = iota S_K$ provides a canonical choice of representative.

#proposition(title: [Eigenfunctions in $H_K$])[
  In the measurable setting with $abs(K)_2 < oo$, let $(lambda_j, e_j)_(j in J)$ be an eigensystem of
  $T_K$ and define
  $ psi_j := 1/lambda_j S_K e_j in H_K, quad "i.e." quad psi_j (x) = 1/lambda_j integral_X K(x, y) e_j (y) dif mu(y), quad x in X. $
  Then:
  + $iota psi_j = e_j$, i.e. $psi_j$ is a representative of the class $e_j$.
  + $(sqrt(lambda_j) psi_j)_(j in J)$ is an orthonormal basis of the closed subspace
    $(Ker iota)^perp = overline(Ran S_K)$ of $H_K$.
  + For $g in L^2(mu)$, $S_K g = sum_(j in J) lambda_j ip(g, e_j)_(L^2(mu)) psi_j$ with convergence in $H_K$.
  + For $f in H_K$, let $P f$ be its orthogonal projection onto $(Ker iota)^perp$. Then
    $ ip(f, sqrt(lambda_j) psi_j)_(H_K) = 1/sqrt(lambda_j) ip(iota f, e_j)_(L^2(mu)), quad
      P f = sum_(j in J) ip(iota f, e_j)_(L^2(mu)) psi_j, quad
      norm(P f)_(H_K)^2 = sum_(j in J) abs(ip(iota f, e_j)_(L^2(mu)))^2 / lambda_j . $
  + The covariance operator $C_K = S_K S_K^*$ satisfies $C_K psi_j = lambda_j psi_j$ and $C_K = 0$ on
    $Ker iota$; thus $C_K$ and $T_K$ have the same nonzero eigenvalues with the same multiplicities.
] <prop:mercer-eigenfunctions>

#proof[
  (i) $iota psi_j = lambda_j^(-1) iota S_K e_j = lambda_j^(-1) T_K e_j = e_j$. The pointwise formula is
  @eq:mercer-S-pointwise.

  (ii) Orthonormality: for $j, k in J$, since $S_K^* = iota$ (@thm:mercer-integral-operator (i)),
  $ ip(sqrt(lambda_j) psi_j, sqrt(lambda_k) psi_k)_(H_K) = 1/sqrt(lambda_j lambda_k) ip(S_K e_j, S_K e_k)_(H_K)
    = 1/sqrt(lambda_j lambda_k) ip(T_K e_j, e_k)_(L^2(mu)) = lambda_j/sqrt(lambda_j lambda_k) delta_(j k) = delta_(j k) . $
  Completeness: by @prop:app-adjoint-kernel-range and $S_K^* = iota$,
  $overline(Ran S_K) = (Ker S_K^*)^perp = (Ker iota)^perp$. Each $psi_j$ lies in $Ran S_K$. Conversely, let
  $g in L^2(mu)$ and decompose $g = g_0 + sum_j ip(g, e_j) e_j$ with $g_0 in Ker T_K = Ker S_K$
  (@thm:mercer-integral-operator (iii)). Since $S_K$ is bounded, we may apply it term by term:
  $ S_K g = sum_(j in J) ip(g, e_j) S_K e_j = sum_(j in J) lambda_j ip(g, e_j) psi_j . $
  This proves (iii) and shows $Ran S_K subset.eq overline(spn){psi_j : j in J}$. Hence
  $overline(spn){psi_j} = overline(Ran S_K) = (Ker iota)^perp$, and the orthonormal family
  $(sqrt(lambda_j) psi_j)$ is an orthonormal basis of this space.

  (iv) By (i) of @thm:mercer-integral-operator,
  $ip(f, sqrt(lambda_j) psi_j)_(H_K) = lambda_j^(-1\/2) ip(f, S_K e_j)_(H_K) = lambda_j^(-1\/2) ip(iota f, e_j)_(L^2(mu))$.
  The other two formulas are the expansion of $P f$ in the orthonormal basis of (ii) and Parseval's
  identity.

  (v) $C_K psi_j = lambda_j^(-1) S_K iota S_K e_j = lambda_j^(-1) S_K T_K e_j = S_K e_j = lambda_j psi_j$, and
  $C_K f = S_K iota f = 0$ for $f in Ker iota$. Since $H_K = (Ker iota)^perp plus.o Ker iota$ and
  $(sqrt(lambda_j) psi_j)$ is an orthonormal basis of the first summand consisting of eigenvectors,
  $C_K = sum_j lambda_j ip(dot, sqrt(lambda_j) psi_j) sqrt(lambda_j) psi_j$, which has exactly the nonzero
  eigenvalues $lambda_j$ with the same multiplicities.
]

#warning-block[
  It is tempting to say "$e_j = psi_j$, hence $e_j in H_K$". This is correct only in the sense
  $iota psi_j = e_j$. A class in $L^2(mu)$ has many representatives, most of which are not in $H_K$, and
  different elements of $H_K$ may represent the same class (whenever $Ker iota != {0}$). The function
  $psi_j = lambda_j^(-1) S_K e_j$ is the _canonical_ representative singled out by the kernel. Without
  further assumptions it is the only one we know how to evaluate pointwise.
]

The next result expands the kernel itself in the eigenfunctions. In the measurable setting we can only
expect such an expansion to hold almost everywhere. Compare this with Mercer's theorem below, where
continuity and full support upgrade it to uniform convergence everywhere.

#proposition(title: [Eigen-expansion of the kernel])[
  In the measurable setting with $abs(K)_2 < oo$, let $(lambda_j, e_j)_(j in J)$ be an eigensystem of $T_K$
  and $psi_j$ as in @prop:mercer-eigenfunctions. Then:
  + $sum_(j in J) lambda_j abs(psi_j (x))^2 <= K(x, x)$ for every $x in X$, and consequently
    $ sum_(j in J) lambda_j abs(psi_j (x)) abs(psi_j (y)) <= sqrt(K(x, x) K(y, y)), quad x, y in X . $
  + There is a $mu$-null set $cal(N) in cal(A)$ such that for every $x in X without cal(N)$
    $ K_x = sum_(j in J) lambda_j overline(psi_j (x)) psi_j quad "in" H_K, $
    and hence $K(y, x) = sum_(j in J) lambda_j psi_j (y) overline(psi_j (x))$ for all $y in X$ and
    $K(x, x) = sum_(j in J) lambda_j abs(psi_j (x))^2$. If $iota$ is injective, one can take $cal(N) = emptyset$.
  + $sum_(j in J) lambda_j e_j times.o overline(e_j) = K$ in $L^2(mu times.o mu)$, where
    $(e_j times.o overline(e_j))(x, y) := psi_j (x) overline(psi_j (y))$. Moreover
    $ norm(T_K)_("HS")^2 = sum_(j in J) lambda_j^2 = integral_X integral_X abs(K(x, y))^2 dif mu(x) dif mu(y) . $
] <prop:mercer-ae-expansion>

#proof[
  Write $u_j := sqrt(lambda_j) psi_j$; by @prop:mercer-eigenfunctions, $(u_j)_(j in J)$ is an orthonormal
  basis of $(Ker iota)^perp$. For every $x in X$ the reproducing property gives
  $ip(K_x, u_j)_(H_K) = overline(u_j (x)) = sqrt(lambda_j) overline(psi_j (x))$.

  (i) Bessel's inequality in $H_K$ gives
  $sum_j lambda_j abs(psi_j (x))^2 = sum_j abs(ip(K_x, u_j))^2 <= norm(K_x)_(H_K)^2 = K(x, x)$. The second
  inequality follows from this and the Cauchy–Schwarz inequality in $ell^2(J)$.

  (ii) The closed subspace $Ker iota$ of the separable space $H_K$ is separable; let ${h_m : m in NN}$ be a
  dense subset. Each $h_m$ vanishes outside the $mu$-null set $cal(N)_m := {h_m != 0} in cal(A)$. Let
  $cal(N) := union.big_m cal(N)_m$, a $mu$-null set. For $x in.not cal(N)$ we have
  $ip(h_m, K_x)_(H_K) = h_m (x) = 0$ for all $m$, and by density and continuity of the inner product,
  $K_x perp Ker iota$. Hence $K_x in (Ker iota)^perp$ and
  $ K_x = sum_(j in J) ip(K_x, u_j) u_j = sum_(j in J) lambda_j overline(psi_j (x)) psi_j $
  with convergence in $H_K$. Norm convergence in an RKHS implies pointwise convergence
  (@prop:rkhs-norm-convergence), so $K(y, x) = K_x (y) = sum_j lambda_j psi_j (y) overline(psi_j (x))$ for all
  $y$, and Parseval's identity gives $K(x, x) = norm(K_x)^2 = sum_j lambda_j abs(psi_j (x))^2$. If $iota$ is
  injective, then $Ker iota = {0}$ and we may take $cal(N) = emptyset$.

  (iii) For $n in NN$ let $k_n (x, y) := sum_(j in J, j <= n) lambda_j psi_j (x) overline(psi_j (y))$, which is
  $cal(A) times.o cal(A)$-measurable. Renaming the variables in (ii), for $y in.not cal(N)$ and all $x in X$,
  $ K(x, y) = sum_(j in J) lambda_j psi_j (x) overline(psi_j (y)) = lim_(n -> oo) k_n (x, y) . $
  Thus $k_n -> K$ pointwise outside $X times cal(N)$, a $(mu times.o mu)$-null set. By (i) and
  @prop:rkhs-kernel-properties, $abs(k_n (x, y)) <= G(x, y)$ and $abs(K(x, y)) <= G(x, y)$ with
  $G(x, y) := sqrt(K(x, x) K(y, y))$, and by Tonelli's theorem (@thm:app-fubini)
  $integral.double G^2 dif (mu times.o mu) = (integral K(x, x) dif mu(x))^2 = abs(K)_2^4 < oo$. Since
  $abs(k_n - K)^2 <= 4 G^2$, the dominated convergence theorem (@thm:app-convergence) yields $k_n -> K$
  in $L^2(mu times.o mu)$.

  The family $(e_j times.o overline(e_j))_(j in J)$ is orthonormal in $L^2(mu times.o mu)$: by Fubini's
  theorem (@thm:app-fubini),
  $ ip(e_j times.o overline(e_j), e_k times.o overline(e_k))_(L^2(mu times.o mu))
    = integral e_j overline(e_k) dif mu dot integral overline(e_j) e_k dif mu = delta_(j k) delta_(j k) = delta_(j k) . $
  Hence $norm(K)_(L^2(mu times.o mu))^2 = lim_n norm(k_n)^2 = lim_n sum_(j <= n) lambda_j^2 = sum_j lambda_j^2$.
  Finally, $T_K$ is trace class, so $sum_j lambda_j^2 <= lambda_1 sum_j lambda_j < oo$, and by
  @thm:app-spectral (iv) $T_K$ is Hilbert–Schmidt with $norm(T_K)_("HS")^2 = sum_j lambda_j^2$. (Directly:
  compute the Hilbert–Schmidt norm in the orthonormal basis $(e_j)_(j in J) union E_0$ of $L^2(mu)$, where
  $E_0$ is an orthonormal basis of $Ker T_K$.)
]

Integrating the identity $K(x, x) = sum_j lambda_j abs(psi_j (x))^2$, valid for $mu$-almost every $x$, and
using $integral abs(psi_j)^2 dif mu = norm(e_j)^2 = 1$ and monotone convergence gives a second proof of the
trace formula @eq:mercer-trace.

#example(title: [Empirical measures, continued: the Nyström extension])[
  In the situation of @ex:mercer-empirical, an eigensystem of $T_K$ consists of the eigenvectors $e_j$ of
  $1/N bold(K)$, normalized by $1/N sum_i abs(e_j (x_i))^2 = 1$, with eigenvalues $lambda_j > 0$. They are
  defined only on the data points. @prop:mercer-eigenfunctions extends them to all of $X$:
  $ psi_j (x) = 1/(N lambda_j) sum_(i=1)^N K(x, x_i) e_j (x_i), quad x in X . $
  This is the *Nyström extension* used to evaluate kernel principal components at new points and to
  build low-rank approximations of large Gram matrices @williams2001; it
  interpolates, $psi_j (x_i) = e_j (x_i)$. By @prop:mercer-eigenfunctions (ii), the functions
  $sqrt(lambda_j) psi_j$ form an orthonormal basis of $spn{K_(x_1), ..., K_(x_N)}$. By
  @prop:mercer-ae-expansion (ii), the expansion $K(y, x) = sum_j lambda_j psi_j (y) overline(psi_j (x))$
  holds for every $y in X$ as long as $x$ is one of the data points ($cal(N) = X without {x_1, ..., x_N}$).
  In general it fails for other $x$. For instance, if $K$ is strictly positive definite and
  $x in.not {x_1, ..., x_N}$, then $K_x in.not spn{K_(x_i)}$ (kernel sections at distinct points are
  linearly independent), so $K_x$ differs from its projection onto $spn{K_(x_i)}$, and
  $sum_j lambda_j abs(psi_j (x))^2 < norm(K_x)^2 = K(x, x)$.
] <ex:mercer-nystrom>

The example shows that the null set $cal(N)$ of @prop:mercer-ae-expansion is essential. The eigenfunctions only
know about the part of $X$ that $mu$ sees. To obtain an expansion valid _everywhere_, we need a measure
that sees all of $X$, and enough continuity to pass from "almost everywhere" to "everywhere". This is
exactly what Mercer's theorem assumes.

== Mercer's theorem <sec:mercer-theorem>

*The Mercer setting.* Throughout this section:
- $(X, d)$ is a compact metric space with its Borel $sigma$-algebra $borel(X)$;
- $mu$ is a finite Borel measure on $X$ with $supp mu = X$;
- $K: X times X -> KK$ is a continuous positive definite kernel.

Typical examples are $X = [a, b]$ or a compact subset of $RR^d$ with the Lebesgue measure (restricted to a
compact set that is the closure of its interior), the torus or the sphere with their uniform measures, or
any compact $X$ with a probability measure of full support.

#lemma[
  In the Mercer setting:
  + $K$ is bounded, $H_K subset.eq C(X)$, the measurable setting of @sec:mercer-lp holds, and
    $abs(K)_p <= mu(X)^(1\/p) abs(K)_oo < oo$ for every $1 <= p < oo$. In particular all results of
    @sec:mercer-lp – @sec:mercer-spectral apply.
  + The inclusions $iota_p: H_K -> L^p (mu)$ are injective.
  + Let $(lambda_j, e_j)_(j in J)$ be an eigensystem of $T_K$. Each class $e_j$ has exactly one continuous
    representative, namely $psi_j = lambda_j^(-1) S_K e_j in H_K$, and $(sqrt(lambda_j) psi_j)_(j in J)$ is an
    orthonormal basis of $H_K$.
] <lem:mercer-setting>

#proof[
  (i) A continuous function on the compact space $X times X$ is bounded, so $abs(K)_oo < oo$, and each
  $K_x$ is continuous. By @prop:rkhs-continuous, $H_K subset.eq C_b (X) = C(X)$. Each $K_x$ is Borel
  measurable, which is (M1). A compact metric space is separable, so $H_K$ is separable by
  @prop:rkhs-separable, which is (M2). Finally
  $abs(K)_p^p = integral K(x, x)^(p\/2) dif mu(x) <= mu(X) abs(K)_oo^p$.

  (ii) If $f in H_K$ and $iota_p f = 0$, then $f$ is a continuous function vanishing $mu$-almost everywhere,
  hence $f = 0$ by @prop:mercer-support.

  (iii) By @prop:mercer-eigenfunctions (i), $psi_j in H_K subset.eq C(X)$ represents $e_j$; any other
  continuous representative coincides with $psi_j$ by @prop:mercer-support. By (ii), $Ker iota = {0}$, so
  @prop:mercer-eigenfunctions (ii) says that $(sqrt(lambda_j) psi_j)$ is an orthonormal basis of all of
  $H_K$.
]

*Convention.* In the Mercer setting we always choose the continuous representative, and we denote it by
the same letter: $e_j := psi_j in H_K subset.eq C(X)$. Thus
$ e_j (x) = 1/lambda_j integral_X K(x, y) e_j (y) dif mu(y) quad "for every" x in X, $
and the eigenvalue equation $T_K e_j = lambda_j e_j$ now holds pointwise.

#theorem(title: [Mercer])[
  Let $(X, d)$ be a compact metric space, $mu$ a finite Borel measure on $X$ with $supp mu = X$, and
  $K: X times X -> KK$ a continuous positive definite kernel. Let $(lambda_j, e_j)_(j in J)$ be an eigensystem
  of the integral operator $T_K: L^2(mu) -> L^2(mu)$, $(T_K g)(x) = integral_X K(x, y) g(y) dif mu(y)$, with
  each $e_j$ chosen continuous. Then:
  + For all $x, y in X$,
    $ K(x, y) = sum_(j in J) lambda_j e_j (x) overline(e_j (y)), $ <eq:mercer-expansion>
    where the series converges absolutely and uniformly on $X times X$. That is,
    $sup_(x, y in X) sum_(j > n) lambda_j abs(e_j (x)) abs(e_j (y)) -> 0$ as $n -> oo$ if $J = NN$.
  + In particular, $K(x, x) = sum_(j in J) lambda_j abs(e_j (x))^2$ uniformly in $x in X$, and
    $sqrt(lambda_j) norm(e_j)_oo <= abs(K)_oo$ for all $j in J$.
  + $T_K$ is trace class with $tr T_K = sum_(j in J) lambda_j = integral_X K(x, x) dif mu(x)$.
] <thm:mercer>

The idea of the proof: since $iota$ is injective, the rescaled eigenfunctions form an orthonormal basis of
$H_K$, so expanding the kernel section $K_x$ in this basis gives @eq:mercer-expansion _pointwise_, with
no exceptional set. Uniformity then follows on the diagonal from Dini's theorem, and off the diagonal from
the Cauchy–Schwarz inequality.

#proof[
  If $J$ is finite, all series are finite sums, and step 1 below already proves everything; so let
  $J = NN$.

  _Step 1: pointwise expansion._ By @lem:mercer-setting (iii), $(sqrt(lambda_j) e_j)_j$ is an orthonormal
  basis of all of $H_K$, and $ip(K_x, sqrt(lambda_j) e_j)_(H_K) = sqrt(lambda_j) overline(e_j (x))$. Hence
  $K_x = sum_j lambda_j overline(e_j (x)) e_j$ in $H_K$ for _every_ $x in X$ (this is
  @prop:mercer-ae-expansion (ii) with $cal(N) = emptyset$). Evaluating at $y$
  (@prop:rkhs-norm-convergence) and taking norms (Parseval) gives, for all $x, y in X$,
  $ K(y, x) = sum_(j = 1)^oo lambda_j e_j (y) overline(e_j (x)) quad "and" quad K(x, x) = sum_(j=1)^oo lambda_j abs(e_j (x))^2 , $
  and renaming $x <-> y$ gives @eq:mercer-expansion pointwise.

  _Step 2: uniform convergence on the diagonal._ (This is the argument of @cor:rkhs-onb-expansion, applied
  to the orthonormal basis $(sqrt(lambda_j) e_j)$.) The functions
  $s_n (x) := sum_(j=1)^n lambda_j abs(e_j (x))^2$ are continuous, nondecreasing in $n$, and converge
  pointwise to the continuous function $x |-> K(x, x)$ by step 1. Since $X$ is compact, Dini's theorem
  (@thm:app-dini) shows that the convergence is uniform:
  $ r_n := sup_(x in X) sum_(j > n) lambda_j abs(e_j (x))^2 = sup_(x in X) (K(x, x) - s_n (x)) -> 0 quad (n -> oo) . $

  _Step 3: absolute and uniform convergence on $X times X$._ For $x, y in X$, the Cauchy–Schwarz
  inequality in $ell^2$ gives
  $ sum_(j > n) lambda_j abs(e_j (x)) abs(e_j (y))
    <= (sum_(j > n) lambda_j abs(e_j (x))^2)^(1\/2) (sum_(j > n) lambda_j abs(e_j (y))^2)^(1\/2)
    <= r_n . $
  Hence $sup_(x, y) sum_(j > n) lambda_j abs(e_j (x)) abs(e_j (y)) <= r_n -> 0$: the series
  @eq:mercer-expansion converges absolutely and uniformly on $X times X$, and by step 1 its sum is
  $K(x, y)$. This proves (i).

  _Step 4: consequences._ The uniform convergence on the diagonal is step 2. From step 1,
  $lambda_j abs(e_j (x))^2 <= K(x, x) <= abs(K)_oo^2$ for all $x$, which gives the bound on
  $norm(e_j)_oo$. Part (iii) is @thm:mercer-integral-operator (iv); alternatively, integrate the
  uniformly convergent series $K(x, x) = sum_j lambda_j abs(e_j (x))^2$ over the finite measure $mu$ and use
  $integral abs(e_j)^2 dif mu = 1$.
]

Mercer's theorem says that a continuous positive definite kernel is an infinite-dimensional version of
the matrix identity $bold(K) = sum_j lambda_j bold(e)_j bold(e)_j^*$ from @ex:mercer-finite, with
convergence as good as one could wish. Truncating the series gives kernels
$K^((n)) (x, y) = sum_(j <= n) lambda_j e_j (x) overline(e_j (y))$ of finite rank with
$norm(K - K^((n)))_oo -> 0$: every continuous positive definite kernel is uniformly approximable by
finite-rank ones built from its own eigenfunctions.

=== Discussion of the hypotheses

*Full support.* Without $supp mu = X$ the theorem fails, even for very nice kernels. In
@ex:mercer-noninjective ($X = [0, 2]$, $mu$ the Lebesgue measure on $[0, 1]$, $K(x, y) = f_0 (x) f_0 (y)$
with $f_0 = 0$ on $[0, 1]$) we have $T_K = 0$. There are no eigenpairs, the right-hand side of
@eq:mercer-expansion is the empty sum $0$, but $K(2, 2) = 1$. The measure simply does not see the part of
$X$ where the kernel lives. What remains true is the almost-everywhere statement of
@prop:mercer-ae-expansion, and, by applying @thm:mercer to the restriction of $K$ to the compact set
$supp mu$, uniform convergence on $supp mu times supp mu$ (@ex:mercer-exercise-support).

*Positivity.* Mercer's original theorem @mercer1909 is often stated for continuous _Hermitian_ kernels
$A$ whose integral operator is positive, i.e. has no negative eigenvalues. This is the same class of
kernels. The following lemma shows that positivity of the integral operator ("Mercer's condition") and
positive definiteness in the sense of @def:rkhs-pd are equivalent for continuous kernels, provided the
measure has full support.

#lemma(title: [Mercer's condition])[
  Let $(X, d)$ be a compact metric space, $mu$ a finite Borel measure on $X$ with $supp mu = X$, and
  $A: X times X -> KK$ continuous and Hermitian, $A(y, x) = overline(A(x, y))$. Let
  $(T_A g)(x) := integral_X A(x, y) g(y) dif mu(y)$ for $g in L^2(mu)$. Then the following are equivalent:
  + $A$ is positive definite;
  + $ip(T_A g, g)_(L^2(mu)) = integral_X integral_X A(x, y) g(y) overline(g(x)) dif mu(y) dif mu(x) >= 0$ for all
    $g in L^2(mu)$.
] <lem:mercer-positivity>

#proof[
  Note that $T_A$ is a bounded operator on $L^2(mu)$, since
  $abs((T_A g)(x)) <= norm(A)_oo mu(X)^(1\/2) norm(g)_(L^2(mu))$ by the Cauchy–Schwarz inequality.

  (i) $=>$ (ii): A continuous Hermitian positive definite kernel is the reproducing kernel of its RKHS
  $H_A$ (@thm:rkhs-moore-aronszajn), the Mercer setting holds, and $T_A = S_A^* S_A$ is positive by
  @thm:mercer-integral-operator (iii).

  (ii) $=>$ (i): Let $x_1, ..., x_n in X$ and $c in KK^n$; we must show
  $Q := sum_(i,l) overline(c_i) c_l A(x_i, x_l) >= 0$. For $delta > 0$ let $B_i := {x : d(x, x_i) < delta}$.
  Since $supp mu = X$, $mu(B_i) > 0$, and we may define
  $ g_delta := sum_(i=1)^n c_i / mu(B_i) ind_(B_i) in L^2(mu) . $
  Then
  $ ip(T_A g_delta, g_delta)_(L^2(mu)) = sum_(i, l = 1)^n overline(c_i) c_l a_(i l)(delta), quad
    a_(i l)(delta) := 1/(mu(B_i) mu(B_l)) integral_(B_i) integral_(B_l) A(x, y) dif mu(y) dif mu(x) . $
  The number $a_(i l)(delta)$ is an average of $A$ over $B_i times B_l$, so
  $abs(a_(i l)(delta) - A(x_i, x_l)) <= sup{abs(A(x, y) - A(x_i, x_l)) : d(x, x_i) < delta, d(y, x_l) < delta}$,
  which tends to $0$ as $delta -> 0$ by continuity of $A$. Hence
  $Q = lim_(delta -> 0) ip(T_A g_delta, g_delta) >= 0$.
]

Consequently, for a continuous Hermitian kernel $A$ and $mu$ of full support, "the integral operator
$T_A$ has only nonnegative eigenvalues" is equivalent to "$A$ is positive definite". For compact
self-adjoint operators, positivity is equivalent to nonnegativity of all eigenvalues, by the spectral
theorem. Mercer's theorem is therefore often summarized as: _a continuous Hermitian kernel with a
positive integral operator has an absolutely and uniformly convergent eigen-expansion._

#remark(title: [Indefinite kernels])[
  Let $(X, d)$ be compact metric, $mu$ a finite Borel measure (full support is not needed here), and
  $A: X times X -> KK$ continuous and Hermitian, but not necessarily positive definite. Then $T_A$ is still
  compact and self-adjoint. It has an eigensystem $(lambda_j, e_j)_(j in J)$ with real $lambda_j != 0$,
  ordered by $abs(lambda_1) >= abs(lambda_2) >= ...$, and
  $ A = sum_(j in J) lambda_j e_j times.o overline(e_j) quad "in" L^2(mu times.o mu) . $
  However, the convergence need not be absolute or uniform.

  _Proof of the $L^2$-statement._ Since $A$ is bounded and $mu$ finite, $A in L^2(mu times.o mu)$, so $T_A$
  is a Hilbert–Schmidt operator, hence compact, and it is self-adjoint because $A$ is Hermitian
  (@prop:app-integral-operators). The spectral theorem (@thm:app-spectral) provides the eigensystem; the
  $e_j = lambda_j^(-1) T_A e_j$ have continuous representatives, since $T_A$ maps $L^2(mu)$ into $C(X)$ by
  uniform continuity of $A$. The family
  $(e_j times.o overline(e_j))_j$ is orthonormal in $L^2(mu times.o mu)$ (as in the proof of
  @prop:mercer-ae-expansion), and
  $ ip(A, e_j times.o overline(e_j))_(L^2(mu times.o mu)) = integral_X integral_X A(x, y) overline(e_j (x)) e_j (y) dif mu(y) dif mu(x) = ip(T_A e_j, e_j) = lambda_j . $
  By Bessel's inequality $sum_j lambda_j^2 <= norm(A)_(L^2(mu times.o mu))^2 < oo$, so
  $G := sum_j lambda_j e_j times.o overline(e_j)$ converges in $L^2(mu times.o mu)$. For $f, g in L^2(mu)$,
  using the spectral decomposition of $T_A$,
  $ ip(A, g times.o overline(f)) = ip(T_A f, g) = sum_j lambda_j ip(f, e_j) ip(e_j, g) = ip(G, g times.o overline(f)) . $
  The linear span of the functions $g times.o overline(f)$, $f, g in C(X)$, is dense in $C(X times X)$ by
  the Stone–Weierstrass theorem (@thm:app-stone-weierstrass: it is a conjugation-closed subalgebra that
  contains the constants and separates points), and $C(X times X)$ is dense in $L^2(mu times.o mu)$
  @rudin1987[Thm. 3.14]. Hence $A - G = 0$ in $L^2(mu times.o mu)$.

  _Failure of absolute convergence._ On $X = TT = RR \/ 2 pi ZZ$ with $mu = dif x \/ (2 pi)$ there is a
  continuous function whose Fourier series diverges at $0$ @rudin1987[Ch. 5]. Taking real or
  imaginary part and symmetrizing, we obtain a real, even, continuous $h$ whose symmetric Fourier partial
  sums at $0$, $sum_(abs(k) <= n) hat(h)(k)$, are unbounded; in particular
  $sum_k abs(hat(h)(k)) = oo$. The kernel $A(x, y) := h(x - y)$ is continuous and Hermitian, and
  $T_A e_k = hat(h)(k) e_k$ for $e_k (x) := e^(i k x)$ (see the proof of @prop:mercer-torus-bochner). So
  the nonzero eigenvalues are the real numbers $hat(h)(k) != 0$ with eigenfunctions $e_k$, and on the
  diagonal
  $ sum_k abs(hat(h)(k)) abs(e_k (x))^2 = sum_k abs(hat(h)(k)) = oo $
  for every $x$: the eigen-expansion does not converge absolutely at any point of the diagonal, and $T_A$
  is not trace class. Positivity is thus exactly what makes Mercer's theorem work.
] <rem:mercer-indefinite>

#remark(title: [The Mercer feature map])[
  In the Mercer setting,
  $ Phi_M: X -> ell^2(J), quad Phi_M (x) := (sqrt(lambda_j) overline(e_j (x)))_(j in J), $
  is a feature map for $K$ in the sense of @def:rkhs-feature-map, since by @eq:mercer-expansion
  $ ip(Phi_M (y), Phi_M (x))_(ell^2) = sum_(j in J) lambda_j e_j (x) overline(e_j (y)) = K(x, y) . $
  The associated functions are $ip(w, Phi_M (dot))_(ell^2) = sum_j w_j sqrt(lambda_j) e_j$, so
  @prop:rkhs-feature-representation gives another route to the spectral picture of the next section. In
  the early SVM literature the existence of this feature map, guaranteed by Mercer's theorem, was the
  standard justification of the kernel trick, and continuous positive definite kernels are therefore
  often called *Mercer kernels* @vapnik1998 @cortes1995 @schoelkopf2002. As @sec:rkhs shows, the kernel
  trick needs neither compactness nor continuity: every positive definite kernel has the canonical feature
  map $Phi_K$.
] <rem:mercer-feature-map>

== The spectral picture of $H_K$ <sec:mercer-picture>

We can now answer the question from the beginning of the chapter: what are the functions in $H_K$, and
what does their norm measure? For $f in L^2(mu)$ we call $ip(f, e_j)_(L^2(mu))$ its *generalized Fourier
coefficients* with respect to the eigensystem. Recall that $T_K$ has a positive square root
(@thm:app-spectral (iii)),
$ T_K^(1\/2) g = sum_(j in J) sqrt(lambda_j) ip(g, e_j)_(L^2(mu)) e_j, quad g in L^2(mu) . $

#proposition(title: [Spectral picture of $H_K$])[
  Let $(X, d)$ be a compact metric space, $mu$ a finite Borel measure with $supp mu = X$, $K$ a continuous
  positive definite kernel on $X$, and $(lambda_j, e_j)_(j in J)$ an eigensystem of $T_K$ with continuous
  $e_j$. Then:
  + *(Coefficient description.)* For every $a = (a_j) in ell^2(J)$ the series
    $ f_a := sum_(j in J) a_j sqrt(lambda_j) e_j $
    converges in $H_K$ and absolutely and uniformly on $X$, and $a |-> f_a$ is an isometric isomorphism
    $ell^2(J) -> H_K$. Thus
    $ H_K = {sum_(j in J) a_j sqrt(lambda_j) e_j : (a_j) in ell^2(J)}, quad
      ip(f_a, f_b)_(H_K) = sum_(j in J) a_j overline(b_j), $
    and the coefficients of $f in H_K$ are
    $a_j = ip(f, sqrt(lambda_j) e_j)_(H_K) = lambda_j^(-1\/2) ip(f, e_j)_(L^2(mu))$.
  + *(Description inside $L^2$.)* A continuous function $f: X -> KK$ belongs to $H_K$ if and only if
    $[f] perp Ker T_K$ in $L^2(mu)$ and $sum_(j in J) abs(ip(f, e_j)_(L^2(mu)))^2 \/ lambda_j < oo$. In this case
    $ norm(f)_(H_K)^2 = sum_(j in J) abs(ip(f, e_j)_(L^2(mu)))^2 / lambda_j . $ <eq:mercer-norm>
    Equivalently,
    $ iota(H_K) = {g in L^2(mu) : g perp Ker T_K, space sum_(j in J) abs(ip(g, e_j)_(L^2(mu)))^2 / lambda_j < oo}, $
    and every class in this set has exactly one continuous representative, which lies in $H_K$.
  + *(Square root.)* $Ker T_K^(1\/2) = Ker T_K$, $Ran T_K^(1\/2) = iota(H_K)$, and
    $ V := iota^(-1) compose T_K^(1\/2)|_((Ker T_K)^perp) : (Ker T_K)^perp -> H_K $
    is an isometric isomorphism. For $g in L^2(mu)$, the uniformly convergent series
    $sum_j sqrt(lambda_j) ip(g, e_j) e_j$ is the unique continuous representative of $T_K^(1\/2) g$; for
    $g perp Ker T_K$ it equals $V g$. Moreover $S_K = V T_K^(1\/2)$.
  + *(Dimension.)* $dim H_K = abs(J)$. In particular, $H_K$ is finite-dimensional if and only if $T_K$ has
    finite rank $m$, and then $H_K = spn{e_1, ..., e_m}$.
  + *(Density.)* $iota(H_K)$ is dense in $L^2(mu)$ if and only if $Ker T_K = {0}$, i.e. if and only if
    $(e_j)_(j in J)$ is an orthonormal basis of $L^2(mu)$.
] <prop:mercer-rkhs-spectral>

#proof[
  Write $u_j := sqrt(lambda_j) e_j$. By @lem:mercer-setting (iii), $(u_j)_(j in J)$ is an orthonormal basis
  of $H_K$.

  (i) In a Hilbert space with orthonormal basis $(u_j)$, the map $a |-> sum_j a_j u_j$ is an isometric
  isomorphism from $ell^2(J)$ onto the space, with inverse $f |-> (ip(f, u_j))_j$. The formula for
  $ip(f, u_j)_(H_K)$ is @prop:mercer-eigenfunctions (iv). For uniform convergence, by the Cauchy–Schwarz
  inequality and @thm:mercer (ii),
  $ sum_(j > n) abs(a_j) sqrt(lambda_j) abs(e_j (x)) <= (sum_(j > n) abs(a_j)^2)^(1\/2) (sum_(j in J) lambda_j abs(e_j (x))^2)^(1\/2)
    <= (sum_(j > n) abs(a_j)^2)^(1\/2) abs(K)_oo, $
  which tends to $0$ uniformly in $x$. (Alternatively: norm convergence in $H_K$ implies uniform convergence
  because $K$ is bounded, @prop:rkhs-norm-convergence.)

  (ii) Let $f in H_K$. Then $iota f in Ran iota = Ran S_K^* subset.eq overline(Ran S_K^*) = (Ker S_K)^perp = (Ker T_K)^perp$
  (@prop:app-adjoint-kernel-range and @thm:mercer-integral-operator (iii)), and
  $sum_j abs(ip(f, e_j)_(L^2))^2 \/ lambda_j = sum_j abs(ip(f, u_j)_(H_K))^2 = norm(f)_(H_K)^2 < oo$ by (i) and
  Parseval. Conversely, let $g in L^2(mu)$ with $g perp Ker T_K$ and
  $sum_j abs(ip(g, e_j))^2 \/ lambda_j < oo$. Then $a_j := lambda_j^(-1\/2) ip(g, e_j)$ defines $a in ell^2(J)$,
  and since $iota$ is bounded and $(e_j)$ is an orthonormal basis of $(Ker T_K)^perp$,
  $ iota f_a = sum_j a_j sqrt(lambda_j) e_j = sum_j ip(g, e_j) e_j = g . $
  So $f_a in H_K$ is a continuous representative of $g$, and by @prop:mercer-support it is the only one.
  Applied to $g = [f]$ for a continuous $f$ with the two properties, this shows $f = f_a in H_K$.

  (iii) $T_K^(1\/2) g = 0$ if and only if $ip(g, e_j) = 0$ for all $j$ (as $sqrt(lambda_j) > 0$), i.e. if and
  only if $g perp overline(spn){e_j} = (Ker T_K)^perp$, i.e. $g in Ker T_K$. Let $g in L^2(mu)$ and
  $a_j := ip(g, e_j)$, so $a in ell^2(J)$ by Bessel's inequality. Then
  $iota f_a = sum_j a_j sqrt(lambda_j) e_j = T_K^(1\/2) g$, so $T_K^(1\/2) g in iota(H_K)$ with the continuous
  representative $f_a = sum_j sqrt(lambda_j) ip(g, e_j) e_j$. Hence $Ran T_K^(1\/2) subset.eq iota(H_K)$, and
  $ norm(V g)_(H_K) = norm(f_a)_(H_K) = norm(a)_(ell^2) = norm(g)_(L^2(mu)) quad "for" g in (Ker T_K)^perp . $
  Conversely, for $f_b in H_K$ with $b in ell^2(J)$, the element $g := sum_j b_j e_j in (Ker T_K)^perp$ satisfies
  $V g = f_b$. So $V$ is surjective and $Ran T_K^(1\/2) = iota(H_K)$. Finally, by
  @prop:mercer-eigenfunctions (iii),
  $S_K g = sum_j lambda_j ip(g, e_j) e_j = sum_j (sqrt(lambda_j) ip(g, e_j)) sqrt(lambda_j) e_j = V(T_K^(1\/2) g)$.

  (iv) By (i), $H_K$ is isometric to $ell^2(J)$, whose dimension is $abs(J)$; the number of nonzero eigenvalues
  counted with multiplicity is the rank of $T_K$.

  (v) By @thm:mercer-lp-embedding (iv), $iota(H_K)$ is dense if and only if $S_K$ is injective, and
  $Ker S_K = Ker T_K$. The second equivalence holds because $(e_j)$ is an orthonormal basis of
  $(Ker T_K)^perp$.
]

Several remarks are in order.

*Functions versus classes.* Part (ii) is the precise version of the often-quoted formula
$H_K = {f in L^2(mu) : sum_j abs(ip(f, e_j))^2 \/ lambda_j < oo}$. That formula is correct only if
$Ker T_K = {0}$ and if "$f in L^2(mu)$" is read as "the continuous representative of a class". If
$Ker T_K != {0}$, every nonzero $g in Ker T_K$ has all coefficients $ip(g, e_j) = 0$, so the series is $0$,
but $g in.not iota(H_K)$. The condition $g perp Ker T_K$ cannot be dropped.

*A smoothness space.* Since $lambda_j -> 0$, the condition $sum_j abs(ip(f, e_j))^2 \/ lambda_j < oo$ is much
stronger than $sum_j abs(ip(f, e_j))^2 < oo$: the coefficients must decay faster than $sqrt(lambda_j)$. The
faster the eigenvalues decay, the smaller $H_K$ is. When the $e_j$ with small $lambda_j$ are the
oscillating ones, as in all examples of @sec:mercer-examples, faster decay means smoother functions. On the
torus this is literally the Sobolev scale (@ex:mercer-torus). In the language of @ex:mercer-finite: $H_K$
contains the functions whose energy along "high frequencies" is small, and $norm(f)_(H_K)$ measures that
energy, each frequency weighted by $1\/lambda_j$.

*Band-limited functions.* If only finitely many eigenvalues are positive, $H_K = spn{e_1, ..., e_m}$ is
finite-dimensional. In signal processing, functions with only finitely many active frequencies are called
band-limited; the kernel $K(x, y) = sum_(j=1)^m lambda_j e_j (x) overline(e_j (y))$ is then a "band-limited
kernel". The polynomial kernels of @ex:rkhs-kernels are of this type, and on an infinite compact set $X$
such kernels can never be universal in the sense of @sec:univ, since a finite-dimensional subspace of
$C(X)$ is closed and hence not dense.

*Isometry and polar decomposition.* By (iii), the square root $T_K^(1\/2)$ maps the unit ball of
$(Ker T_K)^perp$ onto the unit ball of $H_K$ (viewed inside $L^2$). The factorization $S_K = V T_K^(1\/2)$ is
the polar decomposition of $S_K$: $abs(S_K) = (S_K^* S_K)^(1\/2) = T_K^(1\/2)$, and $V$ is a partial isometry,
here unitary from $(Ker T_K)^perp$ onto $H_K$.

The spectral picture makes the effect of regularization completely transparent in the simplest case, the
least squares loss.

#example(title: [Regularization as a spectral filter])[
  Let $KK = RR$ and let $P$ be a distribution on $X times Y$ with $integral y^2 dif P(x, y) < oo$, where $X$,
  $K$ and $mu := P_X$ satisfy the assumptions of @prop:mercer-rkhs-spectral. By @ex:learn-least-squares and
  @eq:learn-ls-decomposition, the least squares risk is
  $risk(L, P)(f) = norm(f - f_P)_(L^2(P_X))^2 + sigma_P^2$, where $f_P in L^2(P_X)$ is the regression
  function. Write $b_j := ip(f_P, e_j)_(L^2(mu))$ and let $f_P^0$ be the orthogonal projection of $f_P$ onto
  $Ker T_K$. For $f = f_a in H_K$, $iota f = sum_j sqrt(lambda_j) a_j e_j in (Ker T_K)^perp$, so by
  Pythagoras
  $ risk(L, P)(f_a) + lambda norm(f_a)_(H_K)^2 = sigma_P^2 + norm(f_P^0)_(L^2)^2 + sum_(j in J) (abs(sqrt(lambda_j) a_j - b_j)^2 + lambda abs(a_j)^2) . $
  Completing the square, for $a, b in RR$,
  $ abs(sqrt(lambda_j) a - b)^2 + lambda abs(a)^2 = (lambda_j + lambda) abs(a - (sqrt(lambda_j) b)/(lambda_j + lambda))^2 + (lambda abs(b)^2)/(lambda_j + lambda), $
  so each summand is minimized exactly at $a_j^* = sqrt(lambda_j) b_j \/ (lambda_j + lambda)$. Since
  $abs(a_j^*) <= abs(b_j) \/ (2 sqrt(lambda))$ (by $lambda_j + lambda >= 2 sqrt(lambda_j lambda)$), $a^* in ell^2(J)$;
  minimizing every summand separately therefore minimizes the sum, and $a^*$ is the unique minimizer.
  Hence the regularized minimizer $f_(P, lambda)$ of @def:reg-regularized-risk is
  $ f_(P, lambda) = sum_(j in J) lambda_j / (lambda_j + lambda) ip(f_P, e_j)_(L^2(P_X)) e_j . $ <eq:mercer-filter>
  Regularization acts as a *spectral filter*. Components along eigenfunctions with $lambda_j >> lambda$
  are kept almost unchanged, components with $lambda_j << lambda$ are damped by the factor
  $lambda_j \/ lambda approx 0$, and the component in $Ker T_K$ is lost entirely (@fig:mercer-filter). The
  same computation gives the approximation error of @def:stab-approx-error:
  $ A(lambda) = inf_(f in H_K) risk(L, P, lambda)(f) - inf_(f in H_K) risk(L, P)(f) = sum_(j in J) (lambda abs(b_j)^2) / (lambda_j + lambda), $
  because $inf_(f in H_K) risk(L, P)(f) = sigma_P^2 + norm(f_P^0)^2$ (the closure of $iota(H_K)$ is
  $(Ker T_K)^perp$). By dominated convergence $A(lambda) -> 0$ as $lambda -> 0$. By monotone convergence,
  $A(lambda) <= c lambda$ for all $lambda > 0$ holds if and only if $sum_j abs(b_j)^2 \/ lambda_j <= c$. Hence
  $A(lambda) = O(lambda)$ if and only if $sum_j abs(b_j)^2 \/ lambda_j < oo$, i.e. (by
  @prop:mercer-rkhs-spectral (ii)) if and only if the projection of $f_P$ onto $(Ker T_K)^perp$ has a
  representative in $H_K$, which is then the minimizer of $risk(L, P)$ over $H_K$. This is a
  concrete instance of @cor:stab-equivalences.

  In operator language, @eq:mercer-filter says $iota f_(P, lambda) = (T_K + lambda)^(-1) T_K f_P$ and
  $f_(P, lambda) = S_K (T_K + lambda)^(-1) f_P$, the classical Tikhonov-regularized solution; this is how
  the formula is derived from the integral equation of @sec:reg in the discussion following @ex:reg-krr. The computation uses only that
  $(sqrt(lambda_j) e_j)$ is an orthonormal basis of $H_K$ whose elements are orthogonal in $L^2(P_X)$; in
  @ex:stab-spectral it is carried out for orthonormal-series kernels without the hypotheses of Mercer's theorem
  (there the eigenvalues are called $w_j$ and the coefficients $b_j$ are called $beta_j$), and the
  resulting approximation error function is studied in detail.
] <ex:mercer-filter>

#figure(
  cetz.canvas({
    plot.plot(
      size: (9, 4.5),
      x-label: [eigenvalue index $j$],
      y-label: [$lambda_j \/ (lambda_j + lambda)$],
      x-tick-step: 5,
      y-tick-step: 0.25,
      x-min: 1,
      x-max: 30,
      y-min: 0,
      y-max: 1.05,
      legend: "inner-north-east",
      {
        plot.add(domain: (1, 30), samples: 60, j => 1 / (1 + 0.1 * j * j), label: $lambda = 10^(-1)$)
        plot.add(domain: (1, 30), samples: 60, j => 1 / (1 + 0.01 * j * j), label: $lambda = 10^(-2)$)
        plot.add(domain: (1, 30), samples: 60, j => 1 / (1 + 0.001 * j * j), label: $lambda = 10^(-3)$)
      },
    )
  }),
  caption: [The spectral filter $lambda_j \/ (lambda_j + lambda)$ of @eq:mercer-filter for eigenvalues
    $lambda_j = j^(-2)$ and three regularization parameters. Eigen-directions with $lambda_j >> lambda$
    pass almost unchanged; the others are suppressed. Decreasing $lambda$ lets more "frequencies" through.],
) <fig:mercer-filter>

== Examples: orthonormal series, the torus and the sphere <sec:mercer-examples>

In all examples of this section the kernel is _constructed_ from a prescribed orthonormal system, so the
eigensystem of $T_K$ is known in advance. This is the typical way of designing kernels with prescribed
smoothness.

#example(title: [Orthonormal-series kernels])[
  Let $(X, d)$ be a compact metric space and $mu$ a finite Borel measure with $supp mu = X$. Let
  $(phi_k)_(k in I)$, $I$ countable, be continuous functions that are orthonormal in $L^2(mu)$, and let
  $w_k >= 0$ be weights such that $sum_(k in I) w_k abs(phi_k (x))^2$ converges _uniformly_ on $X$ (that is,
  for every $epsilon > 0$ there is a finite $F subset I$ with $sum_(k in.not F) w_k abs(phi_k (x))^2 < epsilon$ for
  all $x$). A simple sufficient condition is $sum_k w_k norm(phi_k)_oo^2 < oo$. Define
  $ K(x, y) := sum_(k in I) w_k phi_k (x) overline(phi_k (y)), quad x, y in X . $
  + The series converges absolutely and uniformly on $X times X$, and $K$ is a continuous positive definite
    kernel.
  + $T_K g = sum_(k in I) w_k ip(g, phi_k)_(L^2(mu)) phi_k$. The nonzero eigenvalues of $T_K$ are the positive
    $w_k$; an eigensystem is given by $(w_k, phi_k)_(k in I_+)$, $I_+ := {k : w_k > 0}$, enumerated so that the
    weights are nonincreasing; and $Ker T_K = {phi_k : k in I_+}^perp$.
  + $H_K = {sum_(k in I_+) c_k phi_k : sum_(k in I_+) abs(c_k)^2 \/ w_k < oo}$ with
    $norm(f)_(H_K)^2 = sum_(k in I_+) abs(c_k)^2 \/ w_k$, where $c_k = ip(f, phi_k)_(L^2(mu))$.

  In particular, if $(phi_k)$ is an orthonormal _basis_ of $L^2(mu)$ and all $w_k > 0$, then $Ker T_K = {0}$ and
  $H_K$ consists of the continuous representatives of the classes $f in L^2(mu)$ with
  $sum_k abs(ip(f, phi_k))^2 \/ w_k < oo$.
] <ex:mercer-series>

#proof[
  (i) For a finite set $F subset I$ with $sum_(k in.not F) w_k abs(phi_k (z))^2 < epsilon$ for all $z$, the
  Cauchy–Schwarz inequality gives
  $sum_(k in.not F) w_k abs(phi_k (x)) abs(phi_k (y)) <= epsilon$ for all $x, y$. Hence the family is absolutely
  summable, uniformly on $X times X$, and $K$ is continuous as a uniform limit of continuous finite partial
  sums. For $x_1, ..., x_n in X$ and $c in KK^n$,
  $ sum_(i, l) overline(c_i) c_l K(x_i, x_l) = sum_(k in I) w_k (sum_i overline(c_i) phi_k (x_i)) (sum_l c_l overline(phi_k (x_l))) = sum_(k in I) w_k abs(sum_i overline(c_i) phi_k (x_i))^2 >= 0, $
  and $K$ is Hermitian, so $K$ is positive definite.

  (ii) For fixed $x$, the series defining $K(x, y)$ converges uniformly in $y$, and $g in L^2(mu) subset.eq L^1(mu)$
  because $mu$ is finite. We may therefore integrate term by term:
  $ integral_X K(x, y) g(y) dif mu(y) = sum_k w_k phi_k (x) integral_X overline(phi_k (y)) g(y) dif mu(y) = sum_k w_k ip(g, phi_k) phi_k (x) . $
  Hence $T_K phi_k = w_k phi_k$, and $T_K g = 0$ for $g perp {phi_k : k in I_+}$. If $T_K g = w g$ with $w > 0$,
  then $g = w^(-1) T_K g$ lies in $overline(spn){phi_k : k in I_+}$ and
  $w ip(g, phi_k) = w_k ip(g, phi_k)$ for all $k$, so $g in overline(spn){phi_k : w_k = w}$. Therefore the
  eigenspace of $w$ is $overline(spn){phi_k : w_k = w}$ (finite-dimensional since $T_K$ is compact), and
  $(phi_k)_(k in I_+)$ is an orthonormal basis of $(Ker T_K)^perp$ consisting of eigenvectors. Since only
  finitely many $w_k$ exceed any given $epsilon > 0$ (compactness), they can be enumerated in nonincreasing
  order.

  (iii) This is @prop:mercer-rkhs-spectral (i) with $a_k = c_k \/ sqrt(w_k)$, together with (ii) of that
  proposition.
]

For instance, the Legendre polynomials $P_k$ on $X = [-1, 1]$ with $mu = dif x \/ 2$ give the orthonormal
basis $phi_k = sqrt(2k + 1) P_k$ with $norm(phi_k)_oo = sqrt(2k + 1)$. Any weights with
$sum_k w_k (2k + 1) < oo$ produce a continuous positive definite kernel whose RKHS consists of the
functions with Legendre coefficients $c_k$ satisfying $sum_k abs(c_k)^2 \/ w_k < oo$. The polynomial weights
$w_k = (k + 1)^(-s)$, $s > 2$, give the Legendre example of @ex:rkhs-kernels (there with the Lebesgue
measure, which only rescales the $phi_k$ and the eigenvalues by a factor $2$): the larger $s$, the smoother
the functions. Geometric weights $w_k = rho^k$, $0 < rho < 1$, force geometric decay of the coefficients,
and one can show that such functions extend holomorphically to a neighbourhood of $[-1, 1]$ in $CC$.
In @sec:rkhs the RKHS of an orthonormal-series kernel was computed directly from the series; here we see in
addition that the $phi_k$ are exactly the eigenfunctions of $T_K$, so that such kernels are the
prototypes of Mercer's theorem.

=== The torus

#example(title: [Translation-invariant kernels on the torus])[
  Let $d in NN$ and $TT^d := RR^d \/ (2 pi ZZ)^d$. We identify functions on $TT^d$ with functions on $RR^d$
  that are $2 pi$-periodic in each variable. With the metric
  $d(x, y) := min_(m in ZZ^d) abs(x - y - 2 pi m)$, $TT^d$ is a compact metric space. Let $mu$ be the
  normalized Lebesgue measure, $dif mu = (2 pi)^(-d) dif x$ on $[0, 2 pi)^d$; it is translation invariant and has
  full support. The functions
  $ e_k (x) := e^(i k dot x), quad k in ZZ^d, $
  form an orthonormal basis of $L^2(TT^d, mu)$. Orthonormality is a direct computation. For completeness,
  the trigonometric polynomials form a subalgebra of $C(TT^d)$ that is closed under conjugation, contains
  the constants and separates the points of $TT^d$, so they are dense in $C(TT^d)$ by the Stone–Weierstrass
  theorem (@thm:app-stone-weierstrass); and $C(TT^d)$ is dense in $L^2(mu)$. For $f in L^2(mu)$ let
  $hat(f)(k) := ip(f, e_k)_(L^2(mu)) = integral f(x) e^(-i k dot x) dif mu(x)$ be its Fourier coefficients.

  Let $w = (w_k)_(k in ZZ^d)$ with $w_k >= 0$ and $sum_k w_k < oo$, and define
  $ K(x, y) := sum_(k in ZZ^d) w_k e^(i k dot (x - y)) = kappa(x - y), quad kappa(t) := sum_(k in ZZ^d) w_k e^(i k dot t) . $
  Since $abs(e_k (x))^2 = 1$, this is an orthonormal-series kernel as in @ex:mercer-series (the series
  $sum_k w_k abs(e_k (x))^2 = sum_k w_k$ converges uniformly). Hence:
  + $K$ is a continuous, positive definite, translation-invariant kernel. It is real-valued if and only if
    $w_k = w_(-k)$ for all $k$, and then $K(x, y) = w_0 + 2 sum_(k in Z_+) w_k cos(k dot (x - y))$, where
    $Z_+$ contains exactly one element of each pair ${k, -k}$, $k != 0$.
  + The eigensystem of $T_K$ is $(w_k, e_k)_(w_k > 0)$: $T_K$ multiplies Fourier coefficients by $w_k$,
    $(T_K g)^and (k) = w_k hat(g)(k)$. Mercer's expansion is the Fourier series of $kappa$.
  + $H_K = {f in C(TT^d) : hat(f)(k) = 0 "whenever" w_k = 0, space sum_(w_k > 0) abs(hat(f)(k))^2 \/ w_k < oo}$
    with $norm(f)_(H_K)^2 = sum_(w_k > 0) abs(hat(f)(k))^2 \/ w_k$.
  + *(Trigonometric polynomials.)* If $F := {k : w_k > 0}$ is finite, e.g. $F = {k : abs(k)_oo <= n}$, then
    $H_K = spn{e_k : k in F}$ is a space of trigonometric polynomials: a band-limited RKHS.
  + *(Sobolev spaces.)* For $w_k = (1 + abs(k)^2)^(-s)$ we have $sum_k w_k < oo$ if and only if $s > d\/2$
    (@ex:mercer-exercise-sobolev), and then
    $ H_K = H^s (TT^d) := {f in L^2(mu) : sum_(k in ZZ^d) (1 + abs(k)^2)^s abs(hat(f)(k))^2 < oo}, quad
      norm(f)_(H_K)^2 = sum_(k in ZZ^d) (1 + abs(k)^2)^s abs(hat(f)(k))^2, $
    where each class in $H^s (TT^d)$ is identified with its (unique) continuous representative. For weights
    with $c_1 (1 + abs(k)^2)^(-s) <= w_k <= c_2 (1 + abs(k)^2)^(-s)$, $H_K = H^s (TT^d)$ with an equivalent norm.
] <ex:mercer-torus>

The Sobolev case deserves a closer look. That every element of $H^s (TT^d)$ has a continuous
representative when $s > d\/2$ is the Sobolev embedding theorem on the torus; here it comes for free, since
$H_K subset.eq C(TT^d)$. We even get the explicit bound $norm(f)_oo <= sqrt(kappa(0)) norm(f)_(H^s)$ from
$abs(f(x)) <= sqrt(K(x, x)) norm(f)_(H_K)$. For $d = 1$ and $s = 1$, the classical formula
$sum_(k in ZZ) e^(i k t) \/ (1 + k^2) = pi cosh(pi - t) \/ sinh(pi)$ for $t in [0, 2 pi]$ gives the explicit
kernel
$ K(x, y) = pi / sinh(pi) cosh(pi - abs(x - y)), quad abs(x - y) <= pi, $
extended periodically, and for continuously differentiable (or, more generally, absolutely continuous with
square-integrable derivative) periodic $f$, integration by parts gives $(f')^and (k) = i k hat(f)(k)$, so
$ norm(f)_(H_K)^2 = sum_k (1 + k^2) abs(hat(f)(k))^2 = norm(f)_(L^2(mu))^2 + norm(f')_(L^2(mu))^2 . $
Here the regularizer $lambda norm(f)_(H_K)^2$ is literally a penalty on the derivative. Regularized least
squares with such kernels leads to periodic smoothing splines @wahba1990. @fig:mercer-torus-kernels
compares this kernel with a band-limited one.

#figure(
  cetz.canvas({
    plot.plot(
      size: (9, 5),
      x-label: $t = x - y$,
      y-label: [$kappa(t) \/ kappa(0)$],
      x-tick-step: 1,
      y-tick-step: 0.5,
      x-min: -3.2,
      x-max: 3.2,
      y-min: -0.35,
      y-max: 1.65,
      legend: "inner-north-east",
      {
        plot.add(
          domain: (-calc.pi, calc.pi),
          samples: 120,
          t => calc.cosh(calc.pi - calc.abs(t)) / calc.cosh(calc.pi),
          label: [$w_k = (1 + k^2)^(-1)$],
        )
        plot.add(
          domain: (-calc.pi, calc.pi),
          samples: 181,
          t => if calc.abs(t) < 1e-6 { 1 } else { calc.sin(3.5 * t) / (7 * calc.sin(t / 2)) },
          label: [$w_k = 1\/7$ for $abs(k) <= 3$],
        )
      },
    )
  }),
  caption: [Two translation-invariant kernels $K(x, y) = kappa(x - y)$ on the circle, normalized to
    $kappa(0) = 1$. The Sobolev kernel of $H^1(TT)$ has slowly decaying weights and a kink at $t = 0$; its
    RKHS is infinite-dimensional. The band-limited (Dirichlet) kernel has seven nonzero weights, and its
    RKHS consists of the trigonometric polynomials of degree at most $3$.],
) <fig:mercer-torus-kernels>

Mercer's theorem also shows that _every_ continuous positive definite translation-invariant kernel on the
torus is of the form of @ex:mercer-torus. This is the torus version of Bochner's theorem on positive
definite functions.

#proposition[
  Let $kappa: TT^d -> CC$ be continuous such that $K(x, y) := kappa(x - y)$ is a positive definite kernel on
  $TT^d$. Then $hat(kappa)(k) >= 0$ for all $k in ZZ^d$, $sum_k hat(kappa)(k) = kappa(0) < oo$, and
  $kappa(t) = sum_k hat(kappa)(k) e^(i k dot t)$ with absolute and uniform convergence.
] <prop:mercer-torus-bochner>

#proof[
  By translation invariance of $mu$ (substitute $t = x - y$),
  $ (T_K e_k)(x) = integral kappa(x - y) e^(i k dot y) dif mu(y) = e^(i k dot x) integral kappa(t) e^(-i k dot t) dif mu(t) = hat(kappa)(k) e_k (x) . $
  So the bounded operator $T_K$ acts diagonally on the orthonormal basis $(e_k)$, i.e.
  $T_K g = sum_k hat(kappa)(k) hat(g)(k) e_k$ by continuity. Positivity of $T_K$
  (@thm:mercer-integral-operator (iii)) gives $hat(kappa)(k) = ip(T_K e_k, e_k) >= 0$. As in the proof of
  @ex:mercer-series (ii), the pairs $(hat(kappa)(k), e_k)$ with $hat(kappa)(k) > 0$, enumerated in
  nonincreasing order, form an eigensystem of $T_K$. Mercer's theorem (@thm:mercer) yields
  $ kappa(x - y) = sum_(k in ZZ^d) hat(kappa)(k) e^(i k dot x) e^(-i k dot y) $
  absolutely and uniformly, and $sum_k hat(kappa)(k) = integral K(x, x) dif mu(x) = kappa(0)$. Put $y = 0$.
]

=== The sphere

The sphere is the prototype of a curved compact space, and here the role of the Fourier basis is played
by the spherical harmonics, the eigenfunctions of the Laplace–Beltrami operator. We recall the facts we
need; proofs can be found in @atkinson2012[Ch. 2–3].

Let $d >= 2$ and $SS^d := {x in RR^(d+1) : abs(x) = 1}$ with the geodesic distance
$rho(x, y) = arccos(x dot y)$ and the surface measure $sigma$, whose total mass is
$abs(SS^d) = 2 pi^((d+1)\/2) \/ Gamma((d+1)\/2)$ (e.g. $abs(SS^2) = 4 pi$). The case $d = 1$ is the circle
$TT$ treated above.

*The Laplace–Beltrami operator.* On a compact Riemannian manifold $(M, g)$ it is given in local
coordinates by
$ Delta_M f = 1/sqrt(abs(g)) sum_(i, l = 1)^(dim M) partial_i (sqrt(abs(g)) g^(i l) partial_l f), $
where $abs(g) = det(g_(i l))$ and $(g^(i l)) = (g_(i l))^(-1)$. For $M = SS^d$ it can be read off from the
Laplacian of $RR^(d+1)$ in polar coordinates $x = r xi$, $r > 0$, $xi in SS^d$:
$ Delta_(RR^(d+1)) = partial_r^2 + d/r partial_r + 1/r^2 Delta_(SS^d) . $
The operator $-Delta_M$ is unbounded, symmetric and nonnegative on $C^oo (M) subset L^2(M)$, and it is
essentially self-adjoint there. It is _not_ compact (it is not even bounded), but its resolvent
$(I - Delta_M)^(-1)$ is a compact, positive, self-adjoint operator on $L^2(M)$. The spectral theorem
(@thm:app-spectral), applied to the resolvent, therefore yields an orthonormal basis of $L^2(M)$ of
(smooth) eigenfunctions of $-Delta_M$, with eigenvalues $0 = nu_0 <= nu_1 <= ... -> oo$.

*Spherical harmonics.* A spherical harmonic of degree $k in NN_0$ is the restriction to $SS^d$ of a
polynomial $p$ on $RR^(d+1)$ that is homogeneous of degree $k$ and harmonic, $Delta p = 0$. Let
$cal(H)_k$ denote the space of these functions (not to be confused with an RKHS $H_K$). Writing
$p(r xi) = r^k Y(xi)$ and applying the polar formula,
$ 0 = Delta p = (k(k - 1) + d k) r^(k-2) Y + r^(k-2) Delta_(SS^d) Y, quad "so" quad -Delta_(SS^d) Y = k(k + d - 1) Y . $
The following facts are standard @atkinson2012:
+ $dim cal(H)_k = h_d (k) := (2k + d - 1) ((k + d - 2)!) / (k! (d-1)!)$; e.g. $h_d (0) = 1$,
  $h_d (1) = d + 1$, and $h_2 (k) = 2k + 1$.
+ The spaces $cal(H)_k$ are mutually orthogonal in $L^2(SS^d, sigma)$, and $L^2(SS^d, sigma)$ is the
  closure of $plus.o.big_(k >= 0) cal(H)_k$. They are exactly the eigenspaces of $-Delta_(SS^d)$.
+ *(Addition theorem.)* For every orthonormal basis $(Y_(k, l))_(l = 1)^(h_d (k))$ of $cal(H)_k$,
  $ sum_(l = 1)^(h_d (k)) Y_(k, l)(x) overline(Y_(k, l)(y)) = (h_d (k)) / abs(SS^d) P_k^((d)) (x dot y), quad x, y in SS^d, $ <eq:mercer-addition>
  where $P_k^((d))$ is the Legendre polynomial of degree $k$ in dimension $d + 1$ (denoted $P_(k, d+1)$ in
  @atkinson2012), normalized by $P_k^((d))(1) = 1$ and satisfying $abs(P_k^((d))(t)) <= 1$ on $[-1, 1]$. It
  is proportional to the Gegenbauer polynomial $C_k^(((d-1)\/2))$ and to the Jacobi polynomial
  $P_k^((d\/2 - 1, space d\/2 - 1))$. For $d = 2$ it is the classical Legendre polynomial $P_k$.

#align(center, block(breakable: false, table(
  columns: 4,
  align: center + horizon,
  stroke: (x, y) => (top: if y == 1 { 0.6pt } else { 0pt }),
  table.header([degree $k$], [eigenvalue of $-Delta_(SS^d)$], [$dim cal(H)_k$ on $SS^d$], [$dim cal(H)_k$ on $SS^2$]),
  [$0$], [$0$], [$1$], [$1$],
  [$1$], [$d$], [$d + 1$], [$3$],
  [$2$], [$2(d + 1)$], [$d(d + 3)\/2$], [$5$],
  [$k$], [$k(k + d - 1)$], [$h_d (k)$], [$2k + 1$],
)))

#example(title: [Zonal kernels on the sphere])[
  Let $d >= 2$, $mu = sigma$ on $SS^d$, and for each $k$ let $(Y_(k, l))_(l=1)^(h_d (k))$ be an orthonormal
  basis of $cal(H)_k$. By (ii), the whole family $(Y_(k, l))_(k, l)$ is an orthonormal basis of $L^2(SS^d)$
  consisting of continuous functions. Choose weights that depend only on the degree, $w_(k, l) = w_k >= 0$,
  with
  $ sum_(k >= 0) w_k h_d (k) < oo, $
  and define the orthonormal-series kernel
  $ K(x, y) := sum_(k >= 0) w_k sum_(l = 1)^(h_d (k)) Y_(k, l)(x) overline(Y_(k, l)(y)) = sum_(k >= 0) w_k (h_d (k)) / abs(SS^d) P_k^((d)) (x dot y) . $
  By the addition theorem, $sum_l abs(Y_(k, l)(x))^2 = h_d (k) \/ abs(SS^d)$ for every $x$, so the tails of
  $sum_(k, l) w_k abs(Y_(k, l)(x))^2$ do not depend on $x$, and the uniform-convergence hypothesis of
  @ex:mercer-series holds. Therefore:
  + $K$ is a continuous positive definite kernel that depends only on $x dot y = cos rho(x, y)$. Such
    kernels are called *zonal*; they are invariant under rotations, $K(Q x, Q y) = K(x, y)$ for orthogonal
    $Q$. The kernel does not depend on the choice of the bases $(Y_(k, l))_l$.
  + $T_K Y = w_k Y$ for every $Y in cal(H)_k$ (a form of the Funk–Hecke formula below). The nonzero
    eigenvalues are the positive $w_k$; if the positive $w_k$ are pairwise distinct, $w_k$ has
    multiplicity exactly $h_d (k)$.
  + Writing $f = sum_k f_k$ with $f_k in cal(H)_k$ the orthogonal projections in $L^2(sigma)$, the space
    $H_K$ consists of the continuous representatives of the classes
    $ {f in L^2(sigma) : f_k = 0 "whenever" w_k = 0, space sum_(w_k > 0) norm(f_k)_(L^2(sigma))^2 / w_k < oo}, quad "and" quad
      norm(f)_(H_K)^2 = sum_(w_k > 0) norm(f_k)_(L^2(sigma))^2 / w_k . $
  + *(Sobolev spaces.)* Since $c_d k^(d-1) <= h_d (k) <= C_d k^(d-1)$ for $k >= 1$, the weights
    $w_k = (1 + k(k + d - 1))^(-s)$ satisfy the summability condition if and only if $s > d\/2$. The
    resulting RKHS is the Sobolev space $H^s (SS^d)$, defined through the eigen-expansion of
    $-Delta_(SS^d)$, with norm $norm(f)^2 = sum_k (1 + k(k + d - 1))^s norm(f_k)^2$. The choice
    $w_k = e^(-t k(k + d - 1))$, $t > 0$, gives the *heat kernel* of the sphere.
] <ex:mercer-sphere>

The same construction works on any compact Riemannian manifold $M$: with an orthonormal eigenbasis
$(phi_j)$ of $-Delta_M$ and eigenvalues $nu_j$, one considers $K(x, y) = sum_j w(nu_j) phi_j (x) overline(phi_j (y))$
for a decreasing function $w$, such as $w(nu) = (1 + nu)^(-s)$ (Sobolev kernels, $s > dim M \/ 2$) or
$w(nu) = e^(-t nu)$ (heat kernels). Verifying the uniform-convergence hypothesis then requires bounds on
the eigenfunctions, which are available but beyond our scope. The sphere is special because the addition
theorem makes these bounds trivial.

#context-note[
  Conversely, a classical theorem of Schoenberg @schoenberg1942 states that a continuous function
  $kappa: [-1, 1] -> RR$ gives a positive definite kernel $kappa(x dot y)$ on $SS^d$ for a fixed $d$ if and
  only if $kappa = sum_k a_k P_k^((d))$ with $a_k >= 0$ and $sum_k a_k < oo$. This is the spherical analogue
  of @prop:mercer-torus-bochner, and it can be proved in the same way, using the *Funk–Hecke formula*
  @atkinson2012: for $Y in cal(H)_k$,
  $ integral_(SS^d) kappa(x dot y) Y(y) dif sigma(y) = abs(SS^(d-1)) (integral_(-1)^1 kappa(t) P_k^((d))(t) (1 - t^2)^((d-2)\/2) dif t) Y(x) . $
  Dot-product kernels such as $e^(x dot y)$ or $(1 + x dot y)^m$, restricted to the sphere, are zonal, and
  their eigenvalues can be computed with this formula. Spline smoothing on the sphere is treated in
  @wahba1990.
]

== Summary

- For a measurable kernel with separable RKHS and $abs(K)_p < oo$, the RKHS embeds continuously into
  $L^p (mu)$ with norm at most $abs(K)_p$. The (suitably identified) adjoint of the embedding is the
  integral operator $g |-> integral g(y) K_y dif mu(y)$, and density of $H_K$ in $L^p$ is equivalent to
  injectivity of this operator (@thm:mercer-lp-embedding).
- For $p = 2$: $S_K$ is Hilbert–Schmidt with $norm(S_K)_("HS") = abs(K)_2$, and $T_K = S_K^* S_K$ is the
  integral operator with kernel $K$ on $L^2(mu)$. It is compact, positive, self-adjoint and trace class, with
  $tr T_K = integral K(x, x) dif mu(x)$ and $norm(T_K)_("HS") = norm(K)_(L^2(mu times.o mu))$
  (@thm:mercer-integral-operator, @prop:mercer-ae-expansion).
- The eigenfunctions $e_j$ of $T_K$ have canonical representatives $lambda_j^(-1) S_K e_j in H_K$, and
  $(sqrt(lambda_j) e_j)$ is an orthonormal basis of $(Ker iota)^perp subset.eq H_K$
  (@prop:mercer-eigenfunctions). In general the kernel expansion in these functions holds only almost
  everywhere.
- *Mercer's theorem* (@thm:mercer): for continuous positive definite $K$ on a compact metric space and a
  finite measure of full support, $K(x, y) = sum_j lambda_j e_j (x) overline(e_j (y))$ absolutely and uniformly.
  Full support and positivity are both essential. Positivity of $T_K$ is equivalent to positive
  definiteness of $K$ (@lem:mercer-positivity).
- *Spectral picture* (@prop:mercer-rkhs-spectral): $H_K = {sum_j a_j sqrt(lambda_j) e_j : a in ell^2}$ and
  $norm(f)_(H_K)^2 = sum_j abs(ip(f, e_j)_(L^2))^2 \/ lambda_j$. Moreover $iota(H_K) = Ran T_K^(1\/2)$, and
  $T_K^(1\/2)$ is an isometry from $(Ker T_K)^perp$ onto $H_K$. The RKHS is a smoothness space governed by the eigenvalue decay, and regularization acts
  as the spectral filter $lambda_j \/ (lambda_j + lambda)$.
- On the torus, orthonormal-series kernels are Fourier multipliers, and their RKHSs range from
  trigonometric polynomials to Sobolev spaces $H^s (TT^d)$, $s > d\/2$. On the sphere, zonal kernels play
  the same role with spherical harmonics.

Next, in @sec:univ, we ask the opposite question: rather than describing how _small_ $H_K$ is, we ask when
it is _large_, namely dense in $C(X)$. Fourier kernels with all $w_k > 0$ will be our first examples of such
universal kernels (@ex:univ-fourier).

== Notes and further reading

The theory of integral equations with symmetric kernels goes back to Hilbert and Schmidt in the first
decade of the twentieth century. Mercer @mercer1909 proved the theorem that bears his name for continuous
kernels of "positive type" on a compact interval with Lebesgue measure. A classical proof that does not
use RKHSs is outlined in @ex:mercer-exercise-classical. The systematic theory of reproducing
kernels, which gives the much shorter proof presented here, is due to Aronszajn @aronszajn1950.

Our treatment of the embedding of $H_K$ into $L^p (mu)$, the operators $S_K$ and $T_K$, and Mercer's theorem
follows @steinwart2008[Ch. 4], where measurability issues are also discussed in detail. Mercer's theorem
has been extended to non-compact spaces and more general measures; the almost-everywhere expansion of
@prop:mercer-ae-expansion is a first step in that direction, and @steinwart2012mercer give a systematic
account of the interplay between measures, kernels and RKHSs in this generality. The integral operator
$T_K$ (denoted $L_K$ there) plays a central role in the approximation-theoretic approach to learning
theory of @cucker2007, where the regularity of the target function is expressed through the ranges of
powers of $T_K$, in the spirit of @ex:mercer-filter. An operator-theoretic introduction to RKHSs,
including Mercer's theorem, is @paulsen2016.

For the connections with probability, including Gaussian processes and Karhunen–Loève expansions, see
@berlinet2004 and, from the machine-learning side, @rasmussen2006. Kernel PCA was introduced in
@schoelkopf1998 (see also @schoelkopf2002), and the Nyström extension of @ex:mercer-nystrom was popularized
as a tool for speeding up kernel machines by @williams2001. Historically, Mercer's theorem was the
justification of the kernel trick in the SVM literature @vapnik1998 @cortes1995.

The spectral theorem for compact self-adjoint operators and the theory of Hilbert–Schmidt and trace-class
operators are covered in @werner2018 and @brezis2011. The Fourier-analytic side of the torus examples,
including the existence of continuous functions with divergent Fourier series used in
@rem:mercer-indefinite, is in @rudin1987. Spherical harmonics, the addition theorem and the Funk–Hecke
formula are treated in detail in @atkinson2012. Smoothing splines on the circle and on the sphere, which
are regularized least squares estimators in the RKHSs of @ex:mercer-torus and @ex:mercer-sphere, are the
subject of @wahba1990.

== Exercises

#exercise(title: [Norm of the embedding])[
  In the setting of @thm:mercer-integral-operator, show that $norm(iota) = sqrt(lambda_1)$ if $T_K != 0$ (and
  $iota = 0$ otherwise), where $lambda_1 = norm(T_K)$ is the largest eigenvalue. Deduce that
  $norm(iota) <= abs(K)_2$, with equality if and only if $T_K$ has rank at most one.

  _Hint:_ $norm(iota)^2 = norm(S_K)^2 = norm(T_K)$ by @thm:mercer-integral-operator (iii), and compare
  $lambda_1$ with $sum_j lambda_j = abs(K)_2^2$.
] <ex:mercer-exercise-norm>

#exercise(title: [Size of eigenvalues and eigenfunctions])[
  (a) Let $lambda_1 >= lambda_2 >= ... >= 0$ with $sum_j lambda_j < oo$. Show that $j lambda_j -> 0$. _Hint:_
  $floor(j\/2) lambda_j <= sum_(j\/2 < i <= j) lambda_i$.
  (b) In the Mercer setting, show that $norm(e_j)_oo <= abs(K)_oo \/ sqrt(lambda_j)$, and that
  $sum_j lambda_j norm(e_j)_oo^2$ may be infinite even though $sum_j lambda_j abs(e_j (x))^2 = K(x, x)$ is
  bounded. _Hint for the second part:_ use @ex:mercer-series with $phi_k$ having disjoint supports.
] <ex:mercer-exercise-decay>

#exercise(title: [Brownian motion])[
  Let $X = [0, 1]$ with Lebesgue measure and $K(x, y) = min{x, y}$.
  (a) Show that $u = T_K g$ satisfies
  $u(x) = integral_0^x y g(y) dif y + x integral_x^1 g(y) dif y$, hence $u(0) = 0$, $u'(1) = 0$ and $u'' = -g$
  for continuous $g$.
  (b) Deduce that the eigenpairs are $lambda_j = ((j - 1\/2) pi)^(-2)$,
  $e_j (x) = sqrt(2) sin((j - 1\/2) pi x)$, $j in NN$.
  (c) Write down Mercer's expansion of $min{x, y}$ and verify the trace formula using
  $sum_(j >= 1) (2j - 1)^(-2) = pi^2 \/ 8$.
  (d) Show that $(sqrt(lambda_j) e_j)'$ is an orthonormal basis of $L^2[0, 1]$, and conclude with
  @prop:mercer-rkhs-spectral that $H_K$ is the space
  ${f : f(0) = 0, f "absolutely continuous", f' in L^2}$ with $norm(f)_(H_K) = norm(f')_(L^2)$ of
  @prop:rkhs-sobolev. (With independent standard normal $xi_j$, the series $sum_j xi_j sqrt(lambda_j) e_j (t)$ is the
  Karhunen–Loève expansion of Brownian motion.)
] <ex:mercer-exercise-brownian>

#exercise(title: [The classical proof of Mercer's theorem])[
  Prove @thm:mercer without using $H_K$, for a continuous Hermitian kernel $A$ with positive integral operator
  $T_A$, along the lines of @mercer1909:
  (a) $T_A$ maps $L^2(mu)$ into $C(X)$; hence the eigenfunctions have continuous representatives, unique by
  @prop:mercer-support.
  (b) The remainder $A_n (x, y) := A(x, y) - sum_(j <= n) lambda_j e_j (x) overline(e_j (y))$ is continuous and
  Hermitian, and $T_(A_n) = sum_(j > n) lambda_j ip(dot, e_j) e_j$ is positive. By @lem:mercer-positivity,
  $A_n$ is positive definite; conclude $sum_j lambda_j abs(e_j (x))^2 <= A(x, x)$.
  (c) For fixed $x$, the series $B(x, y) := sum_j lambda_j e_j (x) overline(e_j (y))$ converges uniformly in $y$,
  and $integral (B(x, y) - A(x, y)) g(y) dif mu(y) = 0$ for all $g in L^2(mu)$; deduce $B = A$.
  (d) Conclude with Dini's theorem and the Cauchy–Schwarz inequality as in the proof of @thm:mercer.
] <ex:mercer-exercise-classical>

#exercise(title: [The Poisson kernel])[
  On $TT$, let $w_k = rho^(abs(k))$ with $0 < rho < 1$. Show that
  $K(x, y) = (1 - rho^2) \/ (1 - 2 rho cos(x - y) + rho^2)$, and that every $f in H_K$ is the restriction to the
  unit circle of a function holomorphic in the annulus $rho^(1\/2) < abs(z) < rho^(-1\/2)$.
  _Hint:_ $abs(hat(f)(k)) <= norm(f)_(H_K) rho^(abs(k)\/2)$; consider $sum_k hat(f)(k) z^k$.
] <ex:mercer-exercise-poisson>

#exercise(title: [Sobolev weights])[
  Show that $sum_(k in ZZ^d) (1 + abs(k)^2)^(-s) < oo$ if and only if $s > d\/2$, by comparing the sum with
  $integral_(RR^d) (1 + abs(x)^2)^(-s) dif x$. Deduce the Sobolev embedding
  $norm(f)_oo <= C_(d, s) norm(f)_(H^s (TT^d))$ for $s > d\/2$ from @ex:mercer-torus.
] <ex:mercer-exercise-sobolev>

#exercise(title: [Measures without full support])[
  Let $(X, d)$ be compact metric, $mu$ a finite Borel measure, and $K$ continuous and positive definite, but
  do not assume $supp mu = X$. Let $X_0 := supp mu$.
  (a) Show that $X_0$ is compact and $mu(X without X_0) = 0$. _Hint:_ $X without X_0$ is a union of open null
  sets, and $X$ is second countable.
  (b) Show that the eigenpairs of $T_K$ on $L^2(X, mu)$ and of $T_(K_0)$ on $L^2(X_0, mu)$, with
  $K_0 = K|_(X_0 times X_0)$, correspond to each other, and deduce that @eq:mercer-expansion holds uniformly on
  $X_0 times X_0$ (use @prop:rkhs-sum-restriction for the RKHS of $K_0$).
  (c) Give an example where it fails at a point of $(X without X_0) times (X without X_0)$.
] <ex:mercer-exercise-support>

#exercise(title: [An indefinite kernel])[
  On $TT$ with $mu = dif x \/ (2 pi)$, let $A(x, y) = cos(x - y) - cos(2(x - y))$. Compute the eigenvalues of $T_A$
  and show that $T_A$ is not positive. Find two points $x_1, x_2$ for which the matrix
  $(A(x_i, x_l))_(i, l = 1)^2$ is not positive semidefinite, in accordance with @lem:mercer-positivity.
] <ex:mercer-exercise-indefinite>
